### ISSUE TITLE
JavaScript doesn't launch without an HTML page

### ISSUE THREAD

**Issue by talentlessguy** [spckio/spck-issues#1]
It is unconvenient that you have to create HTML, then insert a link to a script and only then you can use JS. I suggest to run JS automatically, I mean you wrote some JS code and when clicking "Run" you see the result that runs on a temp HTML file that is not displayed until it is attached. Or you can just remove the "Run" button if the file type isn't HTML.

**Comment by spck-io** [comment]
I don't think removing the run button if the file type isn't HTML is a good idea. That would require navigating to the main HTML page every time you want to test the project.

You can also set a default HTML page as explained here as well for projects with multiple HTML files: https://spckio.github.io/spck-documentation/getting-started/#setting-default-launch-file

I will consider adding an "Evaluate" button to quickly test JS snippets, but there are already solutions out there that lets you quickly test JS output.

**Comment by talentlessguy** [comment]
@spck-io you can add "Eval code if default HTML not set" in app settings. It would be great!

**Comment by spck-io** [comment]
Cooliyo, just wondering what are you typically using this feature for? D3 projects, or testing output of function?

**Comment by Proxtx** [comment]
Close this issue!
