### ISSUE TITLE
I can not copy

### ISSUE THREAD

**Issue by Poker9x** [spckio/spck-issues#100]
I don't find the copy dialog in the new version

**Comment by brettjrea** [comment]
Same just generally having all types of hold for context menu issues. I love this app otherwise, hope for a fix so I can use it again.

**Comment by Poker9x** [comment]
> Same just generally having all types of hold for context menu issues. I love this app otherwise, hope for a fix so I can use it again.
yes

**Comment by spck-io** [comment]
Can you provide more details on this? I’m not having any issues with copying during my testing.

**Comment by Poker9x** [comment]
> Bạn có thể cung cấp thêm chi tiết về điều này? Tôi không gặp vấn đề gì với việc sao chép trong quá trình thử nghiệm.

Oh. When did you fix it. Please keep developing, I enjoyed this app.
A few small suggestions are to grant audio permission and send ajax requests without HTTPS. thanks
