### ISSUE TITLE
I can't add images...

### ISSUE THREAD

**Issue by ghost** [spckio/spck-issues#101]
Utf-8 encoding problem....
![Screenshot_20200308-114239](https://user-images.githubusercontent.com/61907107/76157672-edd9ff00-6131-11ea-832d-46b67234f2e6.png)

**Comment by byrz-ell** [comment]
me too..

**Comment by spck-io** [comment]
Thanks for the bug report. I will release a fix for this as soon as possible.

**Comment by spck-io** [comment]
This has been fixed since 4.0.1.

**Comment by ghost** [comment]
Thanku..so Much
