### ISSUE TITLE
Can't push to github

### ISSUE THREAD

**Issue by Doublepicebs** [spckio/spck-issues#102]
![Screenshot_20200308-183611](https://user-images.githubusercontent.com/51971241/76167060-7e353580-616c-11ea-8066-1bc9f42c60e3.png)
This keeps popping

**Comment by spck-io** [comment]
Thanks, I will look into this ASAP.

**Comment by spck-io** [comment]
Having quite a bit of trouble replicating this. I have tried pushing with new and existing repos to GitHub/Bitbucket and not seeing this error. Do you mind explaining the steps to replicate this issue?

**Comment by Doublepicebs** [comment]
It happens if I try to push to github after creating a project.
Pushing seems to work with me when pushing a cloned repo.
