### ISSUE TITLE
Error with fetching

### ISSUE THREAD

**Issue by degoev** [spckio/spck-issues#103]
This code is correct, but I get an error with fetch
![Screenshot_20200309_104403](https://user-images.githubusercontent.com/50908619/76206528-4205e180-620d-11ea-9643-8e22608b7a92.jpg)
![Screenshot_20200309_104338](https://user-images.githubusercontent.com/50908619/76206531-43cfa500-620d-11ea-86a9-bf64909c82b8.jpg)

**Comment by nycki93** [comment]
I have this error too:

```js
async function main() {
  const f = await fetch('http://www.example.com')
  console.log(f)
}

main();

// -> Failed to fetch
```
