### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by ghost** [spckio/spck-issues#104]
JavaScript is not working in console

**Comment by Doublepicebs** [comment]
The console.log() and other console statements don't work, but Javascript in console excutions work

**Comment by ghost** [comment]
Will it be fixed in upcoming versions???

**Comment by spck-io** [comment]
Thanks for the bug report. Update 4.1.0 should fix this. Let me know if this is still an issue after the update.

**Comment by ghost** [comment]
Nope.....when I add line e.g console.log('hello'); .....It's not showing in the console at all but somehow I can execute those syntax from its actual console but not working when include JS file with that syntax

**Comment by spck-io** [comment]
Does the build version say 4.1.0 in settings? Are you adding the file to the index.html file? Lastly, did you check the “Override console” option in the console settings? Many other users have reported this issue have been fixed for them starting from 4.1.0, can you please check again?

**Comment by ghost** [comment]
Yes the build version says 4.1.0 in settings. Yup I am adding the file to index.html file. Lastly, I had checked the "Override console". I even cleared the data and restarted everything, still no clue, what's the error???
