### ISSUE TITLE
Emmet issues

### ISSUE THREAD

**Issue by Doublepicebs** [spckio/spck-issues#106]
![Screenshot_20200309-235145](https://user-images.githubusercontent.com/51971241/76260699-13b1f180-6261-11ea-85ac-4c05a8856c73.png)
Emmet started acting strangely in the last update

**Comment by Doublepicebs** [comment]
For example, it no longer adds the essential attributes for link for example, and adds a closing tag for **all** tags

**Comment by spck-io** [comment]
Thanks for the extra details. I will look into why this is happening.

**Comment by spck-io** [comment]
Update 4.1.0 should fix this. Let me know if this is still an issue after the update. Caused by some changes in the underlying HTML editor.
