### ISSUE TITLE
Npm emulator

### ISSUE THREAD

**Issue by Doublepicebs** [spckio/spck-issues#118]
Would be very useful to have a npm emulator to install packages, e.t.c. Along with a node.js starter kit.

**Comment by Proxtx** [comment]
To do this Spck editor needs access to the Android terminal but the only native thing of the Spck editor app is the webserver.
So: Spck would have to send a request to the webserver wich then have to execute the code and send the results back to Spck.
But the Spck webserver doesn't have access to the terminal at the moment.


P.S. @spck-io if you try to implement this feature: here is a app wich emulates npm / nodejs without root: [Google Play - Node JS](https://play.google.com/store/apps/details?id=io.tempage.dorynode) (Worked for me)

**Comment by mestery69** [comment]
I suggest that when we write in the dependencies / devDependencies part  of package.jsom, spck autocomplete and suggest dependencies, when we select a dependences, it write it accompanied by its version
  
For example
```json
{
  "...": "...",
  "dependecies": {
    "cha...": "// spck suggest and when i click on a proposition, it does write it",
    "chalk": "4.1.0 // spck has suggested, and i selected 'chalk', he wrote it"
  },
  "...": "..."
}
```

**Comment by Phemjay1** [comment]
> To do this Spck editor needs access to the Android terminal but the only native thing of the Spck editor app is the webserver.
> So: Spck would have to send a request to the webserver wich then have to execute the code and send the results back to Spck.
> But the Spck webserver doesn't have access to the terminal at the moment.
> 
> P.S. @spck-io if you try to implement this feature: here is a app wich emulates npm / nodejs without root: [Google Play - Node JS](https://play.google.com/store/apps/details?id=io.tempage.dorynode) (Worked for me)

Can this work with spck editor?
Please how do I start running terminal on spck because I tried to run it but it's telling me my input not found?
