### ISSUE TITLE
Problem cloning repo if it contains symlink

### ISSUE THREAD

**Issue by dperezb** [spckio/spck-issues#121]
Hi,

First of all, the app is really interesting and well made. I've been using it to fix some problems on the go in a couple of github repos and it's amazing.

The problem i'm reporting appears when there's a symlink inside the repo, the app throws the following error:

ERROR:
symlink failed: ENOENT (No such file or directory)

It fails to clone the repo. If you restart the app, the project appears, but it is incomplete. I tried a couple of repos with symlinks inside, same problem.

![Screenshot_20200401-004915_Spck Editor](https://user-images.githubusercontent.com/1334635/78098298-0b0e9000-73b5-11ea-9108-f50b59c14dbd.jpg)

**Comment by spck-io** [comment]
It seems symlinks are a security concern on Android systems. As Android does not want you to be creating links to system files, it checks the target of each symlink before creation to make sure it points within the app directory. I have changed the error message for “failure to create symlinks” as an operating system problem.
