### ISSUE TITLE
Cannot push to Azure Devops

### ISSUE THREAD

**Issue by markus2810** [spckio/spck-issues#124]
I was able to clone a git repo from Azure DevOps, but push fails with error HTTP URL cannot be found.

Seems only to occur on master branch.

**Comment by spck-io** [comment]
I am not able to replicate this issue. Be sure to allow the app token Read + Write permissions and allow access to all accessible organizations. Please let me know if you are still having issues, I have tested with an Azure DevOps and did not experience any problems.

**Comment by bcoudrin** [comment]
I have the same issue, with a token generated from the clone menu, and with a token generated from PAT page, both changed to full permission without success.
Moreover if I try to add the repo in the remote menu, it says that the URL is not valid.

**Comment by spck-io** [comment]
There seems to be a setting that prevents pushing to master, please see:
https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops&viewFallbackFrom=vsts

Unfortunately, I have checked and it seem my Azure DevOps account has been banned for apparently no reason... It is a brand new account that I opened to specifically test this issue. It is not advisable to use DevOps as they will seemingly ban people's accounts for no reason and you will get locked out of all your data...
