### ISSUE TITLE
I can't see my github branches

### ISSUE THREAD

**Issue by AlejandroParada** [spckio/spck-issues#126]
I have created other branches in my repo, but can't refresh and see then in the app

**Comment by spck-io** [comment]
You need to do a fetch/pull to get remote branches.

**Comment by AlejandroParada** [comment]
That is in github, only see origin from remote, not see any other branch. Fetch/pull not get the others from remote

**Comment by spck-io** [comment]
I have made a fix to git checkout in the latest version 4.3.4. Please update and let me know if that fixes this issue.
