### ISSUE TITLE
Is there a way for the latest version  to work on Android 6.0?

### ISSUE THREAD

**Issue by Doublepicebs** [spckio/spck-issues#127]
I can't find the app on Google Play Store

**Comment by Proxtx** [comment]
Found it on Google Play Store

**Comment by Proxtx** [comment]
https://play.google.com/store/apps/details?id=io.spck

**Comment by Doublepicebs** [comment]
Ok found it, it seems that the latest update doesn't support my Android 6.0, is there any way to bypass this problem and let it work on my Android? @Proxtx

**Comment by Doublepicebs** [comment]
Can the web client (PWA) run the latest version?

**Comment by Proxtx** [comment]
https://drive.google.com/file/d/1pqic3VUvKwtzaqEggFWjEMF2EIsjO4wm/view?usp=drivesdk

This is my version of the app(4.3.0)
Maybe try to install this one via file manager.
Make sure to backup your version of the app and all your projects.

**Comment by spck-io** [comment]
https://drive.google.com/file/d/1JIcG00C9vrJU8A9Zh3h9x76YiANdpZQh/view?usp=sharing

I created a special version of the APK supporting Android 6, but only Chrome 55+
Please let me know if it works for you, please do not upgrade to this version if you are not on Android 6, as I'm not sure if files will be carried over. Note that if it prompts for an uninstall, please do not do so without backup of your projects.

**Comment by Doublepicebs** [comment]
The APK doesn't get installed
" × app not installed"

**Comment by Proxtx** [comment]
Sometimes you just have to restart your device

**Comment by Proxtx** [comment]
But honestly I don't think it will work

**Comment by Doublepicebs** [comment]
Restarting the phone is when the app refuses to open, but it refuses to be installed. I think it won't work either, however, I think the PWA is a good solution for this, don't you think?

**Comment by Proxtx** [comment]
Trust me some times it works...

PWA has some disadvantages
- no console
- can't open files from device
- older version of the editor
- projects may get deleted (indexed db)

**Comment by spck-io** [comment]
I have decided to rollback Android support to 6.0. Please be patient as I figure out the best way to do this.

**Comment by Doublepicebs** [comment]
I uploaded all of my important projects to github, then deleted the app, and then installed the APK, it works, and i will tell you if I find any problems here

**Comment by Doublepicebs** [comment]
@spck-io 
Status when running the latest version on Android 6.
--------
Creating projects ✓
Deleting projects ✓
Console ✓
Open in browser ✓
Basic features ✓
Git ✓
Open external files X (never worked before on Android 6.0 due to the `file://` thing)

Disadvantages:
• Some layout issues with the new colour picker. (With small screens)
• App seems to be a bit slower (not sure if this was the app or my phone)

I haven't seen anything that doesn't work yet.

**Comment by spck-io** [comment]
I have made a new release for the editor that supports Android 5.0+.

You should be able to find it on the play store now. Let me know if you are able to upgrade to it (you might not as you are using an “non-official” apk).

I tested this with small screens and hopefully fixed many of the issues you experienced. I also done a lot of optimization, the new syntax validation engine is using typescript 3.x which is probably a lot slower than the jsHint library used by ace editor. I have added a debounce to syntax validation of 700ms, let me know if that makes things a bit faster. I also made the drawer respect the no animation option in the settings, so if that feels a bit laggy you can disable it. The color picker is also moved to the keyboard area for css.
