### ISSUE TITLE
Index.html not linking with Style.css

### ISSUE THREAD

**Issue by Nik401** [spckio/spck-issues#129]
New bugs here, we can't see the style.css changes in the preview section.
I tried it many times but nothing happens, please fix this bugs.

**Comment by Proxtx** [comment]
Works for me. Maybe a bug in your code?

**Comment by Nik401** [comment]
Hi sir,
For example, I give you this simple code.
Can you tell me where is the bug?

**Comment by Proxtx** [comment]
https://github.com/Proxtx/uploads/blob/master/spck.mp4

**Comment by Proxtx** [comment]
Maybe you css file is in a subfolder 
` <link rel="stylesheet" href="[subfolder]/style.css">`

**Comment by Nik401** [comment]
Sorry sir,
Please don't mind that I tried in other apps and it did work!

**Comment by Nik401** [comment]
Although, I added [subfolder] but it doesn't work till now!
In other apps it does work.

**Comment by Proxtx** [comment]
Send me your code

**Comment by Nik401** [comment]
Style.css
<https://drive.google.com/file/d/1oXPdDRz1R6s2Tx6bX1qKfCg1xr47-6bG/view?usp=drivesdk>

  Index.html
<https://drive.google.com/file/d/1oVnek0816FSDI8AXm_r73vZApVEDEwzS/view?usp=drivesdk>
Hi sir, please see this.
And the next problem is I can't see any images in in-app-preview option but
photo does show in browser. Please solve this issue also!
Thank you in advance...

**Comment by Proxtx** [comment]
Sorry but I'm not allowed to see your files please enable link sharing in Google drive

**Comment by Nik401** [comment]
I did it, now please see my problem.
(Btw, the photo wasn't showing in in-app-preview solved now.)
So please fix my first issue which is css doesn't work in html only!
Many many thanks...

**Comment by Proxtx** [comment]
`<link rel="stylesheet" href="Style.css">`
Your filename was "Style.css"
But you wrote "style.css" <- lower case "S"

https://github.com/Proxtx/uploads/blob/master/Archive.zip

**Comment by Nik401** [comment]
Wow..
You are really genious sir.. 😄
Let me try...

**Comment by Nik401** [comment]
Thank you sir, now it's working... 😃

This app is looks like vs code.
Great app..
Only few things I'm facing problem with!

1) No Header Tab (sliding tab is annoying)
2) Putting Color with long press on screen is very annoying, it would be
better if you add specific button for adding color.
3) It would be better if you add specific icons for specific language for
the tabs, now it looks like a simple folder not like a programming language.
4) Syntax Error option doesn't work at all, if I don't use closing tags, it
doesn't say anything!

Please consider these.
Thank you in advance... 💌

**Comment by Proxtx** [comment]
@spck-io ^^

**Comment by Nik401** [comment]
can you tell me where is the comment snipppet?
I mean how to add comment? control+/ doesn't work!

**Comment by spck-io** [comment]
Thanks @Proxtx 

I will work on all these suggestions. With regards to the closing tag though, I don’t see any code editors implement this feature. VSCode does not implement HTML validation at all. I suspect the HTML specification allows for any kind of badly formed HTML to be considered valid.
