### ISSUE TITLE
Where to find project files and codes in Android

### ISSUE THREAD

**Issue by hamedabdollahi** [spckio/spck-issues#13]
1) I can't find the project codes in android, how can i access the project files and codes stored on android device?

**Comment by rjt-rockx** [comment]
Just following up on this, it would be really helpful if Spck could access and edit local files stored on the device storage or SD card. Termux lets you run things like Node.js and Python on Android, and Spck's editing capabilities would be super useful when combined with Termux. 
It might take quite a lot of work to implement it, but given that Spck has the `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` permissions, would it be possible to do so? @spck-io @zebzhao

**Comment by spck-io** [comment]
Refer to #42
