### ISSUE TITLE
Auto word delete and change

### ISSUE THREAD

**Issue by iabx** [spckio/spck-issues#130]
If I type some word and after deleting word store and automatic change if I type othe word

**Comment by spck-io** [comment]
I’m not sure what you mean by this. Just a guess, but there are some keyboards that do  weird composition modes, perhaps using a different keyboard might solve your issue?

**Comment by shamimurrahman19** [comment]
> I’m not sure what you mean by this. Just a guess, but there are some keyboards that do weird composition modes, perhaps using a different keyboard might solve your issue?

I had no issues before the update.
After the update, it messes up the texts inside my code whenever I press the backspace.

**Comment by sepsol** [comment]
Same here,  I'm using Samsung's keyboard. I can attach a clip of that If you want.
