### ISSUE TITLE
Backspace issue in 4.3.0

### ISSUE THREAD

**Issue by shamimurrahman19** [spckio/spck-issues#131]
> I’m not sure what you mean by this. Just a guess, but there are some keyboards that do weird composition modes, perhaps using a different keyboard might solve your issue?

I had no issues before the update.
After the update, it messes up the texts inside my code whenever I press the backspace.

_Originally posted by @shamimurrahman19 in https://github.com/spckio/spck-issues/issues/130#issuecomment-618546696_

**Comment by spck-io** [comment]
This should be fixed in 4.3.2.

**Comment by shamimurrahman19** [comment]
thanks
