### ISSUE TITLE
Layout issues with the colour picker

### ISSUE THREAD

**Issue by Doublepicebs** [spckio/spck-issues#132]
![Screenshot_20200423-230701](https://user-images.githubusercontent.com/51971241/80222980-f043da00-8647-11ea-981a-e6ddd7d90c47.png)
![Screenshot_20200423-230616](https://user-images.githubusercontent.com/51971241/80222994-f639bb00-8647-11ea-8eb8-167565305326.png)

**Comment by spck-io** [comment]
Closing this as color picker was moved to the keyboard section as of 4.3.2. Thanks for the bug report.
