### ISSUE TITLE
Android 10's navigation bar should be black while using a dark theme for the app — currently it's always white

### ISSUE THREAD

**Issue by sepsol** [spckio/spck-issues#133]
![Screenshot_20200425-125623_Spck Editor](https://user-images.githubusercontent.com/47871887/80275213-62133680-86cf-11ea-929b-b3bdea5ba11b.jpg)

**Comment by spck-io** [comment]
I’m not able to replicate this issue on emulators. What device are you using? Did the latest update help? I switched the app to dark theme in 4.3.2.

**Comment by sepsol** [comment]
I'm using Samsung Galaxy S9 and this screenshot was taken on Spck v4.3.0.
I now updated to v4.3.2 and the issue still persists.
