### ISSUE TITLE
UNSAVED FILE

### ISSUE THREAD

**Issue by Mathdel404** [spckio/spck-issues#138]
I was working on a page using spck editor, I created a new file which has cost me my whole page

**Comment by spck-io** [comment]
Can you please provide more details?

**Comment by Mathdel404** [comment]
I was told the spck saves file automatically, unfortunately I thought it would be in my Device but I can't find it either on my device or the app.

**Comment by Proxtx** [comment]
To access the project files of Spck you have to export your project.
If you have superuser rights you can also go to `/data/data/io.spck`.

If you opened the file with a fileexplorer the editor will save the file automatically. Sometimes the editor don't has the rights to edit a file. For example when you opened a file from an FTP connection. 
By the way I would really like to see an build in fileexplorer (in the editor). @spck-io

**Comment by ajay4uu** [comment]
Its not able to read the .css file in my internal storage . I tried changing the path of image but attributes like "img src" is not reading this. Please help me where to save the jpg files and css files.
