### ISSUE TITLE
Code in Local Files

### ISSUE THREAD

**Issue by Gautamkumardev** [spckio/spck-issues#152]
Add ability to edit and cide in local files.

**Comment by Proxtx** [comment]
You can! Just install a file manager click on your file and then click "open with"
Now you should see a list of apps click on Spck editor

**Comment by prajwalch** [comment]
Spck not showing on list.

**Comment by Proxtx** [comment]
https://github.com/Proxtx/uploads/blob/master/YouCut_20200523_195127364.mp4

FX fileexplorer

**Comment by prajwalch** [comment]
Also how to merge new branch into master?

**Comment by Gautamkumardev** [comment]
i can use filemanger to only edit files but cannot save it.
