### ISSUE TITLE
Discord 

### ISSUE THREAD

**Issue by Proxtx** [spckio/spck-issues#157]
At the moment the Discord server is very empty because only a few people look at old Issues or don't even looked at the issues page. Maybe you (@spck-io) could add a little Discord icon at the bottom of the settings page? I recently checked all permissions and I think the Discord Server is ready for some more members.

**Comment by spck-io** [comment]
Thanks for the suggestion!

**Comment by Proxtx** [comment]
Hey @spck-io we would love to hear from you at the discord server.
