### ISSUE TITLE
Add C#

### ISSUE THREAD

**Issue by DrakeUser123** [spckio/spck-issues#159]
I dont know if csharp is already in the app, let me know if its in it, seriously if it is there, tell me how can i use it or apply it. I know its sound stupid but im just curius :D

I know how to use Csharp but how do you apply it to the console, sorry im still new to web dev ... :l

**Comment by spck-io** [comment]
C# requires a .NET core environment. Sadly, I do not know how to integrate .NET core into an Android app. Closing this as there is nothing I can do. Sorry.
