### ISSUE TITLE
Add rtl language support to application enviroment

### ISSUE THREAD

**Issue by abolfazleslami1990** [spckio/spck-issues#160]
Hi i know you already support rtl languages but seems to be a problem with language direction
In rtl languages if you write English word, it won't change the direction to ltr
But in your editor everything is opposite
Like this
'''
سلام خوبی hi there خوبی
'''
See! I couldn't write litterally in right to left direction because of english word appears in my text and this is the embarrassing problem
Please fix it thanks

**Comment by Doublepicebs** [comment]
I highly recommend this @spck-io

**Comment by spck-io** [comment]
Could you explain what you expect to see? What android keyboard are you using? There’s something in Android called a BiDi text engine (bidirectional text layout) not sure if that might be the source of your problem.

Are you expecting to see “there hi?”
