### ISSUE TITLE
SPCK does not open files in TypeScript

### ISSUE THREAD

**Issue by t-heu** [spckio/spck-issues#163]
Bug, Hello, in the past SPCK opened files in TypeScript, now it’s been months since it opened.
![Screenshot_20200605-094551](https://user-images.githubusercontent.com/25287877/83878013-d818ad80-a711-11ea-8b94-8e6167408c38.png)

**Comment by Proxtx** [comment]
We solved this issue in the Discord. There will be an update soon witch will fix this. But there is an workaround for now: 
1. Download FX fileexplorer
2. Watch this video:
https://github.com/Proxtx/uploads/blob/master/20200605_150405.mp4
