### ISSUE TITLE
Can't add Background-image

### ISSUE THREAD

**Issue by byrz-ell** [spckio/spck-issues#164]
Can't add background-image in css with bootstrap.

**Comment by ternengesam** [comment]
I tried adding backroung image but i could not thinking i was doing it wrong
but now i know its a general bug. I am glad this issue was brought up

**Comment by spck-io** [comment]
URL links must be relative. The root URL refers to the **projects directory** (This means you can also access files across projects if you wanted to I.e: “/Flappy Learning/index.html” or “/Project 1/file.html”) could you please reference the image file relative to the HTML file? Or use an absolute path that includes the project name. Please send your project folder structure if you need further help.

**Comment by Proxtx** [comment]
https://github.com/Proxtx/uploads/blob/master/Htest.zip
Test project by me ... Works fine
Maybe send your project files?
