### ISSUE TITLE
Application icon blurry

### ISSUE THREAD

**Issue by nathaneltitane** [spckio/spck-issues#165]
Beautiful app, everything is great so far as I'm making the switch from a normal desktop to my phone using dex.

Couldn't help but notice that the app icon appears blurry in both launchers and may need a resolution upgrade.

Thanks

see attached:

![Screenshot_20200605-113449_Samsung Internet](https://user-images.githubusercontent.com/5674757/83895373-9ba07e00-a720-11ea-8b65-e69a66442536.jpg)

**Comment by spck-io** [comment]
Thanks, will look into this. I think its a problem with downscaling the icon.

**Comment by lucazpf** [comment]
> Beautiful app, everything is great so far as I'm making the switch from a normal desktop to my phone using dex.
> 
> Couldn't help but notice that the app icon appears blurry in both launchers and may need a resolution upgrade.
> 
> Thanks
> 
> see attached:
> 
> ![Screenshot_20200605-113449_Samsung Internet](https://user-images.githubusercontent.com/5674757/83895373-9ba07e00-a720-11ea-8b65-e69a66442536.jpg)

I'm using Spck with my tab S7 but when I switch to DeX I'm not able to have the app in fullscreen mode. Do You have  Spck fullscreen in DeX?

**Comment by nathaneltitane** [comment]
> > Beautiful app, everything is great so far as I'm making the switch from a normal desktop to my phone using dex.
> > Couldn't help but notice that the app icon appears blurry in both launchers and may need a resolution upgrade.
> > Thanks
> > see attached:
> > ![Screenshot_20200605-113449_Samsung Internet](https://user-images.githubusercontent.com/5674757/83895373-9ba07e00-a720-11ea-8b65-e69a66442536.jpg)
> 
> I'm using Spck with my tab S7 but when I switch to DeX I'm not able to have the app in fullscreen mode. Do You have Spck fullscreen in DeX?

your device is up to date? I'm running my dex on a note 10+ with all the latest updates: your device may not have the most recent dex version this not supporting the same features?

mine runs full screen without any issues

**Comment by lucazpf** [comment]
The tablet runs on the latest update. This is how I see the app![Screenshot_20201005-222939_Spck Editor.jpg](https://user-images.githubusercontent.com/1643759/95128988-8e40e200-075a-11eb-9938-ea06093679fa.jpg)

**Comment by nathaneltitane** [comment]
so change the settings within the app to get it to function properly - also enable dex labs options to force resize apps
