### ISSUE TITLE
Enhancement: code folding

### ISSUE THREAD

**Issue by nathaneltitane** [spckio/spck-issues#166]
Is there any possibility to add code folding to the app?

**Comment by Proxtx** [comment]
You can fold the code.
Just click on the line number next to an if-block or a function.

**Comment by nathaneltitane** [comment]
Excellent, thank you!

**Comment by nathaneltitane** [comment]
Hello again @Proxtx ,

I've tested your suggestion and in my case (writing BASH scripts) the folding is only recognized on functions.

I do not get the fold arrow next to if or case statements unfortunately.

Can that be adressed?

**Comment by Proxtx** [comment]
@spck-io ^^

**Comment by spck-io** [comment]
Currently, ace editor does not support folding in bash mode. Consider making a pull request to ace editor to have more advance support for bash editing.
