### ISSUE TITLE
Enhancement: detect language/type using header

### ISSUE THREAD

**Issue by nathaneltitane** [spckio/spck-issues#167]
Hello,

Just noticed that unless an extension is present on any given file, the syntax highlight does not function.

Could you manage enhancing the feature to detect shebangs and headers and apply the highlights accordingly?

Thanks!

**Comment by spck-io** [comment]
What specific examples of shebang line do you want in the editor? The shebang line is used mostly by bash and not usually for determining file type, it is also very specific to Linux. Could you let me know what the use case is, so I do not break compatibility with other features that rely on the file extension?

**Comment by nathaneltitane** [comment]
Bash , shell or python
