### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sajid1500** [spckio/spck-issues#168]
I can't scroll the console upwards. It always gets dragged all the way to the bottom.

**Comment by Proxtx** [comment]
I think this happens because the console automatically scrolls to the bottom when something new gets logged.
Try to only log something when you press a button.

**Comment by sajid1500** [comment]
No, that's now the case. For example, if I log 10 different things, I can't
scroll upwards. I mean I can but after a second it instantly gets to the
bottom. It gets pushed downwards. By default it always get to the bottom
when I run the project. So, I literally have like a second to see my log.
Please help.

**Comment by Proxtx** [comment]
I tried it by my self and it worked fine...
Could you please send a screen record?
Or the project files?
Wich console are you using?

**Comment by sajid1500** [comment]
The files are the default ones you provided. Only I'm changing js file by
logging some things. I'm using Eruda console. Took time to respond because
I was downloading screen recorder and video compresser. Please help.

**Comment by Proxtx** [comment]
I can't replicate the issue maybe try using the other console!
To upload big files just create an GitHub project and upload you files / videos there and share the link

**Comment by sajid1500** [comment]
Thanks for the tip. I shall try reinstalling the app and changing console.
Hopefully it will get fixed. And sorry for sending email multiple times. I
thought it didn't get send.

**Comment by Proxtx** [comment]
Wait don't uninstall it! It won't fix it! I'm sure!

**Comment by Proxtx** [comment]
Your projects will be gone!!

**Comment by Proxtx** [comment]
Please send me the screen record

**Comment by sajid1500** [comment]
Here is the video -
https://github.com/Sajid1500/spckvideo/blob/master/20200606_012232_s01.mp4.
Tried with the legacy console. Works perfectly but the Eruda doesn't😔. I
tried reinstalling. It's the same. No changes.

**Comment by Proxtx** [comment]
Yes you are right this is a bug. But it works for me..
So here are my settings from the eruda console. Apply these and check I the bug still appears...
1=on
0=off
Async Rendering: 1
Enable JavaScript execution: 1
Catch Global Errors: 1
Override Console: 1
Auto display if errors...: 0
Display extra information: 1
Display unenumerable Pro..: 1
Access getter...: 0
Lazy evaluation: 1

**Comment by sajid1500** [comment]
Tried still not working. Maybe the problem is with my tablet. I shall try
it on my phone
