### ISSUE TITLE
Highly needed feature

### ISSUE THREAD

**Issue by sajid1500** [spckio/spck-issues#169]
Coding projects including html,css and js on it is just ez but projects including node don't work. So, I'm creating node projects in termux as it has support for node. I'm using this editor since January now. The only feature which I felt the dire need of is to edit files from device and save it. Almost all android editors have this feature. If you want do it in the pro version spck code editor but please do it. It's a humble request.

**Comment by Proxtx** [comment]
This will come in the next major update
"External storage projects is on the roadmap for the next major release"

**Comment by sajid1500** [comment]
If your doing it please do it using saf or the storage access framework.
So, we can access from anywhere in our device. I was waiting for this
feature for a long time.

Thank you,
Sajid

**Comment by Proxtx** [comment]
@spck-io ^^

**Comment by Sajid1500** [comment]
The files are the default ones you provided. Only I'm changing js file by
logging some things. I'm using Eruda console. Took time to respond because
I was downloading screen recorder and video compresser. Please help.

**Comment by sajid1500** [comment]
Can you tell me when is the next major update coming?
