### ISSUE TITLE
Editor is missing handle.

### ISSUE THREAD

**Issue by Kleenox** [spckio/spck-issues#17]
The application not having a handle (or caret or cursor, whatever you want to call it) that allows you to move the cursor by dragging makes it extremely frustrating to use compared to most other editors on mobile. It's the thing stopping me from using this app. For examples of this you can check any of the following editors: awd, anWriter, Quoda or Dcoder.

Just to make sure you know what I'm talking about, I'm talking about this guy right here:

![image](https://user-images.githubusercontent.com/7082077/50362107-b13ed980-0566-11e9-9ab8-7e7a87c94ece.png)

Best regards

**Comment by spck-io** [comment]
Thanks, will work on it next. The new Git features have kept me busy for the last little while.

**Comment by spck-io** [comment]
Added as of version 0.5.2.
