### ISSUE TITLE
Problem with bluetooth keyboard

### ISSUE THREAD

**Issue by YeongRoYun** [spckio/spck-issues#172]
When I used bluetooth keyboard, I met a big problem.
After using virtual keyboard, I couldn't use bluetooth keyboard anymore.
It doesn't work in this app..

**Comment by spck-io** [comment]
Can you give details on what's happening? Which blue-tooth keyboard are you using and what device/Android version are you having a problem? Thanks.

**Comment by s-sullentrop** [comment]
Not the person above, but as i'm writing this I am using my bluetooth keyboard with no issues along with using it in other apps. My issue with Spck is that the touch screen keyboard pops up when i'm about to start typing, then as soon as I begin typing with the bluetooth keyboard it gets the first input from the keyboard into the code, but stops after that initial key press. My keyboard is the Logitech K480 Bluetooth Keyboard. Thank you for any input you may have!

**Comment by Technirene** [comment]
Same Problem here, on the Matepad Pro with the magic keyboard. Have tried almost every setting, no solution found so far.

**Comment by Proxtx** [comment]
Hi try changing your keyboard app (Gboard). Sometimes it helps!

**Comment by Technirene** [comment]
Problem solved! What a solution. 

Thank you, you mighty wizzard (you have to be one, or I am even dumber than I feeling right now).

**Comment by spck-io** [comment]
There is now an option in Settings that link to the Physical keyboard setting in Android. You can disable Virtual keyboard when using hardware keyboard from there.
