### ISSUE TITLE
Vue code highlight 

### ISSUE THREAD

**Issue by bukitoka** [spckio/spck-issues#180]
Please support vue code highlight

Step to reproduce :
- just clone your Vue project and open it 

Screenshot : 
![Screenshot_20200613_221721](https://user-images.githubusercontent.com/47457477/84571096-d612b680-adc3-11ea-8524-71dd008a9448.jpg)

**Comment by Tobi-Odu77** [comment]
How do I solve this problem because this is also happening to me.

**Comment by spck-io** [comment]
Thanks, I will default .vue files to use html mode in the next release.

**Comment by bukitoka** [comment]
Thanks can't wait to try it 🔥
