### ISSUE TITLE
Cloning a remote repo or pulling from one results in a TypeError

### ISSUE THREAD

**Issue by aydencook03** [spckio/spck-issues#182]
![Screenshot_20200620-162127_Spck Editor](https://user-images.githubusercontent.com/63018272/85210944-70b64c80-b312-11ea-8749-86a5432175b4.jpg)

**Comment by scweiser** [comment]
I'm also experiencing this.  My repo is a mix of many different file types.  Could it be an issue with one of the file types in the repository?

**Comment by wagnered** [comment]
Same here plus continued retry caused app to crash.

edit:  try it with https://github.com/ampache/ampache.git
