### ISSUE TITLE
bug maybe

### ISSUE THREAD

**Issue by sajid1500** [spckio/spck-issues#187]
I'm not sure if it's a bug but whenever I get out of spck code editor using home button and then get inside of the app, it restarts. It also restarts when I switch from multi screen to full and vice-versa. I use a tablet and I switch between multi screen and full screen mode a lot. Sometimes, the app gets stucked when it restarts. Then I've to remove the app from the background and then start the app again. It's frustrating. Can't you change this so that  it doesn't refresh every time?

**Comment by spck-io** [comment]
The app does not currently use largeHeap setting in Android. The restart of the app is determined by AndroidOS and if there is enough memory, it will shutdown apps. Try disabling Autocomplete to save some memory to see if that helps.

Or maybe try shutting down other apps that are consuming too much phone memory.

**Comment by sajid1500** [comment]
Thank you for your response
