### ISSUE TITLE
Emmet not working with Physical keyboard

### ISSUE THREAD

**Issue by Kuameh** [spckio/spck-issues#188]
Some updates back I was able to use Emmet with the tab key but can't anymore.
If i do `div` tab I the desired results. But if I do something like a `div.class>p` it only respond to the last element. 
[Screen_Record.zip](https://github.com/spckio/spck-issues/files/4847202/Screen_Record.zip)

**Comment by spck-io** [comment]
The Emmet shortcuts previously conflicted with other shortcuts in the past. The proper Emmet shortcut for expanding is Ctrl-Alt-E. Sorry for the inconvenience. There is a Shortcut lookup in the Settings tab (just search for Emmet).

**Comment by Kuameh** [comment]
Thanks for the info love the app.
