### ISSUE TITLE
Git Repo does not work

### ISSUE THREAD

**Issue by DMB81** [spckio/spck-issues#20]
I always get the message
Mount Error
Error Timeout Requesting ...

**Comment by secrethash** [comment]
When I push I get Invalid date time format error with HTTP Response Code: 422 ![](https://i.imgur.com/5pTgJ2O.png)

**Comment by spck-io** [comment]
Please use the latest “Clone Git” feature, this is built on top of the more stable isomorphic-git library. I am aware the Mount Github which is using Github APIs is quite buggy.
