### ISSUE TITLE
Why u guys removed the terminal 

### ISSUE THREAD

**Issue by AriaFantom** [spckio/spck-issues#205]
Add the terminal thing or i will delete your app

**Comment by Yonle** [comment]
> i will delete your app
# Nobody cares about that. 
C'mon. Texting that just for attention is fuq1ng **stupid** you know.

**Comment by AriaFantom** [comment]
No need that time i don't have pc not no need

**Comment by Yonle** [comment]
You may also try [Termux](https://termux.org) for running python / nodejs code.

**Comment by Phemjay1** [comment]
Please how do I start running terminal on spck because I tried to run it but it's telling me my input not found?
