### ISSUE TITLE
Python & Javascript librarys

### ISSUE THREAD

**Issue by alimkoca** [spckio/spck-issues#215]
I want npm, pip package managers and terminal in Spck Code Editor

**Comment by Proxtx** [comment]
All of these will be added in the pro version

PARDUS <notifications@github.com> schrieb am Mi., 2. Sept. 2020, 10:26:

**Comment by lonely-v3n1x** [comment]
When will the pro version be available

**Comment by spck-io** [comment]
There is a Pyodide javascript library which emulates Python in Browser that you can use to test simple Python code. I looked into integrating Python 3.9 into the editor but found that the Python library relies on reading from the /system folder which is no longer allowed on Android. Additionally, the readline functionality from C++ seems to be broken on Android, as it keeps returning EOF and fixing the readline dependency is beyond my expertise in C++.

**Comment by spck-io** [comment]
I'm not sure where to start begin debugging for the following issue. If anyone is an expert on C++, please let me know.
<img width="337" alt="Screen Shot 2022-03-26 at 5 28 23 PM" src="https://user-images.githubusercontent.com/42258400/160257781-015ea5e2-c938-4536-98df-427cede669c7.png">
