### ISSUE TITLE
Browser

### ISSUE THREAD

**Issue by JackSuede** [spckio/spck-issues#217]
The browser has issues with playing sounds. After "interacting with the document", as chrome puts it, the first sound plays but other triggered sounds produce a cryptic error message on the current console, but on the old console it says that interaction is required to play the sound. If I tap rapidly, all sounds play.

on Chrome, I only have to interact with the document once and all triggered sounds play.

A great quick fix is to let us designate the external browser as the default, because for now the test browser is just an intermediate step to get to Chrome.

Eventually it'd be nice if we only had to interact with the document once and all sounds will play on the test browser. Great app. 5 stars * * * * *

**Comment by Proxtx** [comment]
I don't think this will be an easy fix because spck uses your system webview.
