### ISSUE TITLE
PLEASE READ

### ISSUE THREAD

**Issue by TheReyzer** [spckio/spck-issues#22]
Hi, I loved your editor, but I'd like to say two things first. There is a bug that when you delete a line of code it adds again, I found this bug only in CSS but I do not know if in other places there are. And second. I could save the project to a folder on the Android device to edit the files in the editor and not have to export in .ZIP to see how it got in the browser, you know? The app create a folder in the memory of the phone for all the projects created in the app stay there hence it is not necessary to be exporting in .ZIP every time you want to see the code outside the app, please at least consider my request, please.

**Comment by spck-io** [comment]
Editing single external files is now possible in android app version 3.0.1. Writing to internal storage is also possible now.
