### ISSUE TITLE
Feature Request: Tabbed view for files

### ISSUE THREAD

**Issue by nikhilmwarrier** [spckio/spck-issues#221]
I've been using spck.io (app) as my go-to editor on my android tablet with a physical keyboard. I just love this awesome software. Everything is awesome, from the UI to Emmet shortcuts and everything else in between.

 Except for one thing: Tab view.
I would like to see my open files up top in a tabbed manner, like VS Code or pretty much every other code editor. I suppose you want to optimize for touch input, etc. Even then, you guys ought to add a toggle to turn on tabbed mode. Oh, and also, a keyboard shortcut to navigate through them, too. Hope you guys can make it.

**Comment by spck-io** [comment]
Thanks for the suggestion. This is added now.
