### ISSUE TITLE
Requesting for a terminal future

### ISSUE THREAD

**Issue by ternengesam** [spckio/spck-issues#226]
Adding a terminal to the editor will be a good upgrade to the app thanks for the good work ...
And also the terminal needs some touching it's misbehaving it's not responding fast it's delays most times keep up the good word...

**Comment by Proxtx** [comment]
(Patch notes 5.0.4)


"Special Annoucement
A new project is in the works at the moment, "Spck Editor Pro" is going to be a separate premium app released for Android. More details will be available in the next update, ETA expected to be mid-September.

Application will be 50-80 MB in download size
App will be able to run NodeJS (likely npm, react, vue, Angular, babel, typescript, sass, less, etc.)"
