### ISSUE TITLE
Action bar is not visible

### ISSUE THREAD

**Issue by apilipa** [spckio/spck-issues#228]
![Screenshot_20201013-061734_Spck Editor](https://user-images.githubusercontent.com/68003832/95801357-e4de8b00-0d1b-11eb-8939-e3ce91de4f3e.jpg)

**Comment by Proxtx** [comment]
On the discord-server someone experienced the same bug. How many projects do you have? If you want to open the side menu just swipe from the left edge right.

**Comment by apilipa** [comment]
I had two projects, slide menu works as well as the run button, but none of then are visible

**Comment by Proxtx** [comment]
Ok then backup all your projects and reinstall the app.

**Comment by spck-io** [comment]
If you are still having this issue, please let me know. I will try to get to the bottom of this.
