### ISSUE TITLE
critical: global find/replace mangles output

### ISSUE THREAD

**Issue by nathaneltitane** [spckio/spck-issues#231]
I've used the global find/replace option on a project iteratively to fill in missing prackets and braces to only find out afterwards that it had mangles the outpur by misunderstanding the expression or interpreting it while i had not turned the regular expression filter on.

One of many mangled substitutions as an example:
find: $PROOT_DIRECTORY
replace with: ${PROOT DIRECTORY} or "${PROOT_DIRECTORY}'

result: ${PROOT_DIRECTOR}Y

$HOME >> ${HOME}ME

and more...

please fix?

EDIT:

Line taken from find/replace output: you can see how in the end it murders the replacement into something unrecognizable.

command+=" PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:${PREFIX}/bi${PREFIX}IX/sbin"

see image below:

![Screenshot_20201014-232632_Spck Editor](https://user-images.githubusercontent.com/5674757/96073588-baecac00-0e74-11eb-978b-7a1d4c0059d4.jpg)

**Comment by nathaneltitane** [comment]
still an issue and regex does not work properly on pro version either.... ::BUMP::

**Comment by nathaneltitane** [comment]
replaces with litteral string even when regex is enabled!

See picture
![Screenshot_20210824-101258_Spck Pro](https://user-images.githubusercontent.com/5674757/130632557-80d708ce-799e-432e-bf56-f3a9a729aa30.png)

**Comment by nathaneltitane** [comment]
@spck-io can this be adressed?

**Comment by spck-io** [comment]
I believe most of these issues should be fixed in 6.0.6. Please reopen if there is still an issue.
