### ISSUE TITLE
android autocomplete random suggestions

### ISSUE THREAD

**Issue by nathaneltitane** [spckio/spck-issues#232]
synatx verification is on and often times the application with suggest android standard input such as User name or other saved global entries that google/android uses to autofill prompts and fields on websites and other applications.

Is there a way to prevent this or could you implement a more strict 'project content only' suggestion mechanism?

**Comment by spck-io** [comment]
The suggestion mechanism is controlled by the Android Keyboard application (which differs for each Keyboard you download), this is outside of the app's control. You can change IME Mode in Settings to Basic to "hint" to the keyboard that no suggestions are required, but it's up to the keyboard if it wants to respect this flag or not.
