### ISSUE TITLE
spck.io no syntax highlighting/recognition

### ISSUE THREAD

**Issue by nathaneltitane** [spckio/spck-issues#233]
self explanantory title - see attached.

![image](https://user-images.githubusercontent.com/5674757/96039322-76422000-0e36-11eb-85ff-443d9becfd18.png)

**Comment by daynakic** [comment]
Spck is basically a web development IDE
It supports 
Advance autocompletion & syntax highlighting Support for:
JavaScript,TypeScript,HTML,CSS,SCSS,LESS
Basic Autocompletion & syntax highlighting for:
Python,Java,C,Ruby,Perl,Scala,More..
As mentioned on their [Documentation](https://spckio.github.io/spck-documentation/editor-settings.html#appearance)  site.
So I think it doesn't support bash highlighting on the web version.

Note: You are using the web version. The android version supports syntax highlighting for bash as mentioned in the app description. So if possible then try switching to android version or use other application.

Hope this helped.

**Comment by Proxtx** [comment]
Or use an Android emulator

**Comment by daynakic** [comment]
They consist built-in editor specialised for shell like nano or vim
Termux is one of the best example of emulators you can try it.
It seems you are on a computer try on your terminal

**Comment by Proxtx** [comment]
Oh wait ... Delete your file and create it again but add ".sh" for syntax highlighting

**Comment by daynakic** [comment]
Oh yes no need to delete just rename

**Comment by Proxtx** [comment]
If you just rename it you have to restart spck

**Comment by daynakic** [comment]
No reloading the browser will work well.
Did you meant it too?

**Comment by Proxtx** [comment]
Well reloading the browser IS restarting Spck
