### ISSUE TITLE
Custom project boilerplates

### ISSUE THREAD

**Issue by talentlessguy** [spckio/spck-issues#24]
Hey, everyone! I really love the app and use it for writing simple web apps when not at home. For example, I learn p5.js. But I don't have a preset for that, and I have to manually setup p5.js.

# How to solve the problem

Add an ability to upload custom boilerplates, for example a repository with sample files (index.html, .gitignore). I don't mean fetch repo or import ZIP cos it is for in development projects. I mean starter packs as React starter (that is already in the app) for example.

# How it can be implemented

Click on "+", then "New Project". Then we can make a button "New Preset". And paste GitHub URL there.

# If this is difficult to create, here are my ideas about presets

* p5.js (+p5.dom.js +p5.sound.js)
* Polymer
* Preact
* Hyperapp

**Comment by spck-io** [comment]
Thank you so much for the suggestion. I really like the idea! I don’t want to promise too much as I am finding it really hard to fix problems with git, and zip export problems people are reporting. Sorry I haven’t been active recently, but integrating isomorphic git into the editor as well as my full time job really ate up my free time.

**Comment by talentlessguy** [comment]
Ok, I hope you have time on this feature. I can send you some design mockups for the feature if you want.
