### ISSUE TITLE
Access termux storage

### ISSUE THREAD

**Issue by holiq** [spckio/spck-issues#244]
I create project on termux directory because need node_modules, how i access my project in termux directory ??

**Comment by Proxtx** [comment]
Wait for spck pro

**Comment by ghost** [comment]
But hey, you can use `termux-setup-storage` (make sure your spck project is external) and then move your termux node_modules directionary to `~/storage/emulated/0/Android/data/spck.io/files/PROJECT_NAME/node_modules`. Here is a script-
```
termux-setup-storage
mv node_modules ~/storage/emulated/0/Android/data/spck.io/files/PROJECT_NAME/node_modules
```
I personally don't do that because I usually don't need to.

**Comment by holiq** [comment]
> But hey, you can use `termux-setup-storage` (make sure your spck project is external) and then move your termux node_modules directionary to `~/storage/emulated/0/Android/data/spck.io/files/PROJECT_NAME/node_modules`. Here is a script-
> 
> ```
> termux-setup-storage
> mv node_modules ~/storage/emulated/0/Android/data/spck.io/files/PROJECT_NAME/node_modules
> ```
> 
> I personally don't do that because I usually don't need to.

node_module can't move to internal because permission in termux directory with internal not same, I've tried it 
But thanks for your answer

**Comment by ghost** [comment]
If it didn't work try `io.spck` instead of `spck.io`
