### ISSUE TITLE
Can not create project

### ISSUE THREAD

**Issue by Asanatsa** [spckio/spck-issues#246]
Can not create project.
Phone Mode:Redmi note4
System:Miui11(Android7.0)

**Comment by Proxtx** [comment]
Do you see an error or what is exactly happening? Check out this page: http://faq.ni-si.ddnss.de/faq/?faq=CreateProject

**Comment by Asanatsa** [comment]
帮助无用，截取日志内容：
`[下午7:38:21] [projects] Updated project list

[下午7:38:21] QuotaExceededError

[下午7:37:28] [projects] Updated project list

[下午7:37:28] [update]: @blank.js

[下午7:37:01] Starting language server`

**Comment by Asanatsa** [comment]
> Do you see an error or what is exactly happening? Check out this page: http://faq.ni-si.ddnss.de/faq/?faq=CreateProject

The problem was solved.The cause is webview's version is too old.(Please forgive the funny English😂,because I'm a Chinese)
