### ISSUE TITLE
Logins

### ISSUE THREAD

**Issue by MrHenry1** [spckio/spck-issues#250]
I'm trying login in the app and none kind of login is working, is giving errors

**Comment by MrHenry1** [comment]
And then I can't use somethings, just like: Run app at Pro Projects, use Terminal

**Comment by MrHenry1** [comment]
![20201130_070838](https://user-images.githubusercontent.com/52577797/100596708-3b5b5500-32db-11eb-84de-839f9ed3951f.jpg)
![20201130_070825](https://user-images.githubusercontent.com/52577797/100596710-3bf3eb80-32db-11eb-8643-01cedba9544a.jpg)
![20201130_070752](https://user-images.githubusercontent.com/52577797/100596711-3c8c8200-32db-11eb-9066-1232b87c5d8c.jpg)

**Comment by spck-io** [comment]
Issue with login should be fixed in the latest update. There was an issue with the certificates used on the play store version. Thanks for the bug report.
