### ISSUE TITLE
Request  

### ISSUE THREAD

**Issue by ghost** [spckio/spck-issues#252]
This request is on the pro version , More payment options should be added because the present don't favour some card types .my PayPal etc

**Comment by spck-io** [comment]
Thanks for your suggestion, but as much as I would like to avoid using Google in-app billing to avoid their 30% Google tax, it is a violation of the Play store agreement and would risk having the app removed by Google :(.

https://support.google.com/googleplay/android-developer/answer/9858738

It looks like Paypal is a supported form of payment in the US. See below:

https://support.google.com/googleplay/answer/2651410?co=GENIE.CountryCode%3DUnited+States&hl=en
