### ISSUE TITLE
Browser 

### ISSUE THREAD

**Issue by ghost** [spckio/spck-issues#256]
the spck in app preview browser is running on a static host local host:7700. webpack is running on local host:8080. Which it's can't display data rendered by  our app else we use browser.
May be you can add future that allows us to enter web address in the speck editor or change and add host.

**Comment by Proxtx** [comment]
The feature is already in the app. (Pro) 
1. Click the three dots next to the play button
2. Run settings
3. Run: URL
4. URL: http://localhost:8080

**Comment by ternengesam** [comment]
Didn't notice Thank you

**Comment by ghost** [comment]
still not working, maybe a bug if not a tutorial could help.
and pasting copied items comes duplicate
