### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by ternengesam** [spckio/spck-issues#257]
i started a new react project when i clicked the play button the terminal throw an error that i should reinstall the app. i logged out the tried logging in the i got this massage. the link point to the screenshot .

https://drive.google.com/file/d/13lyKIwVWr9cHiAuQwNFa4AXj61ZIkuiz/preview?usp=drivesdk

**Comment by spck-io** [comment]
I will investigate this issue. Thanks for reporting this issue. I think I have an idea of what is happening, I will try to implement a fix for this as soon as I can.
