### ISSUE TITLE
Preview not working with BASE tag

### ISSUE THREAD

**Issue by varogonz95** [spckio/spck-issues#26]
Hi, the built-in browser for previews does not work with views having any `<base href="">` tags
I'm not quite sure why this happens

**Comment by spck-io** [comment]
Hi, the editor serves your HTML page through a service worker under the “/run” context. So technically speaking only relative paths in index HTML would work. I believe setting a base tag with href as “/run” would work as well. I’m not a big fan that many boilerplates use the base tag as that restricts your app to only run under the root context. Unfortunately I can’t support this in the editor as the editor needs the root context to serve itself. This sort of thing might be possible if I can integrate node HD into the mobile editor, but that would require a major rewrite that won’t work in the desktop browser version.

**Comment by varogonz95** [comment]
Ok, thanks! I can work with '/run' path

Maybe the built-in browser can append user-defined for `href` paths for base tags on document load events as a hotfix 🤷‍♂️

**Comment by spck-io** [comment]
This is no longer required as files are served with a local server on android starting from version 3.0.0
