### ISSUE TITLE
Ascii characters not recognized

### ISSUE THREAD

**Issue by flodef** [spckio/spck-issues#267]
2 problems underlined, but it's maybe the same.
When testing html/JavaScript, the character € is not recognized. It displays something weird (rounded in orange) next to 1000 in the screenshot.
Also, I get an error when testing a regular expression with accentuated characters (underlined in orange).
My regular expression is : ^[A-zÀ-ú -]{0,10}

![IMG_20201213_162834](https://user-images.githubusercontent.com/9675304/102016264-4cd34100-3d60-11eb-981e-9b1809a6b04b.jpg)

**Comment by flodef** [comment]
This a really severe problem as I could not test properly, and the app is unusable. I tested it also with legacy, and in chrome browser, same problem (however, it works well directly from a mobile phone browser, without using local server).

**Comment by Proxtx** [comment]
Could you please send your project?

**Comment by flodef** [comment]
Yes, sure. Sorry, for the late reply. The project is : https://github.com/flodef/FiMS (to get the error, click on the button in the top right corner).
I finally understood the problem with the `€` character. It needed to be escaped in HTML. I used `&euro;` as an escaper and it works well this way.
Still didn't find the way to resolve the regular expression problem though.

**Comment by flodef** [comment]
I realize that all my accentuated characters are messed up (éèà and so on) which does not happen when using the mobile version of chrome. It's weird because between the local server and the distant server (with the same browser), I get different output.
Thanks a lot for checking it ;-)
