### ISSUE TITLE
How to get PRO version?

### ISSUE THREAD

**Issue by thetejasmagade** [spckio/spck-issues#268]

**Comment by subversivo58** [comment]
I would like to know too

**Comment by Proxtx** [comment]
Search for Spck Pro in the play store.... The first result. The dev account is difference BUT in reality it's the same dev.

**Comment by thetejasmagade** [comment]
Thank you ❤️❤️

**Comment by ievgeniysv** [comment]
How to get pro version on iPad? I can’t find Spck pro in App Store ((

**Comment by Proxtx** [comment]
It isn't on the AppStore because it's technically very difficult to run node js on iOS (maybe it's impossible)

**Comment by yason-20** [comment]
How would I get the pro version on Android 
Motorola??

**Comment by Proxtx** [comment]
As I sad:
Search for Spck Pro in the play store.... The first result. The dev account is difference BUT in reality it's the same dev.

**Comment by subversivo58** [comment]
> How would I get the pro version on Android
> Motorola??

I've used it in Motorola Moto G 4G (first generation) with LineAgeOs 15.1 and now use it on Moto G 6 Play Android 10 AOSP GSI

A link to the appropriate marketplaces could be welcome

https://play.google.com/store/apps/details?id=io.spck&hl=en-US

and

https://play.google.com/store/apps/details?id=io.spck.editor.node&hl=en-US
