### ISSUE TITLE
Add LAN access support

### ISSUE THREAD

**Issue by jianboy** [spckio/spck-issues#271]
spck editor is a good cross platform IDE, it will crate a web server: http://localhost:7600 

but it only can access on own phone. I want clone github project on pc (http://192.168.0.111), then edit it on mobile. such as:

```
public class LocalHttpService extends NanoHTTPD {

    /**
     * 覆写构造方法
     *
     * @param port
     */
    public LocalHttpService(int port) {
        super(port);
    }
```
instead of
```
public class LocalHttpService extends NanoHTTPD {

    /**
     * 覆写构造方法
     *
     * @param port
     */
    public LocalHttpService(int port) {
        super("localhost",port);
    }

```

**Comment by spck-io** [comment]
I'm afraid that adding this feature will be flagged by the Play Store for security issues, and/or Android virus scanners.
