### ISSUE TITLE
This is not an issue exactly.

### ISSUE THREAD

**Issue by ghost** [spckio/spck-issues#274]
Please can this app be minified a little, it's getting bigger as I use it every day and it's begging to slow down.

**Comment by Proxtx** [comment]
I bet you have projects your currently not working on... Just export them (double check if everything was exported correctly) and then delete them from spck.

**Comment by ghost** [comment]
when deleting project created internally, node_modules refuses to delete else i delete item by item in the module,

**Comment by Proxtx** [comment]
Delete the folder with your file manager

**Comment by ghost** [comment]
The internal projects don't appear in my local storage, I tried accessing with termux but the path was not found I wonder where its is actually stored. This is the path ===/data/data/io.spck.editor.node/files.
 #![Screenshot_20201230-002308](https://user-images.githubusercontent.com/75048398/103320338-3f42da00-4a35-11eb-8eff-8bd55b48da2e.png)

I use android 9 stock rom so I don't have root access, using ubuntu in termux gives me the privilege to access some folders like bin.

**Comment by ghost** [comment]
Any I at the process of this discussion I figured out a way of deleting them .
![Screenshot_20201230-003013](https://user-images.githubusercontent.com/75048398/103320612-59c98300-4a36-11eb-9fa3-28032f270d69.png)

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/75048398/103321857-f0e50980-4a3b-11eb-9eea-d1a1c59ee04e.mp4

I get a dialogue saying exporting project requires android Q+
Not able to export
Even when I share to drive node_modules can't be shared

**Comment by Proxtx** [comment]
Try the share button
