### ISSUE TITLE
Can't download zip

### ISSUE THREAD

**Issue by doubara** [spckio/spck-issues#275]
I can't download the zip file to my phone memory, when ever I try downloading I receive an error message.

And also, I can't run native JavaScript file without running Html.

**Comment by Proxtx** [comment]
Pls give us more info about your phone / app / what your trying to archive

**Comment by doubara** [comment]
my phone is itel p36 Android 9 but I guess the feature requires a phone
with Android Q+ (export zip > download).

**Comment by Proxtx** [comment]
Exporting zip files works on Android 9 please send a screen record of you trying to export a project.

**Comment by doubara** [comment]
Good morning, I'm Kieri Ayibadoubara. I love your mobile app alot, and I
would like to know how I could compile SASS to CSS on it if possible, thank
you.
