### ISSUE TITLE
Malfunction of app

### ISSUE THREAD

**Issue by emmanueledett** [spckio/spck-issues#277]
Hello Spck, recently I've been working on a html, CSS and JavaScript page. I noticed that I can't save my files (I taught Spck automatically saves it). I worked on a webpage towards the end of last year only to open it one day and I couldn't find the file again. It hurt me badly. Yesterday, stayed overnight trying to repeat that project only to wake up this morning and find out that it isn't there anymore. I've lost three projects this way. Please how can I fix it.

> `

**Comment by Proxtx** [comment]
Hey are you working on Android or iOS? Where do you have your projects?

**Comment by emmanueledett** [comment]
> Hey are you working on Android or iOS? Where do you have your projects?

Android.

**Comment by Proxtx** [comment]
So do you save your projects internal / external?

**Comment by emmanueledett** [comment]
External.

**Comment by emmanueledett** [comment]
There are three options there:
Internal, External and SD1

**Comment by Proxtx** [comment]
Ok go to this location with your file manager:
`/storage/emulated/0/Android/data/io.spck/files`

**Comment by emmanueledett** [comment]
Thanks, I finally saw it😌

**Comment by emmanueledett** [comment]
> Thanks, I finally saw it😌

I can't find my project. Everything is restored to default😔.
