### ISSUE TITLE
Missing Web API`s

### ISSUE THREAD

**Issue by subversivo58** [spckio/spck-issues#278]
The following APIs Web are disabled or missing: `Notification`,` Push` and `Webauthn`. This is due there is some limitation of the WebView or the application, I did not find references for why they are missing.

**Comment by Proxtx** [comment]
This is most due to permission issues. I would recommend you to open your webpage in chrome... Everything should be fixed there.

**Comment by subversivo58** [comment]
Thanks for the attention.
The reason for opening on the WebView is to be able to use the console, use the transit app.
I do not always have a laptop a hand to be able to do the remote debugging.
Open view in Chrome all ok the permissions are there.
