### ISSUE TITLE
Create Project Failed

### ISSUE THREAD

**Issue by e-labInnovations** [spckio/spck-issues#279]
- SPCK Version: 5.1.3
- Android Version: 7.1.2
- Model Number: Redmi 4

I can't start a new project or clone new project. Always show a message "Create Project Failed".
![](https://i.imgur.com/MM3oq7b.jpg)

**Comment by Proxtx** [comment]
In the screenshot your phone tells you that it has no memory space left(Notification). Maybe delete some apps and try it again..?

**Comment by e-labInnovations** [comment]
Ok,
After deleting some apps and files I got some internal space. Now working
