### ISSUE TITLE
Spck editor, support SASS file but doesn't compile SASS into CSS

### ISSUE THREAD

**Issue by kevinnuarillo** [spckio/spck-issues#290]
I have a project that using SASS but it doesnt compile to the css, please make it compile live server for SASS

![Screenshot_20210131-172250_Spck Editor](https://user-images.githubusercontent.com/69636669/106383899-ea5efe80-63fa-11eb-88f8-84073d879263.jpg)

![Screenshot_20210131-172328_Spck Editor](https://user-images.githubusercontent.com/69636669/106383927-ff3b9200-63fa-11eb-86e9-b06ff6e54b6f.jpg)

![Screenshot_20210131-172304_Spck Editor](https://user-images.githubusercontent.com/69636669/106383939-082c6380-63fb-11eb-8524-2d5daba76675.jpg)

![Screenshot_20210131-172312_Spck Editor](https://user-images.githubusercontent.com/69636669/106383954-10849e80-63fb-11eb-8fbb-e1ab2bd20da7.jpg)

**Comment by spck-io** [comment]
There is now a project template for this in labs. See: https://spck.io/labs/dbZicpwpj
