### ISSUE TITLE
Livepreview doesn't respect word wrap

### ISSUE THREAD

**Issue by kajdo** [spckio/spck-issues#292]
Hi,

I'm using spck to do mostly notes in markdown, I sync via GitHub. Not the best way, but my usecases doesn't allow me other cloud services.

It works like a charm, but when I read my notes, and switch to preview, the word wrap is not working at all.

This wouldn't be a deal-breaker, when horizontal scrolling would work. But this seems to be disabled.

Please have a look ... I think of a webview or similar is used, it should be rather ready to either enable scrolling, or activate word wrapping.

Thx for this Nice App

Edit:
Device OnePlus 5t
OS version Android 10 / oxygen os 10.0.1

**Comment by Proxtx** [comment]
Screenshot?
