### ISSUE TITLE
(npm) Error operation not permitted

### ISSUE THREAD

**Issue by sirius54s** [spckio/spck-issues#298]
![Screenshot_20210217-044617](https://user-images.githubusercontent.com/16833871/108187220-3a68e100-70dc-11eb-93f8-ef216493444b.png)

![Screenshot_20210217-045456](https://user-images.githubusercontent.com/16833871/108187305-51a7ce80-70dc-11eb-936c-18c3e07bc1ce.png)

**Comment by xuber86** [comment]
You need to use --no-bin-links option when installing packages that have bin links. Symlinks aren't allowed on External storage and some file systems.
