### ISSUE TITLE
Git URL format shouldn't prevent use of ":" character

### ISSUE THREAD

**Issue by lethevimlet** [spckio/spck-issues#30]
It's possible to clone a git project using user:token@github.com/owner/project,
but your input dialog is currently preventing the use of the special character ":" which limits this type of operation.

**Comment by spck-io** [comment]
I will look into this for the next update. Sorry about the delay in looking into this issue.

**Comment by spck-io** [comment]
I have changed it so that now : is accepted in the URL. Hope that helps with your issue.

**Comment by spck-io** [comment]
It seems this is working now.
