### ISSUE TITLE
React Preview does not work.

### ISSUE THREAD

**Issue by SaaranshMishra** [spckio/spck-issues#31]
I use a Xiaomi Redmi Note 4. I tried to preview the React broiler-plate code written and it did not work.

**Comment by cambo2015** [comment]
This is still an issue as of Sept.10, 2019 
Phone Model: I believe is an LG

**Comment by IDaveYoung** [comment]
I am also experiencing this issue, can provide project if required

**Comment by spck-io** [comment]
I have fixed the existing bug, it is caused by a misnaming of the app.jsx file. Please reopen this issue if you are still having problems with this.

**Comment by cambo2015** [comment]
Thanks! I will check it out.

**Comment by spck-io** [comment]
Please hold off on updating the android app. It’s currently broken, but I released a working version 2.0.3 as soon as I could, but the play store has not updated yet.
