### ISSUE TITLE
Not pushing the code to github

### ISSUE THREAD

**Issue by prabhu1122** [spckio/spck-issues#313]
I am trying to push my code to github, it shows massage that it done successfully but on other side in my github account it doesn't upload.

Link of my repo is  [Click here](https://github.com/prabhu1122/androidSensorAPI.git) 
![IMG_20210324_213839](https://user-images.githubusercontent.com/31845530/112343657-579b5b80-8ce9-11eb-9251-7ece1ede75d1.jpg)

**Comment by lrnzdc3696** [comment]
It might be because of your github account has email blocking
check if this is on in github settings if it is, they will tell you that they have an email for you so use. copy it and paste it in your spck app email section

**Comment by prabhu1122** [comment]
Thank you, now it's working I forgot to check permission for remote action during key genaration.
