### ISSUE TITLE
Wirless keyboard not working in this spck app

### ISSUE THREAD

**Issue by arshkhan7619** [spckio/spck-issues#319]
I have logitech wireless keyboard and mouse is working but keyboard is not work in this spck app  i have clicked the editor for typing at time one alphabet only typed  and cursor is missing if next  alphabet to click the keyboard.

**Comment by Proxtx** [comment]
Use GBOARD as you default android keyboard. Then try your physical keyboard again.

**Comment by Proxtx** [comment]
https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin

**Comment by arshkhan7619** [comment]
But I wanted to use wireless keyboard  if you have some ideas then says

**Comment by Proxtx** [comment]
Dude have you read my messages? Use GBOARD and then try your Wireless Keyboard again!

**Comment by arshkhan7619** [comment]
Thanku bro 🙂
