### ISSUE TITLE
Can't pull

### ISSUE THREAD

**Issue by AndrewJayStudio** [spckio/spck-issues#32]
If I revert changes to a file, it is still saying that a change was made and it won't let me pull from GitHub because of it. I don't want to commit it because that will revert the changes I made to GitHub itself. Also if you change the launch default file, the Report Issue button doesn't work.

Edit: I had to delete the local project and re - clone the git repo again for it to start working

**Comment by spck-io** [comment]
I have fixed several issues regarding diffing and file reverts in the latest version. The problem you experienced might have been due to a confusion of the staged file and the HEAD branch.
