### ISSUE TITLE
Specific public repo fails on git clone

### ISSUE THREAD

**Issue by KuberDriver** [spckio/spck-issues#320]
Was unable to open this repo on the app for some reason, tried on multiple devices yet same error. It's a public repo: https://github.com/hashicorp/terraform

Screenshots attached with error message..

![Screenshot_20210419-140902](https://user-images.githubusercontent.com/28806564/115242432-c2d62300-a119-11eb-8e78-69da268c1fb4.jpg)
![Screenshot_20210419-140855](https://user-images.githubusercontent.com/28806564/115242435-c36eb980-a119-11eb-8533-8a2f9885e0dd.jpg)

**Comment by spck-io** [comment]
Is this still an issue on the latest release?

**Comment by KuberDriver** [comment]
Apparently yes, but got few more details in the error:

![Screenshot_20220303-074301.jpg](https://user-images.githubusercontent.com/28806564/156519226-78d9a9d8-5424-47f5-8434-1ac5664d9e6b.jpg)
