### ISSUE TITLE
Error exporting ZIP

### ISSUE THREAD

**Issue by RoHBee** [spckio/spck-issues#321]
Can't export the project. I have no codes to show. Is there any problem with this error.

**Comment by Proxtx** [comment]
You need to provide more information

**Comment by RoHBee** [comment]
I am unsure why this happened and dunno what info to give.
1. My project: HTML
2. Device: Xiaomi Redmi Note 9 Pro Max
2: LOG
```
[12:23:49] File threshold exceeded for auto file import.
[12:23:49] [clear]: css
[12:23:49] [clear]: html
[12:23:49] [clear]: javascript
[12:23:49] [update]: @blank.js
[12:23:49] Starting language server
[12:23:46] [metadata] clear cache
[12:23:46] [projects] Updated project list
```

**Comment by RoHBee** [comment]
Is there any manual way of exporting the project.? I mean removing the **spck.json** and moving the file to **/storage**.

**Comment by Proxtx** [comment]
But what exactly went wrong? What makes you think that your project wasn't exported correctly?

**Comment by RoHBee** [comment]
While importing images I manually imported the images to **Android/data/io.spck..../files/Login-Form/images**. Can this cause any error? Everything else seems to be fine.

**Comment by Proxtx** [comment]
Yeah but what makes you think that there is an error?

**Comment by RoHBee** [comment]
What! "What makes me think there is an error?"
Oh my sister cries a lot! This might be causing the error.
There's nothing supernatural powers inside me to detect the error...

**Comment by Proxtx** [comment]
You don't understand.... What is the error? Not what's causing the error...

**Comment by RoHBee** [comment]
"Unable to export zip" 😭😭

**Comment by Proxtx** [comment]
Go to /storage/emulated/0/Android/data/io.spck/files/You-Project and copy all files

**Comment by RoHBee** [comment]
Okay already done. I think theres some problem with git but i dunno.

**Comment by Proxtx** [comment]
Create a new issue then

**Comment by Aplha101** [comment]
Still having the error? Are you downloading the zip? You can't download the zip untill u have android Q+ something , you can upload it on Google drive and download from there 🙂
But idts that you're still havin the error 🙃
Have a good day (and an error free life)
