### ISSUE TITLE
Bencucsk

### ISSUE THREAD

**Issue by bebcub5599** [spckio/spck-issues#323]
/data/user/0/org.qpython.qpy3/files/bin/qpython3-android5.sh && exit
iles/bin/qpython3-android5.sh && exit   <
Python 3.6.6 (qpyc:3.6.6, Jul 26 2018, 03:54:22) [BUILD WITH QPY3-TOOLCHAIN (https://github.com/qpython-android) ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by Proxtx** [comment]
?
