### ISSUE TITLE
ReadObjectFail

### ISSUE THREAD

**Issue by rxd4cted** [spckio/spck-issues#324]
Any solutions to fix this error?

### What i did
> [1] Commit something
> [2] Pull commit from repo
> [3] Push commit from repo

### Expected
> [1] Successfully pushed to remote [remote name]

### What i got
![IMG_20210428_200042](https://user-images.githubusercontent.com/68576241/116400303-7945b080-a85c-11eb-9dc6-a891e15141cf.jpg)

**Comment by manassorn** [comment]
I got a same issue
![Screenshot_20210502-124337_Spck Pro](https://user-images.githubusercontent.com/648775/116831550-5871b800-abda-11eb-9c91-0c193b85b975.jpg)

**Comment by rxd4cted** [comment]
> I got a same issue
> ![Screenshot_20210502-124337_Spck Pro](https://user-images.githubusercontent.com/648775/116831550-5871b800-abda-11eb-9c91-0c193b85b975.jpg)

Yeah, everything was good back then. Dont know why suddenly this error showed up
