### ISSUE TITLE
add CJK support

### ISSUE THREAD

**Issue by murry2018** [spckio/spck-issues#331]
Hi Spck team.
I'm new to Spck Editor and pleased to develop web applications in Android.  Thank you for this nice app!

But there is a little problem with encoding.
I want to fill my app's content with my mothertongue.
When, however, I fill the content as '가나다'(Korean letter) in the editor(see first screenshot), It brokes(see 2nd screenshot).

I found that changing the content manually in developer's console just works fine(see 3rd screenshot).

![Korean letter in the editor](https://user-images.githubusercontent.com/36194181/119213791-d69bed00-bafc-11eb-85a4-ea26b2d1f118.jpg)
[Screenshot 1]

![broken content](https://user-images.githubusercontent.com/36194181/119213845-34c8d000-bafd-11eb-8ab9-abefc39f535d.jpg)
[Screenshot 2]

![developer's console](https://user-images.githubusercontent.com/36194181/119213901-9a1cc100-bafd-11eb-96ef-93ea43eb2fd9.jpg)
[Screenshot 3]

Therefore I think this problem stems from encoding of files. I don't know what default encoding is, but I believe it's not UTF-8.

## What I want is

I want you to change the default encoding as UTF-8, or add settings to change file's encoding.

**Comment by Proxtx** [comment]
This is probably caused by ACE editor... submit an issue there

**Comment by spck-io** [comment]
You should add a meta tag to let the Webview/Browser know the encoding should be UTF-8. `<meta charset="UTF-8">`, otherwise the browser/webview may default to your system default encoding.
