### ISSUE TITLE
Spck web app showing error 404 when we run the project

### ISSUE THREAD

**Issue by thetejasmagade** [spckio/spck-issues#332]
Spck web app showing error 404 when we run the project.
Spck is my favourite online editor. But now I think developers are not maintaining this correctly.
This issue is not only in mobile view but also in desktop view.
Please fix this issue asap it's very important.

![Screenshot_20210525-192833_Chrome](https://user-images.githubusercontent.com/53045273/119510883-85eff280-bd8f-11eb-9a00-8568fa8612e8.jpg)

**Comment by Proxtx** [comment]
#328

**Comment by thetejasmagade** [comment]
Ok, I got it. Thank you😓

**Comment by Proxtx** [comment]
This is fixed now
