### ISSUE TITLE
Port isn't used but spck says me that it is used

### ISSUE THREAD

**Issue by Flymeth** [spckio/spck-issues#333]
Hello !
When I stop my nodejs server on port (for exemple) 5000, everything is okay.
But when I need to restart (close server and re-start it) the server (because changed some codes in my server.js file) on port 5000, spck tells me that this port is already used, but it isn't, and I must close then re-open the app (or change the port).

Have a great day :)

**Comment by sarma2001** [comment]
Force stop the app and try again i am also doing like that

**Comment by Flymeth** [comment]
Thanks for your response, but i don't want to close the app each time i need to restart my server ^^
