### ISSUE TITLE
Error on clone github repo

### ISSUE THREAD

**Issue by jomin398** [spckio/spck-issues#342]
Java exception was raised during method
 invocation

I try to editing my recent repo, it's needed to clone repo.
I did it, it's throws Error.
![Screenshot_20210707-133404_Spck Editor](https://user-images.githubusercontent.com/23178638/124701481-a338e480-df29-11eb-94f7-38f8cc0d245b.jpg)

**Comment by spck-io** [comment]
Try Spck for NodeJS (2.0.1), git has been rewritten in there. After a period of beta-testing it will be released to the main app.
