### ISSUE TITLE
Error - Module Node

### ISSUE THREAD

**Issue by ghost** [spckio/spck-issues#354]
When executing the command "npm intall" using SPCK Editor Pro terminal
Modelo do Smartphone: **Xiaomi Note 8 Pro**.
- SO: **MIUI 12.0.7**
- Version Android: **10QP1A**
- Kernel: **4.14**
![Screenshot_2021-08-05-11-53-31-884_io spck editor node](https://user-images.githubusercontent.com/87216580/128372976-ee84b3a4-3de9-4f8c-8ea4-60fec1cc8e25.jpg)
![Screenshot_2021-08-05-11-53-25-990_io spck editor node](https://user-images.githubusercontent.com/87216580/128373002-72071876-217a-4c50-bfee-a30e1e0a5136.jpg)

**Comment by Aplha101** [comment]
What are you installing

**Comment by Proxtx** [comment]
Add the --no-bin-links flag

**Comment by Aplha101** [comment]
> Add the --no-bin-links flag

Btw can u look at the lastest issue :')
