### ISSUE TITLE
HTTPError: 403 Forbidden (SCPK Editor mobile)

### ISSUE THREAD

**Issue by ghost** [spckio/spck-issues#356]
[
![Screenshot_2021-08-14-03-14-33-912_io spck](https://user-images.githubusercontent.com/87216580/129436161-9359c1b1-5cb7-4ea4-9ca5-3bdf3a3f88cf.jpg)

Anyone know how to solve?

**Comment by Aplha101** [comment]
Getting the same thing ,  last time I got this I switched to sock pro and it worked , but this time it's not working 😢 
You can try to use spck pro maybe it works

**Comment by ghost** [comment]
I used the token in place of the password. It worked.

**Comment by Phemjay1** [comment]
How did you use it please

**Comment by Phemjay1** [comment]
Now I have the token so how do I use it on spck editor? Please help!

**Comment by ghost** [comment]
![0001-6211430385_20210818_234401_0000](https://user-images.githubusercontent.com/87216580/129999233-c9fa16db-c986-4c38-b07a-c924a2665b04.png)

**Comment by Phemjay1** [comment]
Wow! Thank you very much 🙏 I really worked

**Comment by spck-io** [comment]
Password authentication has been deprecated for many Git providers. I believe Github has deprecated authenticating with password this year.
