### ISSUE TITLE
Error 403 , Forbidden

### ISSUE THREAD

**Issue by Aplha101** [spckio/spck-issues#357]
Cloning a repo or pushing results in an Error 403 , what can be done to fix this?

**Comment by ghost** [comment]
I faced the same problem recently. I used the token in place of my password. It worked for me.

**Comment by Aplha101** [comment]
> I faced the same problem recently. I used the token in place of my password. It worked for me.

Where/How can I get the "token"?

**Comment by Proxtx** [comment]
Yep passwords were disabled ( by GitHub) recently... That's why only tokens work.

**Comment by Phemjay1** [comment]
Please how do I get the token?

**Comment by Aplha101** [comment]
> Please how do I get the token?
https://github.com/settings/tokens
go here and then click generate new token , choose the repo option/permission 
And then done

**Comment by Phemjay1** [comment]
Now I have the token so how do I use it on spck editor? Please help!

**Comment by Aplha101** [comment]
> Now I have the token so how do I use it on spck editor? Please help!

Yea , now use it in place of your password in credentials make sure u chose the repo permission

**Comment by Aplha101** [comment]
> Please how do I get the token?
https://github.com/settings/tokens
go here and then click generate new token , choose the repo option/permission 
And then done

**Comment by Phemjay1** [comment]
Wow! That really worked, thank you very much 🙏
