### ISSUE TITLE
Formatting plain text on Android

### ISSUE THREAD

**Issue by jchwenger** [spckio/spck-issues#366]
Hi, thanks for the great app! I'm using the Android version.

I'm looking for a way to format a paragraph of plain text, the way you can do it with vim for instance with 'gq' (and you would have an option to say that you want your line to be e.g. 80 characters).  I can see a 'format' option on the app, but it doesn't seem to do that:
![20210925_123322](https://user-images.githubusercontent.com/34098722/134770158-b3a9ed25-f22d-41a2-84de-156c66019bbf.jpg)

I didn't research this very deeply, but could neither create an example where I could see its effect not a mention in the docs.

Is it something that the app does, or that you plan to include? Possibly a customization of said function? That would be super nice.

Thanks for reading!

**Comment by spck-io** [comment]
Closing as it's implemented in 8.0.8 (android) and 4.0.10 (iOS).
