### ISSUE TITLE
Git control 

### ISSUE THREAD

**Issue by Shreyansh-07** [spckio/spck-issues#368]
I'm not able to commit my work to GitHub. I can clone a repo. I can edit it too. But when I commit it all to GitHub not shows that the commit I'd done but I see no change on my repo files. 
Device- Lenovo Tab M7.
Android version- 9

**Comment by Proxtx** [comment]
You have to push

**Comment by Shreyansh-07** [comment]
> You have to push

Oh! Sorry...🤦
