### ISSUE TITLE
What's this?!?

### ISSUE THREAD

**Issue by Aplha101** [spckio/spck-issues#370]
Some projects with some demonic texts get created in my internal storage ,  when I try to delete them , the app crashes and I have to restart the device to fix the crash  
![Screenshot_2021-10-02-22-24-12-221](https://user-images.githubusercontent.com/76000535/135765497-3eca2cc1-aac4-4b9f-9928-2986069ff4cb.jpeg)

**Comment by spck-io** [comment]
Are you still seeing this issue? It might be a security problem with using SD card since other apps may be able to create files on your SD card.

**Comment by Aplha101** [comment]
> Are you still seeing this issue? It might be a security problem with using SD card since other apps may be able to create files on your SD card.

Nope now it's gone
