### ISSUE TITLE
Melhorias

### ISSUE THREAD

**Issue by ruancarlosss** [spckio/spck-issues#373]
O app é muito bom. Tem me ajudado a estudar as linguagens que preciso. Sua vasta experiência é muito desfrutante e agradável! Vocês poderiam colocar a opção de mudar os caracteres da barra acima do teclado, colocar o que mais usamos ou simplesmente deixar a gente escolher!! App ótimo bem otimizado. Não trava, aguenta um vasto texto de código...meu máximo é 300 linhas e não travou. Observação: uso um Android 6.0.1 #372 @spck-io

**Comment by Proxtx** [comment]
Yes
