### ISSUE TITLE
Can't add github token

### ISSUE THREAD

**Issue by ghost** [spckio/spck-issues#374]
I go to settings and add token, i enter token but nothing happens
![Screenshot_20211019-142516_Spck Editor](https://user-images.githubusercontent.com/68414637/137877117-1cfe3140-9d43-4acf-843b-c9a7eec0ac8b.jpg)

**Comment by ghost** [comment]
Yes i pressed ok and waited and also restarted

**Comment by emshimada** [comment]
I have the same problem.

**Comment by spck-io** [comment]
Is the token saved? The token is meant for accessing private repositories and pushing to your git repo through the "Clone" feature.

**Comment by Aplha101** [comment]
> Yes i pressed ok and waited and also restarted

Did u select the repo option/permission on GitHub? 

[This video](https://youtu.be/kHkQnuYzwoo) really helped me when tokens were announced

**Comment by spck-io** [comment]
Please refer to the documentation on creating app tokens: https://spckio.github.io/spck-documentation/create-app-token.html#
