### ISSUE TITLE
Unable to pull if no common ancestor, e.g. after a force push

### ISSUE THREAD

**Issue by EspenBrun** [spckio/spck-issues#375]
Would like some way to reset current branch to match remote, or at least be able to checkout origin/branch. Now I can not pull and can't read the latest changes in the force pushed branch.

![Screenshot_20211020-174532_Spck Editor](https://user-images.githubusercontent.com/22228208/138126472-d4d29ee0-9239-4f2a-8c70-3cba8faa3be5.jpg)

**Comment by spck-io** [comment]
This feature should be released soon in the Pro (Spck for NodeJS) version. Please test it out to make sure everything is working.
