### ISSUE TITLE
Img Not showing

### ISSUE THREAD

**Issue by Mukeshkingstar** [spckio/spck-issues#383]
![Screenshot_2021-11-19-00-22-39-409_io spck](https://user-images.githubusercontent.com/94641465/142478509-8a84c04c-6bdc-468b-8e4e-508e12b0508f.jpg)
 
IMAGE 🖼 IS NOT SHOWING PLZZ HELP

**Comment by Aplha101** [comment]
Is the image in your code folder?

**Comment by Mukeshkingstar** [comment]
this is the image url

https://i.postimg.cc/FRYXLSJd/IMG-20211127-103835-496.webp

**Comment by Proxtx** [comment]
https://en.wikipedia.org/wiki/Cross-origin_resource_sharing
