### ISSUE TITLE
Weird lines introduced on push/pull from various PCs

### ISSUE THREAD

**Issue by nathaneltitane** [spckio/spck-issues#385]
I've committed some code from my tablet and upon pulling on my laptop to continue the next day, some weird lines introduced themeselves in the code.

This is really not good.

Please fix?

![image](https://user-images.githubusercontent.com/5674757/143619145-085c4550-b1a9-49f0-a7f8-a0e249b32dc6.png)

**Comment by spck-io** [comment]
This is produced by the isomorphic-git as part of how git handles merge-conflicts. It means that git does not know how to automatically resolve the merge conflict and produced some in-line artifacts to show the difference between the old and new versions. VSCode has a way to automatically parse these line-artifacts and produce a nice diff-view, but this is currently not handled in Spck editor.
