### ISSUE TITLE
Cannot connect GitHub account to spck pro

### ISSUE THREAD

**Issue by Aplha101** [spckio/spck-issues#388]
Last week I connected my gut account to spck pro and it was successful, but today when I'm trying to connect again it's giving me an error , I've tried revoking it from the OAuth on GitHub but nothing happens

![Screenshot_2021-12-02-10-23-56-872.jpeg](https://user-images.githubusercontent.com/76000535/144741900-c9e6b0ab-34ee-4d3f-b851-ae01dab5171a.jpeg)

**Comment by spck-io** [comment]
This error means that your email was previously used by another provider (Google, or Facebook). You need to sign-in with the original login provider or you need to use a new email account with Github sign-in.
