### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by cambo2015** [spckio/spck-issues#39]
Typescript support would be amazing. Is that a feature coming in the future?

**Comment by spck-io** [comment]
Typescript is currently supported in the Angular template by using SystemJs to transpile ts.

**Comment by cshaa** [comment]
Currently, TypeScript doesn't have type checking in Spck. Since I installed the app in order to maintain my TS project, it's useless to me this way.

**Comment by spck-io** [comment]
I am working on this issue. Thanks for letting me know.
