### ISSUE TITLE
After merge, git push doesn't finish

### ISSUE THREAD

**Issue by vlrfsg** [spckio/spck-issues#390]
I've encountered this problem several times in versions 5.3.2 and 6.0.0. I suppose this was covered by more serious issues in earlier versions.
I did:
- Clone a repository on spck.io from an organization
- Edit something(A) on spck.io
- Edit, commit and push something(B) on PC via Github's desktop app
- Commit (A) on spck.io
- Pull (B) on spck.io
  - (A) and (B) are automatically merged
- Try to push (A)
Since there was a bug in showing number of commits to push, I couldn't find what is happening. However, it is solved in v6.0.0 to show me that my one-line-diff commit has became enormous 906 commits to push.
I've been avoiding this issue by deleting the repository from workspace and clone it again. This is not a beautiful way, but faster than awaiting the push to finish.
Also, it makes me feel the time longer that the progress bar doesn't move during push.

**Comment by spck-io** [comment]
Thanks for the detailed report. Will investigate this issue.

**Comment by spck-io** [comment]
Git has been overhauled in 2.0.1 of Spck for NodeJS. You can early test it there before it gets released in Spck Editor.

**Comment by vlrfsg** [comment]
Thank you. Merge is working. It seems to have taken you much work. It is very useful now.

However, the number displayed next to "Push" keeps increasing. Could you check whether the counter is cleared when we push or not?

**Comment by spck-io** [comment]
Yes, there is a minor bug there that is recently fixed. Thanks for reporting. Will release the next version soon.
