### ISSUE TITLE
Cannot sign in any any of the apps(pro or webapp)

### ISSUE THREAD

**Issue by Aplha101** [spckio/spck-issues#392]
Wherever I try to sign in I just get some error 

![Screenshot_2021-12-23-21-21-35-488](https://user-images.githubusercontent.com/76000535/147265599-b39f3283-36eb-4494-9a94-8672e89a39f0.jpeg)
![Screenshot_2021-12-23-21-35-34-498](https://user-images.githubusercontent.com/76000535/147265602-46785a21-87bc-4a95-9b20-6497d7a177d7.jpeg)

Please help , I tried clearing the data but nothing happened also tried reinstalling and revoking from GitHub

**Comment by Proxtx** [comment]
use https://spck.io

**Comment by Aplha101** [comment]
> use https://spck.io

I tried signing in there too it's the same thing

**Comment by spck-io** [comment]
This issue should be fixed as of the latest release.
