### ISSUE TITLE
Whats with the workspace?

### ISSUE THREAD

**Issue by Aplha101** [spckio/spck-issues#393]
Is the workspace suppose to save all the projects in opened on spck? Like that over here?
![Screenshot_2021-12-25-11-00-25-278.jpeg](https://user-images.githubusercontent.com/76000535/147378123-3955af70-6fb7-46e7-be93-479fcaf11ffc.jpeg)

But that dosent work , I have to open different projects by cloning them again and again :/ 

![Screenshot_2021-12-25-10-58-48-453.jpeg](https://user-images.githubusercontent.com/76000535/147378136-8b002d44-555f-4bb5-8b74-ab1aa9e8efac.jpeg)

**Comment by Aplha101** [comment]
Nothing is being saved here

**Comment by Proxtx** [comment]
Yes it is supposed to do that

**Comment by Aplha101** [comment]
> Yes it is supposed to do that

But it's not 😐

**Comment by Aplha101** [comment]
I don't see my projects it's a lengthy process to clone them again and again

**Comment by spck-io** [comment]
Is this issue still present on the latest release (6.0.4)?

**Comment by Aplha101** [comment]
> Is this issue still present on the latest release (6.0.4)?

6.0.4? I recently updated and i got 6.0.3 so is it not released? Playstore isn't giving any more updates

**Comment by Aplha101** [comment]
Works on 6.0.5 !
