### ISSUE TITLE
Sign up problem remains same for GitHub in the Latest release ( 6.0.5)

### ISSUE THREAD

**Issue by Aplha101** [spckio/spck-issues#401]
https://user-images.githubusercontent.com/76000535/147844984-b1cf2910-8e9d-4d78-bbac-269b66b84ebf.mp4

Here's the screen recording , of it 
This problem remains on spck pro , spck 6.0.5 and https://spck.io
Fortunately the problem is just with GitHub now , so Im able to sign in with Google

**Comment by Proxtx** [comment]
I think I understand what's happening and how to fix it:

Basically you have the GitHub app installed and told Android to open all GitHub related things with it. Spck is hosted on GitHub. That's the reason GitHub opens when you click on sign in. However GitHub realizes that it is unable to open the page it's ment to open and tries to open it in Chrome. Unfortunately Spck passed some extra arguments wich got lost in the redirecting process. To fix this go to your Settings -> Apps -> GitHub -> Open By Default -> Always Ask

**Comment by Aplha101** [comment]
> I think I understand what's happening and how to fix it:
> 
> Basically you have the GitHub app installed and told Android to open all GitHub related things with it. Spck is hosted on GitHub. That's the reason GitHub opens when you click on sign in. However GitHub realizes that it is unable to open the page it's ment to open and tries to open it in Chrome. Unfortunately Spck passed some extra arguments wich got lost in the redirecting process. To fix this go to your Settings -> Apps -> GitHub -> Open By Default -> Always Ask

![Screenshot_2022-01-01-14-43-39-629.jpeg](https://user-images.githubusercontent.com/76000535/147847610-b7af02ae-b6fb-431c-8c81-b9c4bc9f3789.jpeg)

Just tried what u said , and now it's giving me some other error ...
I reported the same error ( the one in the screenshot in this reply ) a month ago to GitHub support and they told me to revoke spck from GitHub and try again I did that , and then got the error that I'm reporting now ( in this issue) 

I haven't changed my email or password , but the GitHub token

**Comment by Proxtx** [comment]
Did you login with GitHub the first time you used your email address?

**Comment by spck-io** [comment]
If you use the same email address as Google Sign-in, please use Google to sign-in. Spck uses Firebase for authentication, and prevents multiple accounts using the same email address to prevent abuse.

**Comment by DanielMucamba** [comment]
I'm using spck editor pro and I'm not able to register using Google, it always returns login error 10: what do I do 😩

**Comment by DanielMucamba** [comment]
I'm using spck editor pro and I'm not able to register using Google, it always returns login error 10: what do I do 😩

**Comment by spck-io** [comment]
Thanks for the bug report. I’m looking into it.

**Comment by DanieleSpuria** [comment]
Has the problem with GitHub been resolved? Thank you
