### ISSUE TITLE
Feature idea

### ISSUE THREAD

**Issue by Aplha101** [spckio/spck-issues#402]
A feature about code schematics, saved code blocks can be reused globally in any project , 
It can be accessed through the Bot or with a new tab "schematics" beside the File/search/Git tabs

**Comment by DerGoogler** [comment]
Did you mean code snippets, like in VS Code?

**Comment by Aplha101** [comment]
> Did you mean code snippets, like in VS Code?

No not snippets , like a wrote some function or just some css that i can re use in my future projects so I'll just save that as a schematic and use it wherever I want , just like saving notes

**Comment by Aplha101** [comment]
> Did you mean code snippets, like in VS Code?

Snippets generates a format for the keyword you chose , schematics however will save the code that you wrote in the project , if you ever played the game "mindustry" you'd get what I mean
