### ISSUE TITLE
Add options to change background

### ISSUE THREAD

**Issue by wolf-yuan-6115** [spckio/spck-issues#403]
Add options to chnage background.

Excepted step to change background:
- Go to settings => Background
- Choose `Import image...`
- A media picker will pop out
- After that, Spck will copy that image to `<internal storage>/.spckConfig/background/<index of image>.<file extension>`
  - `index of image` mean first background will be 1, second will be 2...
- Then change background image.

**Comment by DerGoogler** [comment]
I think it'll look trashy with custom background images. The currently images are specific selected.

**Comment by Aplha101** [comment]
> I think it'll look trashy with custom background images. The currently images are specific selected.

You can add filter settings like blur and stuff and who the hell would choose some pic from Disney World as their background 😐

**Comment by wolf-yuan-6115** [comment]
Yes, blur effect can be done with css: `backdrop-filter: blue(4px)`.

**Comment by Aplha101** [comment]
> Yes, blur effect can be done with css: `backdrop-filter: blue(4px)`.
> 

Yes but , I meant on spck , the feature .... Not talking about html/css

**Comment by wolf-yuan-6115** [comment]
Yes, but Spck is written in Html, Css and JavaScript, it is packaged in
cordova or something else i think.

**Comment by DerGoogler** [comment]
I think Spck is written in Vue.js.

**Comment by Proxtx** [comment]
The background images are blurred already by spck. In the Discord we looked at the original images (by searching through the html request) and found out that they are not blurred. We even put our own image instead of the default one and it looked acceptable: 
![unknown-1.png](https://user-images.githubusercontent.com/39201896/147912385-edc8e68f-1074-499f-80b9-8a3bfe823d98.png)

**Comment by Aplha101** [comment]
> The background images are blurred already by spck. In the Discord we looked at the original images (by searching through the html request) and found out that they are not blurred. We even put our own image instead of the default one and it looked acceptable: 
> ![unknown-1.png](https://user-images.githubusercontent.com/39201896/147912385-edc8e68f-1074-499f-80b9-8a3bfe823d98.png)

I mean yeah that background looks great XD

**Comment by DerGoogler** [comment]
> > The background images are blurred already by spck. In the Discord we looked at the original images (by searching through the html request) and found out that they are not blurred. We even put our own image instead of the default one and it looked acceptable: 
> > ![unknown-1.png](https://user-images.githubusercontent.com/39201896/147912385-edc8e68f-1074-499f-80b9-8a3bfe823d98.png)
> 
> I mean yeah that background looks great XD 

Not really..

**Comment by spck-io** [comment]
I will consider it, but bug fixes are my top priority right now. There is actually some annoying glitches using backdrop-filter and I have opted not to use this.

**Comment by Aplha101** [comment]
> I will consider it, but bug fixes are my top priority right now. There is actually some annoying glitches using backdrop-filter and I have opted not to use this.

Alr chief

**Comment by wolf-yuan-6115** [comment]
No, its written in Spck UI (Of course)

**Comment by wolf-yuan-6115** [comment]
> I will consider it, but bug fixes are my top priority right now. There is actually some annoying glitches using backdrop-filter and I have opted not to use this.

Oh yes, like it is not working in Firefox by default. We need to enable some feature in firefox config page.

**Comment by Volumeclassmate** [comment]
怎么自定义啊

**Comment by spck-io** [comment]
Added as of 6.1.2.
