### ISSUE TITLE
Eruda console

### ISSUE THREAD

**Issue by adr420** [spckio/spck-issues#404]
While using eruda's console in app, the console gets hanged on getting any error ,sometimes it makes the whole app to be hanged ...

Please fix this

**Comment by Proxtx** [comment]
Use the Legacy Console option (settings)

**Comment by adr420** [comment]
Oh, but this is not a solution at all, i have tried lagacy which has no features other than direct logging [Object object] , will it(eruda) be ever fixed ?

I have used eruda manullay(without spck) too where it works better , there is some problem with the app...

and yes ,right now, i am using lagacy....

**Comment by Aplha101** [comment]
> Oh, but this is not a solution at all, i have tried lagacy which has no features other than direct logging [Object object] , will it(eruda) be ever fixed ?
> 
> I have used eruda manullay(without spck) too where it works better , there is some problem with the app...
> 
> and yes ,right now, i am using lagacy....

Try [this eruda](https://www.npmjs.com/package/eruda) it works smooth for me , also it has more features like javascript execution and source code etc ( similar to chrome dev tools) 

```xml
<script src="//cdn.jsdelivr.net/npm/eruda"></script>
<script>eruda.init();</script> 
```
Put this in your html and your eruda is updated

**Comment by adr420** [comment]
Thank you ,but i may not have internet all time , the app must be updated...

**Comment by Aplha101** [comment]
> Thank you ,but i may not have internet all time , the app must be updated...

Install it with npm and move all the folders to your project, that won't require internet and yes I'd like this version of eruda to be added in spck

**Comment by Proxtx** [comment]
You can download the files manually

**Comment by spck-io** [comment]
Updated Eruda in the new release. Let me know if it still lags, I think the cause was there was too much stuff being written to the console due to how Eruda was packaged with the application.

**Comment by adr420** [comment]
It's working fine now.
