### ISSUE TITLE
Spck cannot access storage 

### ISSUE THREAD

**Issue by Aplha101** [spckio/spck-issues#405]
For some reason I cannot select the internal storage option in the workspace

![Screenshot_2022-01-02-19-11-31-782.jpeg](https://user-images.githubusercontent.com/76000535/147877699-93faac33-23f3-4334-985c-069ff443b9bd.jpeg)

I cannot access it , the button isn't responding

**Comment by spck-io** [comment]
Does this happen every time you visit workspace or only sometimes?

**Comment by Aplha101** [comment]
> Does this happen every time you visit workspace or only sometimes?

Everytime now

**Comment by Aplha101** [comment]
> > Does this happen every time you visit workspace or only sometimes?
> 
> Editing this again , i opened spck to check the workspace again and I can see it working now out of no where , whereas for the past like 1-2 days it wasn't working

**Comment by Aplha101** [comment]
> Does this happen every time you visit workspace or only sometimes?

Ok update this is  12hours after i checked the working of workshop and now it's gone 
Please look into the matter @spck-io 

![Screenshot_2022-01-04-21-48-10-666.jpeg](https://user-images.githubusercontent.com/76000535/148090194-46376aad-4d9a-4205-a897-4c007bfdad3f.jpeg)

**Comment by spck-io** [comment]
Let me know if you're still experiencing this issue on the new version 6.0.6. Added some error catching code around getting external drives on Android.

**Comment by Aplha101** [comment]
> Let me know if you're still experiencing this issue on the new version 6.0.6. Added some error catching code around getting external drives on Android.

Till now everything seems fine the workspace is working , I'll tell the final result in 2-3 days

**Comment by Aplha101** [comment]
It seems that there's no problem with the storage now , I'm closing this issue

**Comment by Aplha101** [comment]
> It seems that there's no problem with the storage now , I'm closing this issue
