### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by zshMVP** [spckio/spck-issues#406]
![JavaScript](https://user-images.githubusercontent.com/74349057/147949241-dbb76e30-af58-4af8-bc4e-f31936582142.jpg)
This is my javascript.I often get an error when I run on Spck Editor.
![Error](https://user-images.githubusercontent.com/74349057/147949814-5d1fca26-0655-47b5-9b7b-782ee984d65f.jpg)
This is my html.
![Html](https://user-images.githubusercontent.com/74349057/147950072-d512fb0c-eeb7-4d63-bb52-a68571e1cd1a.jpg)
But when I run in the browser，never report an error.
System: Android11

**Comment by Aplha101** [comment]
> ![JavaScript](https://user-images.githubusercontent.com/74349057/147949241-dbb76e30-af58-4af8-bc4e-f31936582142.jpg)
> This is my javascript.I often get an error when I run on Spck Editor.
> ![Error](https://user-images.githubusercontent.com/74349057/147949814-5d1fca26-0655-47b5-9b7b-782ee984d65f.jpg)
> This is my html.
> ![Html](https://user-images.githubusercontent.com/74349057/147950072-d512fb0c-eeb7-4d63-bb52-a68571e1cd1a.jpg)
> But when I run in the browser，never report an error.
> System: Android11
> 
> 
Many people complained the same thing on stackoverflow ,  you can try to add an event listener to it and see if it works
