### ISSUE TITLE
A really big error ( UI bug) 

### ISSUE THREAD

**Issue by Aplha101** [spckio/spck-issues#407]
~~Spck tells you how big your error really is~~ ( jk) , another UI bug
Btw is it really supposed to be this big? 

Version 6.0.5 

![Screenshot_2022-01-03-23-59-55-684.jpeg](https://user-images.githubusercontent.com/76000535/147970023-e6f6cb03-ec94-4a63-b23e-5e4004382b5f.jpeg)

**Comment by spck-io** [comment]
Thanks for reporting. Really silly looking error, will fix for next release.
