### ISSUE TITLE
This ain't a issue 😅

### ISSUE THREAD

**Issue by alenpaul2001** [spckio/spck-issues#41]
Guys this ain't an issue,But really loves to say an appreciation towards the application u guys managed to create.Soory for misusing the git issue panel.I will be really satisfied if u guys add python support to spck editor.
Thanks

**Comment by Proxtx** [comment]
I don't think, that Python support will be added because first ace editor have to support it. Additional spck editor is not able to run Python code. The reason for that is, that it can't access the system bash or download python to the local storage.

**Comment by alenpaul2001** [comment]
> I don't think, that Python support will be added because first ace editor have to support it. Additional spck editor is not able to run Python code. The reason for that is, that it can't access the system bash or download python to the local storage.

**Comment by spck-io** [comment]
I don’t think Python officially supports Android. I did some research and Androids implementation of Linux has some serious flaws (for example fork process doesn’t work correctly). I do not plan to support this in the near future, unless someone releases a stable python sdk for Android in the future.
