### ISSUE TITLE
Account - not possible to sign in with github 

### ISSUE THREAD

**Issue by aisbergde** [spckio/spck-issues#410]
When I try to sign-in with github, then I get this error

>Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared.

I can sign in with Google, this works, but I would prefer github or gitlab

**Comment by spck-io** [comment]
Please refer to #401 to see if that solves your issue. The authentication flow is handled by firebase and it seems to a prevalent issue. OAuth2.0 redirects are handled by firebase which opens a Chrome browser to do the redirection. If you have any Github apps installed, it will override any request to https://github.com which may be what's causing this issue. The solution in #401 seems to change some setting in the Github app to not interfere with the redirection.

**Comment by aisbergde** [comment]
I think this is the same issue. I will think about whether I will continue to log in with google or remove the default for github.
