### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by adr420** [spckio/spck-issues#415]
I need it ,is it removed , bring it back...

**Comment by Aplha101** [comment]
It's still there
![Screenshot_2022-01-11-15-47-38-690.jpeg](https://user-images.githubusercontent.com/76000535/148924407-592cd0a2-ed61-4f5b-b64c-fa96de4720b3.jpeg)

**Comment by Aplha101** [comment]
> I need it ,is it removed , bring it back...

Can u send a screenshot of ur style sheet?

**Comment by adr420** [comment]
![Screenshot_20220112-104909_Spck Editor](https://user-images.githubusercontent.com/69690253/149068510-ddf46995-3acc-4c82-b35d-d3a684e5c4a1.jpg)

Before it also appears on selecting the text , i do not want extra buttons...

**Comment by Aplha101** [comment]
![Screenshot_2022-01-12-13-41-20-498.jpeg](https://user-images.githubusercontent.com/76000535/149088733-4985da25-8f78-424a-ad9a-2bf96e3358a3.jpeg)

You mean this? It only appears when u type a color name , I never saw that thing appear After selecting a text

**Comment by spck-io** [comment]
You need to re-enable the "Extra Keyboard" under settings to get the extra bottom row of keys. It seems you have it disabled.

**Comment by adr420** [comment]
Here , I want to request a feature from you,that is,to show a color picker option in that(auto complete) list whenever i type hexadecimal value, rgba,hsla etc. in a .sass / .css/ .scss file...

It would be hard for me to add an extra keyboard in a very small code area

**Comment by Aplha101** [comment]
>  
> ![Screenshot_20220112-104909_Spck Editor](https://user-images.githubusercontent.com/69690253/149068510-ddf46995-3acc-4c82-b35d-d3a684e5c4a1.jpg)
> 
> Before it also appears on selecting the text , i do not want extra buttons...

Why haven't u updated tho..

**Comment by adr420** [comment]
Today i have updated 

> Here , I want to request a feature from you,that is,to show a color picker option in that(auto complete) list whenever i type hexadecimal value, rgba,hsla etc. in a .sass / .css/ .scss file...
> 
> It would be hard for me to add an extra keyboard in a very small code area

but are you going add this feature , it's not there ?

**Comment by adr420** [comment]
The reason for which i have opened this issue is resolved ,i was not able to find the color picker and now it works , nothing to do with this, please take time to work on #418 ,as an editor the app does not support code highlighting for many files (e.g: Makefile, .hpp ,CMakeLists.txt as far i have discovered).
