### ISSUE TITLE
Android Filesystem Support

### ISSUE THREAD

**Issue by spck-io** [spckio/spck-issues#42]
This is more of an announcement to give a heads up on what will be happening in the next major release.

I’m currently rewriting the entire storage backend without breaking compatibility with some of the existing features or corrupting existing files. Unfortunately I did not have the foresight to not completely not rely on Dexie.js (indexedDB) querying API. I have came to the conclusion that the Github API integration will definitely break and some features like git status updates of the file system (color changing according to git status) might also break.

I plan to add keep the legacy version of the editor around, but by upgrading through the Android Play Store, it will upgrade to the newer version with external file storage and more refined Git integration. I do not think this will corrupt or delete any files but I cannot make any guarantees about if the browser storage will not be wiped through an update of the webview. The good news is after switching to external storage it will fix any data loss issues related to using indexedDB. The browser version of the editor will continue to use the indexedDB API. Currently the file storage also stores git hashes and does it’s own git status logic which may have bugs when used with the git backend.

I am also writing extensive tests with the new system so it should not choke on binary files and other cases that were not considered when I initially wrote the editor. However this may take some time, and I appreciate everyone’s patience :).

**Comment by spck-io** [comment]
Recent developments in Android scoped storage is making me reconsider this request as it would limit the usefulness of this update. The filesystem developed in the app appears way more reliable than Androids new filesystem

Please see https://commonsware.com/blog/2019/06/07/death-external-storage-end-saga.html

To summarize:
- Apps may only use SAF or internal storage from now on, any apps using external storage will break next year.
- Files that are not created by the app will be invisible to the app, including any files moved into the device by USB cable
- Using SAF appears to be 25-100x slower than Files API which is unacceptable for git operations, what may have originally taken 30 seconds will take over an hour to complete. Additionally it is a buggy and incomplete API which you cannot even get basic information from, I.e. the path for a file making it incompatible with the app 
- Using internal storage the app can function as intended but files are removed upon uninstall and only allow for users to copy out the file via USB. Any modifications to the file outside the app may render the file unusable by the app.
- Android filesystem APIs neglect symbolic links and mode information making it incompatible with git implementations
- Apps like termux is also facing major compatibility challenges with Android Q https://github.com/termux/termux-app/issues/1072

**Comment by Proxtx** [comment]
I did a little bit of research about the Cordova Plattform:
It is not that hard to edit / read files in the directory of the app.
It is a little bit harder to edit external files.
But an interesting thing is, that it is able to support the IOS filesystem.

And an Idea for the integration: It would be great if could open single files and if there would be an option to add project from path.

**Comment by spck-io** [comment]
I have some separate issues for iOS. From everything I read about Android Q, it seems like the read external files API will change so all the files created outside of the app are hidden (inaccessible to the app) even with READ EXTERNAL storage permissions. Additionally anything that adds a file URL scheme to the system will no longer be supported in the future, not sure how Google wants apps to handle this is the future. Currently a lot of apps are not using SAF to read external files, but using the legacy behaviour instead and with external storage permissions. Android documentation states this behaviour is going to break next year when they release android Q and they will backfill this behaviour to all previous android versions using API 30. 🤔 My plan is to integrate an HTTP server in the near future, start switching to internal storage which still behaves like a native file system. Additionally, Android doesn’t provide an efficient way to transfer binary data between JavaScript and Java, they do not support transferring bytes data and everything is coerced from Java String or ints to JavaScript and back. The fastest way others have tested is doing base64 conversion and back. I haven’t tested how slow this is gonna be yet, but I somehow suspect it won’t be faster than using indexedDB 😰

**Comment by spck-io** [comment]
Currently trying to decide if I want to go with a slightly broken and unmaintained Nanohttpd in Java, or go the ndk route and try to compile something like nginx for Android... I have no experience with ndk 😨

**Comment by spck-io** [comment]
I almost have the filesystem stuff working, I’m having some issues keeping the http server running... hopefully I can sort that out soon.

**Comment by Proxtx** [comment]
If it is possible I think it would be a good idea, that the app backups all projects before deleting the indexedDB.

**Comment by spck-io** [comment]
That’s a great idea! I have implemented all the features as of yesterday, I will probably be making an update to the Android app in the new few days. The way the migration will work is the following:

Projects using indexedDB will have an IDB icon next to them. Opening IDB projects will open a prompt asking the user to migrate the project to the FS, or they can choose to backup, if they choose the backup option, migration is deferred to until the next time they try to open the project. They can continue to work on their IDB project as before. The migration process will show a progress indicator, if the migration encounters some issue, no changes to the project will be made and they can continue working on their project in IDB. New projects created will always use Android FS, there is no option to switch to IDB for new projects due to data integrity issues that some users have reported. I suspect that some Android phones will clear IDB when low on storage or external clutter management apps are deleting it somehow or perhaps some bugs in Chrome led to the loss of data in IDB.

As a further note, testing your app in native browsers like Chrome and Firefox will be available in the upcoming release!

**Comment by Proxtx** [comment]
Am I able to access the project with an file manager?

**Comment by spck-io** [comment]
Filesystem support has been added to the mobile editor since version 3.0.0 of the android app, closing this for now.

**Comment by hiukky** [comment]
@spck-io where the repository clone goes ... I can't find the directory for access with termux :/

**Comment by Proxtx** [comment]
You will need root

**Comment by Proxtx** [comment]
But if you have it should be in /data/data/io.spck

**Comment by Proxtx** [comment]
I don't have root so I only think it should be there

**Comment by hiukky** [comment]
> I don't have root so I only think it should be there

yes .. my device is in version 10 of android and with super user access. but I had already searched this directory but without success.

**Comment by spck-io** [comment]
What file manager are you using to access the rooted device? Does your file manager have root support? I’m not sure how Android 10’s scopes storage affects rooted devices. I read under normal conditions all files will be invisible to other apps.

**Comment by hiukky** [comment]
> Qual gerenciador de arquivos você está usando para acessar o dispositivo enraizado? O seu gerenciador de arquivos tem suporte root? Não tenho certeza de como o armazenamento de escopos do Android 10 afeta os dispositivos raiz. Eu li em condições normais todos os arquivos serão invisíveis para outros aplicativos.

I use the pro version of Solid Explorer and it has a great support for root. I browsed in possible folders in my root but I didn't succeed in the search. if it's really around here ... it's well hidden lol : )

**Comment by Proxtx** [comment]
Are you sure that your projects are saved to the local storage?

**Comment by Proxtx** [comment]
And maby try again on an other Fileexplorer

**Comment by hiukky** [comment]
you doubt it... The cloned github repository is stored on the device ... because the use of the import based on the downloaded zip works, but only with the zip, it extracts it somewhere ... because it would also work I download the repository, extract it and open the folder with the extracted project ... that way I could work on the thermux and spck without problems.

**Comment by hiukky** [comment]
> E maby tente novamente em outro Fileexplorer

I'll try Root Explorer

**Comment by omegapaulo** [comment]
Hello @spck-io how is it possible to work with my Android files? Can't find a way and after reading all this I am even more confused ( new dev alert ) is it so that I can't save files locally and work with it? I'd like to use termux and node to create little projects on my phone.

**Comment by albino-babuino** [comment]
alert(), prompt(), confirm(), doesn't work in iOS.

**Comment by Poker1x** [comment]
Hello. Acode has supported reading system files of termux applications. however, I don't like Acode. I hope Spck can do this

**Comment by Proxtx** [comment]
You can choose "Open With Spck" in your file manager

**Comment by ademola-lou** [comment]
App is useless if we can't even access the file manager unless you're rooted lol

**Comment by MrHinsh** [comment]
The android app for Obsidian is able to access external storage and share files with other apps.

Perhaps taking a look at their code will lead to some insight.
