### ISSUE TITLE
I'd like to suggest an enhancement

### ISSUE THREAD

**Issue by Aplha101** [spckio/spck-issues#420]
![Screenshot_2022-01-15-20-37-40-149.jpeg](https://user-images.githubusercontent.com/76000535/149626648-43f88193-3d84-4046-af7e-ca8e6ae15d96.jpeg)

When we fold a function , the grey box is sometimes a bit annoying to look at so it'd be better if the grey box gets removed and also errors inside a folded function do not show up that can be hard to find when there are a lot of folded things

**Comment by spck-io** [comment]
Fixed as of 6.1.2.
