### ISSUE TITLE
Your account is logged into too many devices.

### ISSUE THREAD

**Issue by tachibana-shin** [spckio/spck-issues#421]
Steps to reproduce the error:

1. Get the app
2. Log in to your account
3. Delete apps suddenly
4. Then reload the app
5. Login -> error `Your account is logged into too many devices.`

**Comment by Aplha101** [comment]
You can try revoking it from GitHub ,  that's what GitHub support told me

**Comment by tachibana-shin** [comment]
> Bạn có thể thử thu hồi nó khỏi GitHub, đó là những gì bộ phận hỗ trợ GitHub đã nói với tôi



> You can try revoking it from GitHub , that's what GitHub support told me

if i login with facebook or google what should i do?

**Comment by Aplha101** [comment]
> > Bạn có thể thử thu hồi nó khỏi GitHub, đó là những gì bộ phận hỗ trợ GitHub đã nói với tôi
> 
> 
> 
> > You can try revoking it from GitHub , that's what GitHub support told me
> 
> if i login with facebook or google what should i do?

![Screenshot_2022-01-16-12-16-27-814.jpeg](https://user-images.githubusercontent.com/76000535/149650218-6f14e0a4-b78e-4b04-860b-6a9c99c3ad0f.jpeg)

You can try to Signout all then try again

**Comment by spck-io** [comment]
Try logging in again after getting this error. This should be fixed in the latest version.
