### ISSUE TITLE
Security suggestion

### ISSUE THREAD

**Issue by Khaled-dev3** [spckio/spck-issues#423]
Hi spck editor dev/devs (idk how many developers are working on this editor)
So I've never posted something on the explore tab cuz i don't want people to just steal my code as they can copy it and paste it onto their project #So please make an option to hide the code and just run the project in the user's browser#
And make it when you clone a project it's saved in the internal editor storage 
(I know that making updates for this amazing editor is hard)

**Comment by spck-io** [comment]
This is a security issue, as you want to be able to audit other people's code when you run it. If the code is hidden then potentially malicious code (redirect to malicious websites) or mining bitcoin in background could be ran undetected.
