### ISSUE TITLE
It Lags for (1-10) secs.

### ISSUE THREAD

**Issue by adr420** [spckio/spck-issues#428]
The App is not stable , altogether , i can say , it lags too much on opening any type(.mp3,.txt,.jpg) of file larger than few KBs(say 1.4 kb) , even sometimes opening my projects , and yes it lags or just stops for 1-10 secs.

**Comment by spck-io** [comment]
Which version of the app are you using? What version of Android do you have?

**Comment by adr420** [comment]
App version -> 6.0.9 
Android Version - > 9

The app lags for 1-5 secs on opening files larger than 1kb.

**Comment by adr420** [comment]
The app works a bit faster after 6.0.9 update , but media files are taking just about 1-3s while opening ....

**Comment by spck-io** [comment]
I made some further optimizations in the upcoming release. Hope it speeds up file opening.

**Comment by adr420** [comment]
Yep! it worked thanks for your support 😊
