### ISSUE TITLE
Open files in tabs

### ISSUE THREAD

**Issue by adr420** [spckio/spck-issues#429]
May be this is a feature of this IDE to have a small file manager to "travel" between different files ,but it sucks , so PLEASE PLEASE think about it , when working on a very important project and 
** struggling with that file navigator **
 is very annoying to me PLEASE PLEASE try to have tabs like other editors , i use this IDE because its UI and completion is best among them , THIS NEW FEATURE will make it very suitable to use ...

Let's say i have opened a file and i want to go to another file which is in another folder which itself is in another folder and here, it seems to irritating 
to open that file with that file navigator above , via tabs i will just slide and there i am having my file...

**Comment by spck-io** [comment]
There is an option to quickly bookmark files using Ctrl + O. Clicking the icon to the right bookmarks the file and pins it to the top. Would this work as a tab replacement?

**Comment by spck-io** [comment]
If there is enough support for tabs based navigation (upvotes on this issue) I will implement this in the next version.

**Comment by Mak1319** [comment]
The copyright holder of the app 

I want more features like that so extract the code from the app and started devlopment of the code and I succeeded to improve something like that .

I made cool comments in code in sass_ls, css_ls, javascript_ls,

Emmet in React base javascript file


Package.json module auto complete in js file 

![Screenshot_2022-02-09-20-19-46-525_io spck](https://user-images.githubusercontent.com/78523112/153226013-16419506-82a7-4286-8c0a-936e93ac2c5c.jpg)
![Screenshot_2022-02-09-20-19-35-834_io spck](https://user-images.githubusercontent.com/78523112/153226024-9a6bfd3e-dd19-4f00-b7cc-f6a14c221b1c.jpg)
![Screenshot_2022-02-09-20-19-20-311_io spck](https://user-images.githubusercontent.com/78523112/153226034-d69d8bc0-74ec-47c3-bae7-0ef1dc7fa9db.jpg)
![Screenshot_2022-02-09-20-16-26-991_io spck](https://user-images.githubusercontent.com/78523112/153226044-27f8c6d4-e4b5-41fa-bfa3-0d48824a16b6.jpg)

**Comment by adr420** [comment]
Really Really thanks 🤩🤩 !
