### ISSUE TITLE
Failed to clone a repo

### ISSUE THREAD

**Issue by warbe-maker** [spckio/spck-issues#430]
I'm pretty sure it is my limited knowledge. I failed with an authentication error. I've entered the name of my access token in the credentials, username and mail were correct but ...
Any help would be very much appreciated. I have to confess that I've never used my generated access token so far. So there might be still something wrong with it. Sorry to bother anyone with these very basics.
Regards
Walter

**Comment by warbe-maker** [comment]
I've solved the problem by generating a new token which provided me with a way to copy it. I was unable to copy the one I had already generated. When I copied and pasted the new one generated everything worked fine. This issue may be deleted therefore.

**Comment by spck-io** [comment]
Ok, thanks for the update. There is also a documentation page about generating github tokens here: https://spckio.github.io/spck-documentation/create-app-token.html
