### ISSUE TITLE
Selection bug in word wrap "off"

### ISSUE THREAD

**Issue by panchalbhavya2210** [spckio/spck-issues#432]
https://user-images.githubusercontent.com/94476517/152192452-e037b532-a3cd-465d-954b-44e6636922ab.mp4

**Comment by PFiS1737** [comment]
I met this issue too, hope it gets fixed soon.

**Comment by spck-io** [comment]
Thanks for reporting. This issue should be fixed in the next release.

**Comment by panchalbhavya2210** [comment]
> Thanks for reporting. This issue should be fixed in the next release.

When the next update is gonna release? this bug is very annoying...
Could you fix this ASAP.

**Comment by spck-io** [comment]
Sorry, the next change involves a big refactoring with how project preferences are stored. Which is why I am doing extensive testing to make sure there are no additional bugs introduced with this change. I will release either today or tomorrow. Thanks for your patience.

**Comment by spck-io** [comment]
I have submitted the next release (6.1.0) to the play store. Awaiting the review process.

**Comment by panchalbhavya2210** [comment]
> I have submitted the next release (6.1.0) to the play store. Awaiting the review process.

Thanks a lot...
