### ISSUE TITLE
css style on React 17 (System js) Project

### ISSUE THREAD

**Issue by Onoshe** [spckio/spck-issues#433]
I created a React 17(System js) project but having difficulty in importing css file on the project. I used import "./styles.css"  on my App.js but keeps giving error on the console and won't load.

Please help

**Comment by UserOEM** [comment]
Use full path instead of  '. /some_file'

Go to your css file (or any other file you want to import) and click copy path. Paste it where needed.

**Comment by AniqueManiac** [comment]
> Use full path instead of '. /some_file'
> 
> Go to your css file (or any other file you want to import) and click copy path. Paste it where needed.

did not worked ..

**Comment by PetersonIhmes** [comment]
> Use full path instead of  '. /some_file'
> 
> Go to your css file (or any other file you want to import) and click copy path. Paste it where needed. 

It's not found

**Comment by UserOEM** [comment]
You can try this. Inside terminal 
npm i --no-bin-links --save-dev style-loader
npm  i --no-bin-links --save-dev css-loader

Then add additional rule for css inside webpack.config and try with import 

1rst rule stay the same...
 rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: ["babel-loader"]
      },

=> insert the object below (don't forget coma above) <=
      {
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader' ]
      }
    ]

At the moment it not possible to add **any** library (literally anything), only solution would be to open some older project with thosee libs already installed or to wait next release. See the issue #580. Besides,  pray to god that dev upgrade Node version...
