### ISSUE TITLE
Request For Code 

### ISSUE THREAD

**Issue by Mak1319** [spckio/spck-issues#438]
I extract your products level code and started editing this and try to make it better .

 I improved some features like 

1. file suggestions 
2.  Emmet in React base javascript file .
3. Add a theme for app 
4. Separate Editor and App theme 
5. Add support font ligature
6. Module import autocomplete from package.json in js mode 
7. File icon in filesystem 
8. A mode for .env file in js 
9. Snippet for React 
10. Custom text in font viewer 
11. Special comments in sass js css 

Look some preview:

![Screenshot_2022-02-09-20-19-35-834_io spck](https://user-images.githubusercontent.com/78523112/153229248-bac06931-d513-4541-88b5-eb344790bea6.jpg)
![Screenshot_2022-02-09-20-19-20-311_io spck](https://user-images.githubusercontent.com/78523112/153229262-fc495867-2cee-4ee0-87d3-83e7cf874b1d.jpg)
![Screenshot_2022-02-09-20-16-26-991_io spck](https://user-images.githubusercontent.com/78523112/153229274-c0db2808-36e5-42b6-833f-ea6c9f29e766.jpg)

If you don't mine 

I want the devlopment code for make it better.

My future plans:

1. Tab base file navigation
2. Autocomplete for installed modules 
3. Live sass compiler in editor (working on it) 
4. Export code minified 
5. Supports for Angular and other libraries
6. Support add custom snippet to user (working on it)
7. Individual workspace setting (working on it)
8. Intigrated postman like software to handle APIs 

Please give me the devlopment source code. I have no profit from this. I just want to make it better. I shall send you the code of my version of the code.

**Comment by spck-io** [comment]
Sorry, Spck Editor is closed source for competitive reasons.
