### ISSUE TITLE
[Feature Request] color picker with color converter

### ISSUE THREAD

**Issue by mcanam** [spckio/spck-issues#439]
please add a color converter like in vscode.

![IMG_20220214_071152](https://user-images.githubusercontent.com/67553080/153781832-873e7b09-3f88-4b89-9fa0-c663adc378e7.png)

it's simple but very helpful. because switching to another app just to convert color is not efficient. 

 thank you

**Comment by spck-io** [comment]
There is a color picker in the extra touch keyboard. Is there any particular enhancements you would like to request to this feature?
<img width="316" alt="Screen Shot 2022-02-14 at 9 26 40 PM" src="https://user-images.githubusercontent.com/42258400/153980995-8e885da2-cfe1-4e7a-ac5c-7552c428acfb.png">

**Comment by mcanam** [comment]
please add pickr interactions like hex, rgb, hsl and input

**Comment by spck-io** [comment]
Added as of 6.1.2.
