### ISSUE TITLE
annoying arrow

### ISSUE THREAD

**Issue by JasimAlrawie** [spckio/spck-issues#44]
![Screenshot_20191113213047](https://user-images.githubusercontent.com/40839702/68792708-f4ada500-065c-11ea-867a-2e5d1ac0a8ea.png)
this arrow is so annoying plz fix it 
it popup when i write anything

**Comment by spck-io** [comment]
What keyboard and android version are you using. Due to widely varying android keyboard behaviours, it may help to switch to a different keyboard. I have tested gboard, chroma keyboard and hacker keyboard on my phone (Android 6)

**Comment by spck-io** [comment]
Is anyone still having issue with this? The arrow is caused by a hidden character used in the text field as a workaround for many keyboards that do not fire a delete event in an empty textfield.

**Comment by Proxtx** [comment]
I'am using spck allot but I've never seen this but...
But I'm using Gboard

**Comment by JasimAlrawie** [comment]
> Is anyone still having issue with this? The arrow is caused by a hidden character used in the text field as a workaround for many keyboards that do not fire a delete event in an empty textfield.

im using faceEmoji keyboard and the problem still 
my android 9
i wasn't think the problem perhaps from the keyboard i'll try on my native keyboard

**Comment by JasimAlrawie** [comment]
Yeah the pronelm was from the keyboard🤔
With samsung keyboard the arrow gone

**Comment by Proxtx** [comment]
Yes your right...
I tested it with your keyboard:
![Screenshot_20191127-212951](https://user-images.githubusercontent.com/39201896/69757410-39593600-115d-11ea-9964-51d9b7ed265b.png)
