### ISSUE TITLE
Is the iOS version no longer getting updates?

### ISSUE THREAD

**Issue by KamilTheDev** [spckio/spck-issues#445]
Is the iOS version no longer getting updates? Seems there hasn't been an iOS update for over a year.

**Comment by panchalbhavya2210** [comment]
> Is the iOS version no longer getting updates? Seems there hasn't been an iOS update for over a year.

Android also not getting the update...

**Comment by spck-io** [comment]
Haven't had time to work on the iOS version, but it's in the plans for it to have a major update in the coming months.
