### ISSUE TITLE
Spck app doesn't open on latest version

### ISSUE THREAD

**Issue by jepsuCoded** [spckio/spck-issues#45]
Spck app won't open after the update. It's all white when I'm opening it then after a few seconds this shows up. Am I the only one experiencing this? I've tried reinstalling the app but still stuck in this :< I'm on Android 6.0 btw thanks!

![Screenshot_20191114_151549](https://user-images.githubusercontent.com/40726737/68847569-dc479400-0709-11ea-892c-4952dcc2b003.jpg)

**Comment by Proxtx** [comment]
Same with 
Webpage not available
The webpage at http://192.168.0.15/ could not be loaded because:

net::ERR_CLEARTEXT_NOT_PERMITTED

**Comment by Proxtx** [comment]
I think in the network of the dev he has the IP 
193.168.0.15
I think he didn't changed it bag to 127.0.0.1 or 
localhost

**Comment by jepsuCoded** [comment]
dev said Its already been fixed, we'll just wait for the update again on play store.

**Comment by Proxtx** [comment]
https://drive.google.com/file/d/1BQMLlEyrHWKP9AU4DlO1eIX1FFNYd4kI/view?usp=drivesdk

Backup File by Me

**Comment by spck-io** [comment]
Please hold off on updating the android app. It’s currently broken, but I released a working version 2.0.3 as soon as I could, but the play store has not updated yet.

**Comment by Proxtx** [comment]
Will I lost my projects?

**Comment by spck-io** [comment]
I’m not entirely sure. From the testing I’ve done on my phone Android 6, after uninstall and reinstall all my projects are lost. Although from this stackoverflow answer https://stackoverflow.com/questions/44583172/indexeddb-is-automatically-being-recovered-after-app-installation, it appears there might be saved. I have already enabled this option, but it may depend on your google account data settings. Sorry for my lack of knowledge on this...

**Comment by Proxtx** [comment]
I tested it :+1: 
My projects are still there!
Well done
