### ISSUE TITLE
Push error: Your repo is in a detached HEAD state. Please re-checkout a branch to fix this.

### ISSUE THREAD

**Issue by epsislow** [spckio/spck-issues#450]
If anyone can tell me what to do in Spck Editor with this error, thanks in advance:

Push error: Your repo is in a detached HEAD state. Please re-checkout a branch to fix this.

**Comment by spck-io** [comment]
The HEAD (pointer) showing which commit you are at is pointing to null. This can happen when you delete the active branch, as HEAD was pointing to that branch before. To fix this, go to the "Branches" dialog and checkout any of the available branches. See screenshot below:
<img width="271" alt="Screen Shot 2022-03-06 at 1 07 32 PM" src="https://user-images.githubusercontent.com/42258400/156936094-843c4854-d763-417e-8d81-bedb56fd2b0b.png">

**Comment by epsislow** [comment]
Thanks alot! 
I know how to fix it using git commands, but i didn't found out, how to checkout a branch.
Now it's clear!
