### ISSUE TITLE
Errors still don't show up when i fold a function/object 

### ISSUE THREAD

**Issue by Aplha101** [spckio/spck-issues#451]
I have to use fold feature a lot because of lengthy and messy functions but if by chance i got something missing and there's an error I can't really figure out where is the error located at ,  so it's a lot of searching through the code 

https://user-images.githubusercontent.com/76000535/156981638-8b64579b-ab62-465d-a0d7-d56da9f0ae31.mp4

It'll be really helpful if this can get fixed

**Comment by Proxtx** [comment]
I think this an ace error

**Comment by Aplha101** [comment]
> I think this an ace error
Uh whats an ace error... 😅

**Comment by Proxtx** [comment]
Spck is using ace as it's editor. Look it up on Google or GitHub

**Comment by Aplha101** [comment]
> Spck is using ace as it's editor. Look it up on Google or GitHub


Oh ok , understood

**Comment by spck-io** [comment]
There is a "Next Error" feature which kinda solves this issue, although it's not as UI friendly as directly displaying the error when folded.
<img width="370" alt="Screen Shot 2022-03-13 at 2 21 07 PM" src="https://user-images.githubusercontent.com/42258400/158073573-c2116187-7206-4f9c-8e9c-e239836d7c18.png">

**Comment by spck-io** [comment]
Improved errors and folding was added to 6.1.2. Closing this issue, thanks for the suggestions.
