### ISSUE TITLE
Issue when we type something and click on the style.css or any file it erases the " new typed code..." 

### ISSUE THREAD

**Issue by panchalbhavya2210** [spckio/spck-issues#453]
https://user-images.githubusercontent.com/94476517/158069584-eed50046-187f-4534-8c00-4903be909711.mp4

**Comment by Proxtx** [comment]
This probably happens due to not autosaving quick enough. Wait a few seconds and then click.

**Comment by panchalbhavya2210** [comment]
> This probably happens due to not autosaving quick enough. Wait a few seconds and then click.

Yup, that's what the issue was.
Thanks...
