### ISSUE TITLE
Project viewer broken

### ISSUE THREAD

**Issue by adr420** [spckio/spck-issues#462]
![Screenshot_20220325-182627_Spck Editor](https://user-images.githubusercontent.com/69690253/160223328-f19c18e2-80f3-4d3e-8719-2f41053be2e1.jpg)
![Screenshot_20220325-182633_Spck Editor](https://user-images.githubusercontent.com/69690253/160223330-2f3b13e3-c991-4c4b-a3c9-fc151f017585.jpg)

VERSION => 6.1.1
I am not able to scroll and view  my files.

**Comment by spck-io** [comment]
Yes I'm aware of this issue, this should be fixed in 6.1.2 (released yesterday). Sorry about the inconvenience.
