### ISSUE TITLE
Can't login with Github

### ISSUE THREAD

**Issue by mohsinht** [spckio/spck-issues#468]
1. I click on "Login with Github" 
2. Browser opens with Github login screen. I use my Github username and password to login. 
3. Github asks for SPCK authorization. I click on "authorize" 
4. I get redirected to an error screen on https://spck-editor.firebaseapp.com/__/auth/handler

I get the following error message:

"Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared."

**Comment by spck-io** [comment]
Please see issue #401 to see if this solves your issue.

**Comment by geomach** [comment]
Iam having trouble using connecting to GitHub please correct the issue.
