### ISSUE TITLE
Not being able to push

### ISSUE THREAD

**Issue by Aplha101** [spckio/spck-issues#471]
Never saw this error before..?
Is there any solution?

![Screenshot_2022-04-17-23-35-25-482.jpeg](https://user-images.githubusercontent.com/76000535/163726957-8e3c4bcd-7346-49be-a6d9-8d77879cd870.jpeg)

**Comment by Proxtx** [comment]
try git pull

**Comment by Aplha101** [comment]
> try git pull
> 

It says : empty response from git

**Comment by Proxtx** [comment]
try cloning the repo again

**Comment by Aplha101** [comment]
ok this worked 
create a new repo>clone into spck>add files>commit>push 

this didnt work
create a new repo>add the remote to the project in spck>commit>push
