### ISSUE TITLE
Cannot clone github repo with size 1 gb

### ISSUE THREAD

**Issue by Kikhsn** [spckio/spck-issues#475]

**Comment by ghost** [comment]
What GitHub Repo is that 😀😀

**Comment by Aplha101** [comment]
> 

Spck has only 5mb limit for files i believe

**Comment by ghost** [comment]
> > 
> 
> Spck has only 5mb limit for files i believe

Lol, have cloned a repo with the size more than 5mb.

**Comment by spck-io** [comment]
This is an issue with working memory in Android. Android only provides only ~50MB of memory per application: https://stackoverflow.com/questions/18675557/what-is-the-maximum-amount-of-ram-an-app-can-use. The git operation needs to load the entire packfile within memory in order to unzip it.
