### ISSUE TITLE
Bug on copying

### ISSUE THREAD

**Issue by CALEB789** [spckio/spck-issues#477]
It is difficult to copy and paste. When you want to copy text . The cursor moves around rapidly which is not easy to control.

**Comment by yahiaBSK** [comment]
**Same problem :(**

**Comment by spck-io** [comment]
Is this still a problem with the latest update 6.2.9?

**Comment by yahiaBSK** [comment]
> Is this still a problem with the latest update 6.2.9?

no, it's fixed perfectly.
