### ISSUE TITLE
Lagging & Crashing In Spck pro... 

### ISSUE THREAD

**Issue by panchalbhavya2210** [spckio/spck-issues#478]
https://user-images.githubusercontent.com/94476517/165139374-302ec31c-7a5a-468c-9158-79365cf7f2ea.mp4

**Comment by spck-io** [comment]
Sorry, it seems the latest update to switch to native scrolling (prerendering the entire file) was causing this issue. I'm very sorry for this change as testing on emulator is not entirely the same as testing on a device.
