### ISSUE TITLE
Touch issue

### ISSUE THREAD

**Issue by JasimAlrawie** [spckio/spck-issues#48]
Sometimes the app doesn't respond for touches
When i close the app and reopen it the last opened file doesn't respond the touches. I should switch to other file and then back to the same file to avoid the problem

**Comment by JasimAlrawie** [comment]
Watch this http://imgur.com/a/hAOpBCR

**Comment by Proxtx** [comment]
If you touch the arrow button (right-bottom) and touch anywhere you will be able to write!

**Comment by JasimAlrawie** [comment]
yeah this work but you should fix it🤔

**Comment by spck-io** [comment]
I will take a look. Thank you both for providing additional details on this bug, it really helps.

**Comment by spck-io** [comment]
Found the issue, still looking for a fix. The webview does not come into focus until clicked upon even though it is on top. There is no way in JavaScript to make the window come into focus, will do more testing to see if there’s a work around. Clicking on the editor prevents the event from bubbling up to the window, maybe this behaviour needs to change.

**Comment by Proxtx** [comment]
Hey simple solution: just extend the Navigation bar on load of the app. The user I will click next to it to minimize it the editor would be fully functional then

**Comment by JasimAlrawie** [comment]
is your app based on webview 😃??

**Comment by Proxtx** [comment]
Yes of course: Didn't you noticed the trouble about the Local Storage implementation and the [Spck.io](spck.io) website?

**Comment by JasimAlrawie** [comment]
nope
