### ISSUE TITLE
The new update's selection is too much

### ISSUE THREAD

**Issue by fbn776** [spckio/spck-issues#480]
Just say you were moving the cursor to a specific position, and you accidentally touch a place near the place you wanted to move the cursor to, so now you move the cursor again to the specified position, but now by doing so, it selects the text. It's a pain, it slows down the work flow. I think this is a new feature in the latest update.

**Comment by ghost** [comment]
> Just say you were moving the cursor to a specific position, and you accidentally touch a place near the place you wanted to move the cursor to, so now you move the cursor again to the specified position, but now by doing so, it selects the text. It's a pain, it slows down the work flow. I think this is a new feature in the latest update.


Yeah probably too sensitive to anything selective

**Comment by fbn776** [comment]
Yep. It's too sensitive.

**Comment by sonivraj82** [comment]
Yes and In my device it flicers a lot while copying something and it is just so hard to copy 

Does any one faces the same issue???

**Comment by fbn776** [comment]
I think it's your device.. 
Try reinstalling the app, it might fix it.

**Comment by spck-io** [comment]
I will look into this issue, are you clicking near the same spot very fast? It would help a lot with some kind of screen recording so I can see exactly the actions being performed in the editor. I think it may be due to the doubleclick to select feature that was requested another another user. Sorry about this, will try to fix this in the next update.

**Comment by spck-io** [comment]
Is this still an issue in the latest release 6.2.9? Or if you experience other problems in the recent update? Thanks.

**Comment by ghost** [comment]
> Is this still an issue in the latest release 6.2.9? Or if you experience other problems in the recent update? Thanks.

Fixed, I guess 😊🎉

Happy Coding );

**Comment by sonivraj82** [comment]
> I think it's your device.. 
> Try reinstalling the app, it might fix it.

Yes I did that it worked
