### ISSUE TITLE
Your attitude towards deleting account is immoral and does not work

### ISSUE THREAD

**Issue by yasircoskun** [spckio/spck-issues#484]
Your attitude towards deleting account is immoral and does not work

its immoral (not ethical) because confirmation text is too long and not copyable.

![Screenshot_2022-05-10-19-11-12-353_io.spck.jpg](https://user-images.githubusercontent.com/83482221/167674206-c1f4847c-a41a-4c39-9820-edb8aa7166cf.jpg)

i mad and wrote this shit to textbox.

![Screenshot_2022-05-10-19-17-29-162_io.spck.jpg](https://user-images.githubusercontent.com/83482221/167675382-9d79543e-259d-4f34-894f-f8fbd6d20c57.jpg)

But...

![Screenshot_2022-05-10-19-17-55-129_io.spck.jpg](https://user-images.githubusercontent.com/83482221/167675470-a62e871a-7f34-4857-9815-774310e6a8cb.jpg)

**Comment by spck-io** [comment]
I will look into this issue for the next update. Send me an email regarding with the email that you want to be deleted from the system.
