### ISSUE TITLE
Importing zip files

### ISSUE THREAD

**Issue by JasimAlrawie** [spckio/spck-issues#49]
Sometimes when i import zip file the app won't extract all files. theres always shortfalls

**Comment by spck-io** [comment]
Can you provide a sample zip file of when this happens? Are you using editor version 0.7.2 (found in the settings tab), I have recently fixed a sub folders bug with this. Also how are you generating the zip file? Maybe there could be a particular bug in the zip library the editor is using.

**Comment by JasimAlrawie** [comment]
im generating the zip with your app :)

**Comment by spck-io** [comment]
What file formats are in your project?

**Comment by JasimAlrawie** [comment]
its index.html, p5.js, script.js, style.css

**Comment by Proxtx** [comment]
I tested it with an ZIP file wich didn't worked in the past: 
It worked
v0.7.2

**Comment by spck-io** [comment]
The only issue with zip imports that I’m currently aware of is if the zip file is encoded with any encoding other than UTF8. Please reopen if you encounter any other problems with zip imports not related to encoding and attach a copy of the zip file to help replicate the issue.

**Comment by Cheatcodeswin** [comment]
I'm trying to export my project but it keeps saying error when it gets to 17 file I erased apps and I have about 4gs free why is this?
