### ISSUE TITLE
COPY & CUT TEXT PROBLEM

### ISSUE THREAD

**Issue by yahiaBSK** [spckio/spck-issues#491]
**When i want to cut or copy text(code) inside the app i just can't, when i clicked the button of copy or cut, the cursor just left the text that i selected, and the the container of copy and cut disappeared at all. 
i hope you fix it soon as possible, Thanks.**
- this problem happening in both of your app (pro & normal).

**Comment by julianze** [comment]
Same here

**Comment by spck-io** [comment]
Thanks for the bug report. I will look into this problem ASAP.

**Comment by yahiaBSK** [comment]
**_Good support, problem fixed perfectly._**
