### ISSUE TITLE
Blank Screen Problem

### ISSUE THREAD

**Issue by knightwor** [spckio/spck-issues#492]
When i am writing code than 99.99% time my editor screen disappeared and i can't see my code

Please solve this problem..

**Comment by ternenges** [comment]
Lol, spck editor has grow from a simple easy to use code editor to an app full of bugs on every update.

**Comment by spck-io** [comment]
Can you please post a screenshot or video of the problem? Sorry for any inconvience.

**Comment by knightwor** [comment]
I have no problem right now because the blank screen problem fixed. Today
when doing coding in spck code editor than i see the blank screen problem
fixed.

गुरु, 26 मई 2022, 5:45 am को spck-io ***@***.***> ने लिखा:
