### ISSUE TITLE
Too buggy with larger files

### ISSUE THREAD

**Issue by Nashnish** [spckio/spck-issues#498]
Text not even show when scrolling, it's too slow and text not showing in the editor. It's almost impossible to do anything with larger files. Screen freezes and showing not responding message. Disable and fancy things like animations but nothing works.

It's unfortunate that this great editor has performance issues.

![Screenshot_20220528-025231_Spck Editor](https://user-images.githubusercontent.com/104837160/170764751-13a3f458-b75d-485c-b816-80b4bb676e15.jpg)

![Screenshot_20220528-024649_Spck Editor](https://user-images.githubusercontent.com/104837160/170763984-45a45dd3-a043-42a0-98e0-7fd6c367f818.jpg)

**Comment by spck-io** [comment]
Which version of the editor are you using? Let me know if you still have this issue in v6.2.7.
