### ISSUE TITLE
Vertical scroll not working (wrap)

### ISSUE THREAD

**Issue by Phoxett** [spckio/spck-issues#499]
I just updated the app, now that code is beyond the screen width, I can't see the code. When I type ' , ' (comma), it since to hide the code so some reason. I have to use word wrap to see the rest of the code.

**Comment by spck-io** [comment]
Which version of the app are you currently experiencing this problem with?

**Comment by Phoxett** [comment]
I facing the problem in the latest version (6.2.6)

**Comment by spck-io** [comment]
Is this the same issue as #496? This has been fixed in the latest update.
