### ISSUE TITLE
Beta features

### ISSUE THREAD

**Issue by Proxtx** [spckio/spck-issues#50]
I just want to know if there are any beta features because on the Play Store there is an beta but I didn't found any changes!

**Comment by spck-io** [comment]
They are on the same release track. I do not have enough beta testers to publish a separate beta release yet.

**Comment by Proxtx** [comment]
Will the BETA-version like the normal one or will it be older?

**Comment by spck-io** [comment]
I think the current beta release is a lot older than the production track.
