### ISSUE TITLE
Shortcuts not have same functionality as before

### ISSUE THREAD

**Issue by UserOEM** [spckio/spck-issues#503]
From 2.0.2 till 2.0.7 including the last one all have the same problem with shortcuts functionality and lag. 

![control.jpg](https://user-images.githubusercontent.com/84070129/170862367-8a6ee7e4-724f-419a-9b76-0be69033dc4e.jpg)

I extensively use control shortcut(pic above) to:
- comment  "control  /"  or  "control  ." 
- copy/paste "control c" and "control v" (also dont work when control key is on)  

Also, shortcut "log TAB" for console.log()  don't work anymore. 

Some additional things, movement is so sensitive and extra keyboard tab is always visible even its off in settings. I'm using Spck Pro 2.0.2 at the moment, in my opinion it's the only stable version and the fastest. I got so used to toggle comment (on/off) and "log TAB" that I can't use any other version except 2.0.2...second important thing is lag which is visible on larger projects.

I also want to say, that this is the best ever app for Android. I'm so thankful for the developer for building this app. Keep up with good work!

**Comment by adr420** [comment]
For me too

**Comment by spck-io** [comment]
Can you describe which movement is sensitive so I can look into it? Do you mean by the selection of text out of screen triggering autoscrolls is too sensitive, or touch scrolling has become too sensitive?

Can you clarify what is "log TAB", I apologize as I'm not familiar with this functionality. I have fixed an issue with text selection in the recent 6.2.9 version and I will look into the shortcut issues.

I have also fixed the "Extra Keyboard" and "Touch Keyboard" settings not working in the upcoming version.

Thanks for your help in advance and for reporting these issues, I will work on them ASAP.

**Comment by adr420** [comment]
CTRL or CMD button is not working for me , whenever i press CMD+[anykey] it just writes the text in [anykey].

Like CMD + s writes 's' to the buffer.

**Comment by UserOEM** [comment]
Thank you for quick response! 

I'm sorry that I can't give you an accurate answer specifically only about the last version because I'm using 2.0.2. even though I have tested it. Usually, when I see that I can't use shortcuts or is lagging, I just skip the version. I was thinking from 2.0.2 to 2.2.9 in general. Maybe you already fixed some things that I'm going to write below... I'm too long on 2.0.2😁

- selection of large chunk of code and (touch) scrolling while the code is selected is sensitive
- overall scrolling is sensitive
- selecting isn't precise,  (e. g.  I want to grab code from line 25 to 175, it's difficult to grab exactly till and the line 175 and while I'm selecting the code, movement is too sensitive so I can easily grab the whole code below - it isn't smooth, I can't stop on line I want to) 

It's my mistake that I didn't explain in detail.  e. g. I would like not to type manually every single time "console. log()", rather just to type as before "log" and press TAB on keyboard. I think that have to do with Emmet in newer versions. Before, when I type "log"  I see text "log snippet" and I press TAB to get "console. log()"... also in one version in between I have found that - I can type "log" (there is no more log snippet, it's something else) but then I press "space" then "back" and then TAB and I have "console. log()"😅. It isn't nice experience at all, but it's way better not to write it manually😁

My settings:
Bot autocomplite trigger - on input 
Keybindings - VSCode

With everything I’ve written so far I totally forgot to mention a big issue for me and why I have downgraded:
-  I'm using React, and unfortunately, very very often when I press run - app freeze, there is no output, I can return back but then every time it's the same. The only solution is to force stop the app in the settings. Quick fix, toogle in Android settings so that back key force any app to determine and when app freez just determine it with back key and start it again...this solution is good for now because I can do it very quickly. 
- overall movement, touch scrolling, selecting, switching folders, copying/pasting - there is so much lag in newer versions. I just can't concentrate on writing the code (the way I'm using the app, usually half of the screen is video player - some tutorial or documentation and other half of it is Spck Pro). 
- shortcuts that I already mentioned (I can't code fast enough without the shortcuts, it's also very strenuous when I need to manually type e.g. "console.log()" who knows how many times or to toggle comments...) 


Thank you in advance, I appreciate your time!

**Comment by spck-io** [comment]
> CTRL or CMD button is not working for me , whenever i press CMD+[anykey] it just writes the text in [anykey].
> 
> Like CMD + s writes 's' to the buffer.

I'm having trouble replicating this on emulator. What version are you on, also is this a problem with using a physical keyboard? Thanks.

**Comment by spck-io** [comment]
@UserOEM 

I'm having trouble replicating the "log" problem. The log snippet is showing correctly when I type "log" in the latest 2.2.9.

On emulator the selection seems to work... hard to determine what you're seeing on your device without some kind of screen recording (would help greatly).

I'm not sure if the lag has been fixed in the latest 2.2.9, but some other users have reported that the lag issues have been resolved in the last few updates.

I'm not sure if the freezing you describe is a result of memory limitations on Android. I will try to get a physical device to test with.

**Comment by Aplha101** [comment]
> @UserOEM 
> 
> I'm having trouble replicating the "log" problem. The log snippet is showing correctly when I type "log" in the latest 2.2.9.
> 
> On emulator the selection seems to work... hard to determine what you're seeing on your device without some kind of screen recording (would help greatly).
> 
> I'm not sure if the lag has been fixed in the latest 2.2.9, but some other users have reported that the lag issues have been resolved in the last few updates.
> 
> I'm not sure if the freezing you describe is a result of memory limitations on Android. I will try to get a physical device to test with.

I'm also experiencing the same , using ctrl + c replaces the selected text with "c" instead of copying it

I don't really use the ctrl button that often but , here's a recoding what @UserOEM might be experiencing

https://user-images.githubusercontent.com/76000535/171781615-57a89e3a-c809-40d4-93e0-674f1374307f.mp4

**Comment by spck-io** [comment]
What keyboard are you using in the video? Just curious, does this happen with Gboard?

**Comment by adr420** [comment]
This same happens with me too, i am using Gboard.

**Comment by UserOEM** [comment]
I'm using dcoder keyboard, didn't test on others because it's my primary keyboard for coding. Also, it would be nice to add outdent key beside indent in action bar and same applies for uppercase 'CMD + u' - to lowercase shortcut is missing e.g. 'CMD + l' . I don't know about Android limitations, but I have 6GB of memory.

**Comment by Aplha101** [comment]
> What keyboard are you using in the video? Just curious, does this happen with Gboard?

Yup it's Gboard

**Comment by spck-io** [comment]
I finally figured out the source of the problem and am able to replicate it. Working on a fix, it has to do with the Keybinding setting set to VSCode.

**Comment by spck-io** [comment]
This has to do with setting the Keybinding to VSCode, prior to version 6.2.x, I believe that setting did nothing due to another bug. After fixing this to apply some VSCode shortcuts, there is a bug with how other shortcuts are handled.

**Comment by UserOEM** [comment]
@spck-io
I have made short video so you can see some things that I have mentioned. I can't upload it on GitHub via Android.

https://ufile.io/ib369s82
