### ISSUE TITLE
Unable to delete an account connected to Google

### ISSUE THREAD

**Issue by codingtuto** [spckio/spck-issues#508]
**I tested a lot of times to delete my account to link it to my github account but it's impossible! Why**

**Comment by ghost** [comment]
> **I tested a lot of times to delete my account to link it to my github account but it's impossible! Why**

The case is simple

I guess there's issue with Authenticating with the GitHub OAuth on SPCK Editor, so I'll probably advice to continue to use Google OAuth.

Buh if you want revoke the access here are the steps to take if the account doesn't get deleted on SPCK:

- ![Screenshot_20220604-165024.png](https://user-images.githubusercontent.com/58574822/172013704-f137429d-f26e-4ab6-98db-1b22cdbf82b0.png)

Go to your Phone settings and click Google it will show that ↑ and Click Manage Your Account it will take you to your Account.

- ![Screenshot_20220604-165101.png](https://user-images.githubusercontent.com/58574822/172013776-4a570528-0932-49b1-9d41-d6637476f243.png)

Then click the Search Icon and type **third party** it will automatically show the the suggestion, click the first one and scroll downward, You'll see all the Authenticated Apps you can revoke the access from there 😊.

Like this:
![Screenshot_20220604-165142.png](https://user-images.githubusercontent.com/58574822/172013839-caf4dd56-4a05-4f0f-aa31-49998ac93fc5.png)

Happy Coding 🎊🎊🎊🚀:-)

**Comment by JamriHossen** [comment]
![Screenshot_2022-07-19-22-39-25-918_io spck editor node](https://user-images.githubusercontent.com/91720435/179806522-89200bdb-62d3-44e5-9889-4a21dd1f7a0f.jpg)

I don't know if this problem is similar with that report. but I'm not able to continue with my this account. even I have never deleted my account but it's showing ," your account is being deleted. try 72 hours later."

**Comment by codingtuto** [comment]
fix the account deletion problem it must be automatic but each time an error...
