### ISSUE TITLE
Add prettier - code formatter

### ISSUE THREAD

**Issue by Proxtx** [spckio/spck-issues#51]
[Prettier](https://prettier.io/) 
Prettier is available for a lot of popular code editors:
VS code, VS, Atom, Webstorm and a lot more.
I don't think it will be hard to implement!🤔
👍😁

**Comment by spck-io** [comment]
There is already an unopinionated code formatter called indent.js that can be accessed in the plus icon menu of the quick keyboard, but if you prefer to use prettier, I can add this as an alternative opinionated formatter that can be changed in the settings.

**Comment by Proxtx** [comment]
I already discovered this tool but it is a little but it is not working very good:
`function createBlocks (width, height){
  for(var i = 0;i<Math.floor(fieldWidth/width);i++){
    blocksArray.push([]);
    for(var z = 0;z<Math.floor(fieldHeight/height);z++){
      blocksArray[i].push({color: "#000000"});
    }
    }
    }
    
    function loadBlocks (width, height){
      for(var i = 0;i<blocksArray.length;i++){
        for(var z = 0;z<blocksArray[i].length;z++){
          if(blocksArray[i][z].color){
            ctx.fillStyle=blocksArray[i][z].color;
          }
          ctx.fillRect(i*width, z*height, width, height);
        }
        }
        }
        initCanvas();
        createBlocks(blockWidth, blockHeight);
        genApple();
        loadBlocks(blockWidth, blockHeight);
        
        
        
        //Game
        
        function updateSnake (){`


For no reason in insert tabs to the code.

**Comment by Proxtx** [comment]
I think nobody is actively developing indent.js(look at the dates)
![Screenshot_20191204-163346](https://user-images.githubusercontent.com/39201896/70156336-0f02fd80-16b4-11ea-9261-996355d37189.png)

**Comment by spck-io** [comment]
Ok, I can switch it. I am the developer for indent.js and there has been no bug reports on the repo. Just wondering if prettier can be configured to not put each element of an array on a new line? I find it super annoying when code prettifiers add a whole bunch of new lines to my code, but maybe that’s just me...

**Comment by Proxtx** [comment]
Maby you just add an option to the settings to choice which prettifier to use.

**Comment by Proxtx** [comment]
[prettest.zip](https://github.com/spckio/spck-issues/files/3922824/prettest.zip)
Here is an test script by me (edit code.txt and run script)
A great think I like of prettier is the `semi: true` option Wich adds semicolons.

**Comment by spck-io** [comment]
I looked into prettier and I’m shocked that the standalone bundle is over 30000 lines of code. Even when gzipped it still is a huge file, not to mention parsing through so much JavaScript will further slow down the editor load time. I’m going to switch to jsbeautifier, alternately I can refractor the formatter into a webworker, which hopefully shouldn’t bog down the editor start up time.

**Comment by Proxtx** [comment]
Ok... I'm really looking forward to it!
