### ISSUE TITLE
Can’t login to any service on iOS 12.5.5

### ISSUE THREAD

**Issue by luni-moon** [spckio/spck-issues#511]
I can’t use any of the login buttons, after running the command `cmd + R` on my iPad through the app, which means I cannot login to use the run feature. I am running iOS 12.5.5 on an iPad Air (4,1) (iPad Air 1st Generation). I would love to see this fixed, whilst still being able to update the app (on my device), after it is fixed! Thank you so much!

**Comment by luni-moon** [comment]
Is this project dead? I have had this issue open for a while now, with no response!

**Comment by Proxtx** [comment]
the project isn't dead but the IOS version isn't very well maintained
