### ISSUE TITLE
All projects disappeared on reinstalling

### ISSUE THREAD

**Issue by SytherPlayZ** [spckio/spck-issues#513]
I recently accidentally deleted spck editor and now my all projects disappeared. is there a way to bring those back again?

**Comment by UserOEM** [comment]
I don't believe is possible anymore, maybe with some data recovery app. Quote from app description: "*Back up your projects before uninstalling the app, otherwise you will likely lose the data! Upgrading/updating the app should be okay."

**Comment by Aplha101** [comment]
> I recently accidentally deleted spck editor and now my all projects disappeared. is there a way to bring those back again?

Maybe #350 can help

**Comment by SytherPlayZ** [comment]
> 

There's no com.io.spck folder in Internal Storage>Android>data. Is there any recovery app or anything?

**Comment by Aplha101** [comment]
> > 
> 
> There's no com.io.spck folder in Internal Storage>Android>data. Is there any recovery app or anything?
> 

If you have some projects on git you can clone them back ig

**Comment by UserOEM** [comment]
@SytherPlayZ 

/storage/emulated/0/Android/data/io.spck.editor.node
