### ISSUE TITLE
Disappointment when using fetch

### ISSUE THREAD

**Issue by F4Jonatas** [spckio/spck-issues#518]
Every time I load a file, I don't know why, a script tag is added with eruda.
This slows down the whole process unnecessarily.

Response text:
![Screenshot_20220703-123821029](https://user-images.githubusercontent.com/12034399/177046863-0d42d7b6-000b-4de4-a9c2-db9b446f83ee.jpg)

Real File:
![Screenshot_20220703-123914460](https://user-images.githubusercontent.com/12034399/177046888-ea762497-dcf7-4177-aa1e-788167c31806.jpg)

**Comment by spck-io** [comment]
Eruda is the console that you are showing in the screenshot. If you turn off the console feature, or if you go to settings and switch "Console" to "Legacy" it will not load Eruda.
