### ISSUE TITLE
PLS Fix!!!

### ISSUE THREAD

**Issue by Proxtx** [spckio/spck-issues#52]
![Screenshot_20191202-184818](https://user-images.githubusercontent.com/39201896/69982304-68442300-1534-11ea-8a35-a13cc25ac727.png)
This `i` is triggering!!
PLS add a `;`.
Every time you start a new project it will appear in the main.js Wich is generated.
But it's a cool feature (pls add also a style.css automatically)

**Comment by spck-io** [comment]
Ok thank you, I will fix that in the upcoming release.
