### ISSUE TITLE
GitHub login error , Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared.

### ISSUE THREAD

**Issue by codrhyme** [spckio/spck-issues#528]

**Comment by Proxtx** [comment]
Check the other issues for this. Try uninstalling the GitHub app.

**Comment by opiation** [comment]
> Check the other issues for this. Try uninstalling the GitHub app.

I'm not sure what the GitHub app has to do with the Spck app. The GitHub sign-in flow redirects to a browser link to GitHub. I've tried opening the redirect with Google Chrome for Android, Brave Browser and Firefox. All of them yield the same error.

```
Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared.
```

Uninstalling and reinstalling the GitHub Android app also yielded the same results.

While I don't have the full network error from GitHub's auth flow or Spck client, the mention of missing initial state suggests that Spck is not storing the OAuth 2.0 _state_ sent along with the initial auth request so it cannot validate if GitHub's auth response includes the correct _state_. Testing the OAuth flow from Spck to GitHub would confirm or rule out this guess though I can't do this myself at the moment. I hope this helps someone else debug it however.

**Comment by Proxtx** [comment]
No don't reinstall the GitHub app. Just uninstall it. Remove it from your device.

**Comment by opiation** [comment]
> No don't reinstall the GitHub app. Just uninstall it. Remove it from your device.

That did work. This does mean however that if Spck signs out (like the token expiring or manual sign out), we have to uninstall the GitHub app again, sign in, then reinstall the GitHub app. After reinstalling the GitHub app and signing in to it again, signing back into GitHub through Spck fails again. Not the _ideal_ solution.

**Comment by Proxtx** [comment]
There is no obvious way around that. The following happens in the background: Spck Creates a special URL / Request and registers it. Now Spck needs you to open the URL in your Browser to authorize yourself (login into GitHub, 2FA etc.). Spck tries to open the special authorisation URL. Now this is where things go wrong: The GitHub app tries to open all URLs starting with GitHub.com. Therefore Spck's special GitHub auth URL gets redirected to the GitHub app. The app realizes that it can't handle the authorisation URL and continues to redirect the browser. Unfortunately the app also removed the Initial State.

**Comment by opiation** [comment]
Right, thanks for sharing the explanation! That definitely clarifies the intersection of interests here.

I've never filed an issue with GitHub's mobile/Android app. I don't have the time to figure out how to get a bug report to them at the moment so I'll live with uninstalling the GitHub app in the meantime. Thanks for your time.
