### ISSUE TITLE
Not exactly an issue 

### ISSUE THREAD

**Issue by Aplha101** [spckio/spck-issues#533]
This isn't an issue but the readme says there will be a separate repo or something like that to suggest / ask and other stuff but I don't find it or it hasn't been created ( ik the Dev's are busy) but  here's the thing ( request ) 

It's been like a month or so without any updates and i wanna know what are / can be the long term plans for spck

**Comment by UserOEM** [comment]
Good question. I would like that also to know. It would be nice to upgrade Node, also React 17 + Hot-Reloader isn't working - webpack-cli need to update to version 4.10.0. If you can, please prevent folder collapsing on every file import in next release.
