### ISSUE TITLE
No terminal on paid account

### ISSUE THREAD

**Issue by zoollerman** [spckio/spck-issues#542]
I have paid basic account. But I cant use terminal. Only with timer to 60 min dayli. Basic account isnt enough? Thanks.

**Comment by UserOEM** [comment]
Hi @zoollerman. Basic account is free but with limitations 1 hour/day Terminal.

**Comment by zoollerman** [comment]
Sorry, I thought my account was not free, as I pay a monthly fee. GPA.3373-4089-9513-81532..3. I received thisD order number from Google for the last monthly payment. So you just deduct the monthly fee and I get nothing for it? Please investigate.

**Comment by UserOEM** [comment]
Hi @zoollerman. I'm just a regular user as you, not admin/dev. What I can say for sure, that payment is working as is should. If you want more quicker respond, join Spck discord channel. [Join Here](https://discord.gg/zzgSTq43)

**Comment by spck-io** [comment]
Thanks for the bug report. I have handled your issue, closing this now. Let me know by email if you're still having problems.
