### ISSUE TITLE
Add GitHub Dark Theme

### ISSUE THREAD

**Issue by Neodevils** [spckio/spck-issues#551]
GitHub Dark Theme for editor would be amazing. Literally, amazing.

**Comment by Neodevils** [comment]
@spck-io may you check it?

**Comment by Neodevils** [comment]
@spck-io hello?

**Comment by spck-io** [comment]
Thanks for the feature request. This has been added in the latest release 7.0.4.

**Comment by Neodevils** [comment]
> Thanks for the feature request. This has been added in the latest release 7.0.4.

Where can I download latest version? I don't see it on beta version of the app.
