### ISSUE TITLE
Spck.io : adding repo error

### ISSUE THREAD

**Issue by n-ce** [spckio/spck-issues#552]
![Screenshot_20221008-182841_Chrome](https://user-images.githubusercontent.com/69345507/194708779-3b19a6bc-d2ca-41aa-83ee-0546321389b3.jpg)

**Comment by spck-io** [comment]
This is a security issue as browsers do not allow CORS request if the origin does not specify cross-origin headers. All major Git providers (Github, etc.) do not allow CORS. You can use the browser version by disabling CORS via a flag when launching Chrome as a workaround.
