### ISSUE TITLE
Bad automatic formatting for syntax generator function

### ISSUE THREAD

**Issue by ronaldo-bguimaraes** [spckio/spck-issues#560]
Apparently the generator function syntax is not well supported in class method declarations.

![Screenshot_20221117-121413~2.png](https://user-images.githubusercontent.com/65988366/202499134-51bed778-0031-49fc-a3d0-30a7543158fc.png)

**Comment by spck-io** [comment]
Thanks for the bug report. This is an issue with the underlying js-beautify library which is the formatter for this editor. Please raise an issue there, thanks.
