### ISSUE TITLE
Github sign in is broken 

### ISSUE THREAD

**Issue by ramarivera** [spckio/spck-issues#561]
![Screenshot_20221118_103947_Chrome.jpg](https://user-images.githubusercontent.com/7547875/202670757-498e7d40-af04-4ff7-b597-875bec5bdfe4.jpg)

**Comment by Aplha101** [comment]
#401

**Comment by spck-io** [comment]
Thanks for responding to this. This is a firebase issue/Oauth protocol issue on Android, it's beyond my control.
