### ISSUE TITLE
Allow spell check on mobile to auto correct

### ISSUE THREAD

**Issue by Wyko** [spckio/spck-issues#564]
If I change the IDE to text mode, I would like the mobile autocorrect feature to actually correct my spelling. I use this platform to write stories and back them up via GitHub, and the fact that autocorrect is disabled makes editing everything difficult.

**Comment by spck-io** [comment]
In the latest release there is a "Edit Text" in the file menu icon for .txt files, and also a "Text" icon for .txt files. Clicking this will switch the editor to use a simple textbox for editing, this will have autocorrect and default editing behavior.
