### ISSUE TITLE
Blurry editor and fonts not loading after update

### ISSUE THREAD

**Issue by Khaled-The-Dev** [spckio/spck-issues#566]
After the new update the editor font became blurry and hurts my eyes the menus and everything else is fine only the editor I tried changing the font but the fonts won't load

**Comment by deejinng** [comment]
If I'm to be honest

The recent update is something else entirely 😅😅😅

**Comment by spck-io** [comment]
Is this still an issue with the latest release? Can you attach a screenshot? I think this has to do with turning on antialiasing for fonts. If this is still an issue I will turn it off in the next update.

**Comment by Khaled-The-Dev** [comment]
> Is this still an issue with the latest release? Can you attach a screenshot? I think this has to do with turning on antialiasing for fonts. If this is still an issue I will turn it off in the next update.

No the update fixed it. Sry for being late
