### ISSUE TITLE
I can't use the editor

### ISSUE THREAD

**Issue by Khaled-The-Dev** [spckio/spck-issues#567]
It seems like that the editor is broken
I can only delete code and can't write any

**Comment by spck-io** [comment]
Is this still an issue with the latest release? can you attach a video of what's happening? Thanks.

**Comment by Khaled-The-Dev** [comment]
> Is this still an issue with the latest release? can you attach a video of what's happening? Thanks.

The update fixed the issue thanks. Best editor ever
