### ISSUE TITLE
The account has been deleted for more than 3 months, and even when I try to log in with Git, it says an error

### ISSUE THREAD

**Issue by fifia07** [spckio/spck-issues#568]
![Screenshot_2022-12-13-11-54-41-300_io.spck.jpg](https://user-images.githubusercontent.com/101568075/207259134-0132eb84-339e-4ac6-bf1b-4f55c746b78f.jpg)

**Comment by spck-io** [comment]
Thanks for the bug report. I will look into it.

**Comment by halt-spesn** [comment]
i have the same issue, any fixes for this?
