### ISSUE TITLE
Add Library doesn't work!

### ISSUE THREAD

**Issue by deejinng** [spckio/spck-issues#578]
When we click on Add Library files doesn't get Downloaded anymore 

Is the issue with CDNjs API or what ??

**Comment by K79SN4** [comment]
Detected similar issues on both App and [Web](https://spck.io).

+ Issues: 
  1. Workspace>Projects>Files>`Add Library` option doesn't create `cdn_modules` folder or download files for existing modules folder. `Download Missing Files` option in existing or manually created modules folder works. 
  2. Workspace>Create project>`Clone` option for public github repository seems broke too(404 error). I haven't checked the same for private repo.
+ Version: 7.0.4
+ System : latest Spck-editor/Webview/Chrome/Brave on Android 12
+ Similar report : 
  1. #580

**Comment by deejinng** [comment]
And I and a friend just created the kind of feature in an app called Acode 😅
