### ISSUE TITLE
File Loose

### ISSUE THREAD

**Issue by Renzy20** [spckio/spck-issues#582]
Hi, I have a issue that all my files that made 11 days ago on SPCK Editor. All the html and css files was lost. I dont know what happen. All the prototype of my project was lost.

**Comment by spck-io** [comment]
Check if the project is under Internal/External or SD card Storage options. Other than that, some Android systems seems to wipe data randomly or according to some security features (failed lockscreen password attempts for example). What is the exact phone model and OS that you are using.
