### ISSUE TITLE
onclick event not working why?

### ISSUE THREAD

**Issue by zishan0786** [spckio/spck-issues#594]
My code ----

<button onclick="click()" id="btn">click</button>

<script>
function click() {
 
    alert('zishan')
  
}

</script>

**Comment by Aplha101** [comment]
> My code ----
> 
> click
> 
> <script> function click() { alert('zishan') } </script>

This is not an issue related to the app ...

**Comment by zishan0786** [comment]
How can i resolve this

**Comment by Aplha101** [comment]
> How can i resolve this

Use an event listener...
