### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by M2H0-ST33Z** [spckio/spck-issues#597]
Unable to login as this keeps happening . I have struggling to login to SPCK with Github then I clicked sign in with Google then deleted the account and tried signing in with Github. It's not letting me login. 
![Screenshot_20230205_164306_Chrome](https://user-images.githubusercontent.com/124494611/216826326-a7efbee3-e937-414c-8d17-13dc165c055d.jpg)

**Comment by Aplha101** [comment]
#401 😊
