### ISSUE TITLE
Change Font

### ISSUE THREAD

**Issue by Proxtx** [spckio/spck-issues#60]
In the settings there is only an Font-Size option.
Woul it be possible to add an Font option to change the Font?

**Comment by spck-io** [comment]
Fonts are really expensive in terms of sizing. Bundling a few fonts will take a couple MB. The chosen font for the editor is a monospaced font that supports all character sets including Chinese/Japanese/korean which requires a separate character for each word... I would only consider this if the user uploads their own font.

**Comment by Proxtx** [comment]
Yes this would be an good solution
