### ISSUE TITLE
Log in issue

### ISSUE THREAD

**Issue by MmolayiNN** [spckio/spck-issues#600]
![B2360738-763E-4768-885B-B7799B8F874A](https://user-images.githubusercontent.com/117799614/218333271-b7d5a2f1-137a-49e4-8e0d-f5d121c00aae.png)
I can’t find the profile icon, I wanted to log in with my account

**Comment by tshegoPM** [comment]
I also can’t find the profile icon to log into

**Comment by spck-io** [comment]
The iOS version of the app is very outdated, hoping to update it soon, but having some trouble passing the App Review process due to a 3rd party library issue.
