### ISSUE TITLE
Cloning repo fails because it contains symlinks

### ISSUE THREAD

**Issue by oplatek** [spckio/spck-issues#602]
Hi,

I found Spck Editor very useful for writing articles in LaTex which I version in git.
I also do a lot of experiment setups in easy Python and Bash scripts.

Often I have committed symlinks in the repo. I do not need them when I am “coding”/writing in Spck Editor on iPad but at the moment they prevent cloning the repositories which contain the symlinks.

If I try to clone a repository with a symlink I got `Create Project Failed` error. See the screenshots.
I think that a nice workaround would be if Spck Editor could detect if there are symlinks and not create them if it is problematic to create Symlinks on iPadOS.
From a Git point of view, the code could simply remove the symlinks and add them back before committing.

**Comment by spck-io** [comment]
This would be available in the next update for iOS. Unfortunately, the app has been rejected by the App Store review process several times now due to some failure with the subscription system.
