### ISSUE TITLE
Android 7.0 + ?? Why?

### ISSUE THREAD

**Issue by Doublepicebs** [spckio/spck-issues#61]
Why is the editing single files in the internal storage need Android 7.0+ ? All apps can access storage especially 5.0+ not 7.0+

**Comment by spck-io** [comment]
file:// scheme registration was deprecated in android 7.0. The file:// intent no longer works in android 7+. Read about it here: https://proandroiddev.com/sharing-files-though-intents-are-you-ready-for-nougat-70f7e9294a0b

External saving is done through content resolvers as file managers in 7+ gives no way to access the canonical path of a file. Registering a file:// scheme would be flagged by the play store as unsafe, and registering it together with content:// simply did not work. Sorry about the inconvenience...

**Comment by Doublepicebs** [comment]
No problem,
But can't you use the same way of uploading  a "zip/image/.. etc" for editing a file on spck, then saving it locally?
