### ISSUE TITLE
Git push error

### ISSUE THREAD

**Issue by Ojile93** [spckio/spck-issues#611]
When ever I want to push my commit to github server, an error message with the below heading is always display 

"Push rejected because it was not a simple fast forward. Use force:true to override" 

Pls how do I solve this problem?

![Screenshot_20230403-232943_Spck Editor.jpg](https://user-images.githubusercontent.com/122288467/229644464-12914b08-7d16-409d-99a2-5d2e742564ec.jpg)

**Comment by eksonmude** [comment]
Me also

**Comment by spck-io** [comment]
Do a git pull first, resolve conflicts, then do a git push.
