### ISSUE TITLE
Unable to Login .

### ISSUE THREAD

**Issue by Redeemed-Michael** [spckio/spck-issues#618]
> 

Unable to login as this keeps happening. I have been struggling to login to SPCK with GitHub then I clicked sign in with Google then deleted the account and tried signing in with GitHub. It's letting me login. I have been trying this for days now. It's not working 
![216826326-a7efbee3-e937-414c-8d17-13dc165c055d](https://user-images.githubusercontent.com/131270160/233881669-71012e72-5fad-44a3-803d-8685722a6c6b.jpg)

**Comment by Aplha101** [comment]
> > 
> 
> Unable to login as this keeps happening. I have been struggling to login to SPCK with GitHub then I clicked sign in with Google then deleted the account and tried signing in with GitHub. It's letting me login. I have been trying this for days now. It's not working ![216826326-a7efbee3-e937-414c-8d17-13dc165c055d](https://user-images.githubusercontent.com/131270160/233881669-71012e72-5fad-44a3-803d-8685722a6c6b.jpg)

Have a look at #401

**Comment by Methylol** [comment]
I also can't log in with Google account.
Seems I'm getting an 403 Error probably since my location (USA sanctions, etc).
When I try with GitHub account, It just says "Internal error".
![Screenshot_20230430_232713_io spck](https://user-images.githubusercontent.com/88193952/235373848-f02e96ed-0b08-4ba1-94d7-bf1c6e1d158d.jpg)

**Comment by Davip8b3b** [comment]
Hello, I have the same problem, when trying to log in through github the same error appears.  What it seems is that the app identifies that the address on Google and on github is the same, however my Google account login was deleted more than 72 hours ago and is still appearing in the system.
![Screenshot_20230430-200426](https://user-images.githubusercontent.com/113862556/235380486-20d449b8-7fba-4dbe-bd35-f627db4e48c1.png)

**Comment by Bulie173** [comment]
Good day kindly assist I am unable to log in as I am getting an error stating there's another account with my email address but different credentials 

![Screenshot_2023-05-03-23-13-33-61_f9a7afa717ced9e1fc9be9833291031a](https://user-images.githubusercontent.com/132505732/236051723-75f58bcc-90d5-4d25-b7fe-71e3fa161c60.jpg)

**Comment by spck-io** [comment]
Account deletion should be fixed as of the latest version. Sorry for the inconvenience.
