### ISSUE TITLE
Function description box overflows screen, making it difficult to read

### ISSUE THREAD

**Issue by ManvendraSingh-007** [spckio/spck-issues#619]
When writing code, the function description is not properly aligned on the screen. The description box overflows the screen and we cannot see the full description. This makes it difficult to understand what the function does. Can you please fix this issue 😢

![Screenshot_2023-05-06-18-42-31-373](https://user-images.githubusercontent.com/94853003/236626754-dd1b4b39-4ca8-4d40-b75f-16a358e38ffb.jpeg)

**Comment by spck-io** [comment]
Thanks for the bug report. This should be fixed in the next version v8.0.2.0
