### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Doublepicebs** [spckio/spck-issues#62]
Well, this is not an issue, but what about setting up a discord server? For users and devs (only you?) can be in contact except keeping everything on GitHub

**Comment by Proxtx** [comment]
I created a community server

If Dev wants admin he will get but he didn't respond to your request 

[Discord Server](https://discord.gg/TBdaPq3)

**Comment by spck-io** [comment]
Closing this see #64 to join the community server. I will check on it once in a while for bugs and issues.
