### ISSUE TITLE
Usage issues， After running the code， The keyboard will not automatically focus

### ISSUE THREAD

**Issue by Huangyo66** [spckio/spck-issues#632]
Bluetooth keyboard will not automatically focus， Run Network Code， After returning, focus on each point before focusing， Very troublesome， After all, have you done it many times?

**Comment by Huangyo66** [comment]
Will not automatically focus after running the code, Just return to the code editing page without automatic focus, Why not autofocus?

**Comment by spck-io** [comment]
Thanks for the bug report. I think I got the issue, when exiting the preview, the editor does not automatically focus? Will look into a fix for this.
