### ISSUE TITLE
MergeNoCommonAncestryError

### ISSUE THREAD

**Issue by muzikeji** [spckio/spck-issues#640]
MergeNoCommonAncestryError
Merge failed because no common ancestor was found between
2acd4a523d6d1840dd9a02f3599bf21bcfd2cbe9 and refs/heads/main.

**Comment by spck-io** [comment]
The two branches you are trying to merge together has no common ancestors. You may have done a shallow clone on the repo at a time after the two branches diverged. Try doing a full repo clone by unselecting "Shallow Clone" option during clone. Unfortunately shallow repos cannot be converted into full ones within Spck Editor after cloning.
