### ISSUE TITLE
cannot open app when there is no network

### ISSUE THREAD

**Issue by tenzap** [spckio/spck-issues#643]
When opening the app I get this screen when there is no network enabled, or not connected to the internet.

![Imagepipe_1](https://github.com/spckio/spck-issues/assets/46226844/ccd224c0-3910-406f-bf6e-3d11ca1d9ca8)

**Comment by spck-io** [comment]
I cannot replicate this on my device. Can you please include more information? Thanks.

**Comment by tenzap** [comment]
Set the smartphone to flight mode (be sure the app is not opened in the background) and open the app. This triggers the issue for me.
Redmi note 9s, Android 12.
Is it still not reproducible?
What additional info would you need?

**Comment by spck-io** [comment]
I am not able to reproduce this on emulator, but I suspect it is either a 3rd party program that is blocking all connections when your phone is in Flight mode (i.e. Antivirus or Firewall app), or your OS (LineageOS maybe?) is modded to block connections when in Flight mode. I am currently investigating if there is a workaround when this happens.

**Comment by tenzap** [comment]
I don't precisely know why but I noticed that most times I have the problem described here, but once I didn't have it and spck editor opened even in offline mode.
