### ISSUE TITLE
My Google accounts is still being deleted.

### ISSUE THREAD

**Issue by mesterum** [spckio/spck-issues#647]
On spck.io I can't connect, neither create an account with my Gmail address because I had an account with Google on spck.io and long time ago I requested its deletion. 
When I try to login with Google I am refused with the message to wait 72 hours for my account to be deleted. 
The other 2 options: Facebook and Github are rejected with the message that I have already an account with the  same email address. 
Am I banned for life to use spck.io?

**Comment by spck-io** [comment]
I believe this should be fixed. Let me know otherwise.
