### ISSUE TITLE
Empty Projects Bug?

### ISSUE THREAD

**Issue by HenryLimaBR** [spckio/spck-issues#67]
When I create a empty project by choosing no js and no css framework. The project is created but I can't access it by clicking. After creating the project, I took a look at the "/data/data/io.scpk/files/" folder and realized that the project folder does not exist. sorry for the bad english.

Additional Details: If I create unnamed project, it works, but I can't create any file. If I create the project folder manually, it becomes impossible to delete until I delete the folder and try deleting again.

**Comment by Proxtx** [comment]
`[7:17:41 AM] [add]: /data/data/io.spck/files/Pong/main.js`
`[7:18:23 AM] [add]: /data/data/io.spck/files/main.js`
The first message is from a normal project (pong), but the second is from the empty project. It seems like it is saving it's files to the home directory and not to a specific folder.

If you start the preview now you will see your last project.

AND if you press 'View in Browser' it will go to your last projects path. If you now go to [localhost:7700](http://localhost:7700/) you will see: 'Nothing to see here' the standard html-code. If you open Spck again and tab on the project you will be able to edit `ain.js`.
I don't know why the 'm' is missing but if you edit 'ain.js' for example: 'alert("Hello World")' and now reload the page in your Browser ....... TA DA an Alert dialogue YAY


PLS join our [Spck - Community](https://discord.gg/TBdaPq3) Discord Server

**Comment by spck-io** [comment]
Thanks for the bug report and @Proxtx thank you for the work around. This is due to a recent hot fix that lets users revert back empty FS projects to IDB if available. This has been already fixed but not yet released. You could use the templates to create a non empty project and then just delete the extra files. Sorry for the inconvenience...
