### ISSUE TITLE
Login problem 

### ISSUE THREAD

**Issue by Peacemaker675** [spckio/spck-issues#671]
When I try to login from my GitHub account it says an account with this email address exist with different credentials
I did have a Google account on spck with that email address but I deleted it why it's not letting me log in ?

**Comment by Fenriros** [comment]
> When I try to login from my GitHub account it says an account with this email address exist with different credentials
> I did have a Google account on spck with that email address but I deleted it why it's not letting me log in ?

Same

**Comment by spck-io** [comment]
It takes a few days for the account to be deleted to prevent abuse.
