### ISSUE TITLE
Volume button movement toggle continues after finger is lifted

### ISSUE THREAD

**Issue by waynemwashuma** [spckio/spck-issues#672]
When I press on the volume button once,the text pointer continues to scroll indefinitely to right or left even though I only want it to move one character to the left or right.

I have to press onto the screen again in order to make it stand still.

https://github.com/spckio/spck-issues/assets/94756970/33c8f90a-fbbb-4d2a-9697-3b4fe3251c37

**Comment by waynemwashuma** [comment]
As you can see in the video,the pointer just moves left to right without stopping.
This makes it hard to do precision scrolling with the pointer.

You can also see the left and right buttons on top of the keyboard are active even though I am not pressing on the volume buttons.

**Comment by bkmkmon** [comment]
The same problem, please fix!

**Comment by victoryosiobe** [comment]
Exactly what i'm facing. I even did a screen record only to find this issue is here already. I think it came with the latest update (8.0.5.3 (Aura)).

**Comment by spck-io** [comment]
Sorry for the late reply. Thanks for the bug report. This has been fixed in the upcoming release 8.0.8.0

**Comment by waynemwashuma** [comment]
Thanks for fixing the bug.
