### ISSUE TITLE
Can't push on custom branches.

### ISSUE THREAD

**Issue by afaeid** [spckio/spck-issues#676]
I created a custom branch on Github. Then I tried to push my codes on that custom branch. It failed to push codes. Why does it happen even though there is option for adding custom branch on the branch sub-section under the git section? Isn't it a bug?

**Comment by spck-io** [comment]
I cannot duplicate this issue. I have tried creating a new branch under "Branch". Checkout this new branch, using the Checkout option and then Push. This is working for me. Can you update with more details?

**Comment by afaeid** [comment]
Sorry! Maybe I had done any mistake earlier. Now, I've followed your instructions and it works. Do you have any video tutorial over SPCK Editor? The web docs is backdated, I think.
