### ISSUE TITLE
Cannot clone public git repository

### ISSUE THREAD

**Issue by XygenSS** [spckio/spck-issues#678]
![Screenshot_2023-12-24-17-49-34-987_io.spck-edit.jpg](https://github.com/spckio/spck-issues/assets/27952407/8285f245-0db5-422d-a6fd-be819cce9078)

See attached screenshot. Was attempting to clone a public fork of https://github.com/CleverRaven/Cataclysm-DDA. App throws an error and project fails to create.

Device: Xiaomi Pad 6 Pro
OS Version: Manufacturer: Xiaomi; Model: 23046RP50C; Release: 13; Incremental: V14.0.9.0.TMYCNXM;
App version: 8.0.6.0 downloaded from Play store

**Comment by spck-io** [comment]
This is due to a OutOfMemory Error in Java. The repo you are trying to clone is way too big for your phone to handle. If even a shallow commit does not work then you cannot clone this with Spck Editor.
