### ISSUE TITLE
projects not deleting

### ISSUE THREAD

**Issue by bitt0008** [spckio/spck-issues#69]
so when i try to delete a project - it doesnt do anything.
from google play store, 0.8.6, android 7.0

**Comment by spck-io** [comment]
Are you still having this issue with the latest release?

**Comment by bitt0008** [comment]
> Are you still having this issue with the latest release?

yep.

**Comment by spck-io** [comment]
Thanks this is very helpful. Did you upgrade the Android app to the latest version (3.0.9), this seems similar to an older bug in a previous Android app version. Do you get this error with new projects? Does this project have “IDB” label next to it?

**Comment by spck-io** [comment]
Are you still seeing this issue on 0.9.8? I suspect that this is an older project created with a previous version of the editor. I added some failsafe conditions to the editor for those cases.

**Comment by ghost** [comment]
oh sorry, completely forgot about github. i dont have the time to check it out, does it work for you personally?

**Comment by spck-io** [comment]
I never encountered this bug personally yet. Would be really helpful to get some logs or screenshots to give me a clue how this is happening. I did make a few changes to the delete project in previous versions in hopes it could solve some of these issues.

**Comment by spck-io** [comment]
Closing this as it’s a duplicate of #93
