### ISSUE TITLE
Keyboard auto-popup

### ISSUE THREAD

**Issue by Doublepicebs** [spckio/spck-issues#70]
When I press run button, the keyboard pops up without the presence of any field ! (Maybe because the console has its text area auto focus?)

**Comment by spck-io** [comment]
Thanks for the bug report, I will check it out.

**Comment by spck-io** [comment]
Is this still happening with the latest Android version? I added some flag to the console to try and prevent this.

**Comment by Doublepicebs** [comment]
Nope, fixed! Thanks a lot!! 👍
