### ISSUE TITLE
Allow to change path

### ISSUE THREAD

**Issue by ahmadbhai78692** [spckio/spck-issues#714]
I want to create a folder for my projects and I want to save my all projects in that folder but there is no option for change path 😔😔😔 
Please solve this problem and add a option to change path/directory/folder
Please add this option and Ctrl button also

I will be very grateful to you
Your permanent user....

**Comment by spck-io** [comment]
Sorry, this has been a long requested feature, but the Android OS does not allow arbitrary apps to do this. There are a set of hurdles to jump through for the app to be classified as a filemanager application and there are severe security restrictions with doing so that will cripple the app.
