### ISSUE TITLE
New Design (small mistake)

### ISSUE THREAD

**Issue by Proxtx** [spckio/spck-issues#74]
If you press the plus icon in the editor, the extended sheet will have a different color.
![Screenshot_20200109-164646](https://user-images.githubusercontent.com/39201896/72082042-db913f80-32ff-11ea-9cad-f541c0d8e1ca.png)
By the way: to everyone who is reading this: you can join the Spck - Community Discord Server

**Comment by spck-io** [comment]
Thanks for the bug report, will have a look tonight.
