### ISSUE TITLE
Can't Mode Landscape

### ISSUE THREAD

**Issue by SharkyA7** [spckio/spck-issues#744]
Can You At least Make The App Can Mode Landscape

**Comment by nexoscreator** [comment]
Already this feature here
Go Spck Editor > Settings Tab > Mobile Catagaory
Here you can find out Orientation

![IMG_20241204_205531](https://github.com/user-attachments/assets/6f5efd41-b402-4757-abf8-0155261eb9d8)

By Default Is `Auto`
Also you can mack it permate `Landscape`

![IMG_20241204_205549](https://github.com/user-attachments/assets/88b499b6-5a56-4bc6-a839-0f68ad2704e9)
