### ISSUE TITLE
Search projects doesn't work

### ISSUE THREAD

**Issue by Doublepicebs** [spckio/spck-issues#77]
File search works, yet not project search

**Comment by Doublepicebs** [comment]
Although it used to work previously

**Comment by spck-io** [comment]
Thanks for the bug report. How is it failing? I’m trying but I can’t seem to replicate this.

**Comment by Doublepicebs** [comment]
I write in the search box, press search and nothing happens. All projects are still in their order, and the result isn't filtered. Here, have a look:
If you don't see the video attached bin this comment, see it here > 
https://drive.google.com/file/d/1S86JbrrMbyH7aRSN_FVG_cldZk-O-cPy/view?usp=drivesdk

**Comment by spck-io** [comment]
Thanks, I got confused with the file search feature. I added some test to the project search and fixed it in the latest release 0.9.7
