### ISSUE TITLE
Blinking cursor not properly aligned on editor

### ISSUE THREAD

**Issue by jepsuCoded** [spckio/spck-issues#8]
The blinking cursor are not aligned properly making it hard to type anything at all since its on the wrong place. The more the characters are there in line the farther the indicator is. See the low quality GIF below.

![20181108_192922](https://user-images.githubusercontent.com/40726737/48196667-2925bb80-e38e-11e8-90d9-ef82e4b90c68.gif)

**Comment by spck-io** [comment]
What version of Android are you using? (4.4 Kitkat?) It seems your webview in the app is overriding the default fonts used in the app, and even the default monospaced fonts are not loading in your android version. Does using the web app in Chrome align the characters properly? (https://spck.io)

**Comment by jepsuCoded** [comment]
My phone is Vivo y53 and it has its own rom called funtouch OS, the android version is 6.0.1.

**Comment by jepsuCoded** [comment]
My phone is Vivo y53 Android 6.0.1 Marshmallow with funtouch os rom, I've
tried it in Chrome and the problem is still the same, its not properly
aligned.

**Comment by spck-io** [comment]
I have included an emergency backup monospace font in the latest (0.4.3) version of the web app. Are you still seeing this issue? You might have to reload the app to see the update.

**Comment by jepsuCoded** [comment]
Sorry for late reply, unfortunately yes I'm still seeing the issue I've also tried it in Chrome and still the same.

**Comment by spck-io** [comment]
No worries, quite a strange problem. Can you screen shot what you see on this page?
https://spckio.github.io/spck-documentation/browser-font-test.html

If all of these fonts appear the same to you, can you see any special fonts on other websites? If so can you link me a page with a different font so I can see what they are doing differently?

**Comment by spck-io** [comment]
Thank you so much for doing this. It really helped me figure out the problem. I have updated the web app with a font that should not conflict. Hopefully this fixes your issue, you may need to restart the app once or twice.

Just for curiosity sake :), I updated the test site with the monospace fallback fonts used in the editor: https://spckio.github.io/spck-documentation/browser-font-test.html Just want to know which of these fonts caused the problem for you. Thanks again!

**Comment by spck-io** [comment]
Glad to hear this issue is finally resolved. I learned some new things as well, thanks for all your help! If you find any other issues, please let me know here and I'll do my best to help if I can.
