### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by Proxtx** [spckio/spck-issues#81]
Touch Features are disabled by default .. I don't think that this is an good idea because pwas are only working on mobile devices

**Comment by spck-io** [comment]
I haven’t seen this issue on my test devices. The touch feature is enabled only if the device is touch capable. On non-touchscreen devices it will default to off. What device are you seeing this on?

**Comment by Proxtx** [comment]
If you open it in the browser before adding the page to the home screen
