### ISSUE TITLE
Can't scroll

### ISSUE THREAD

**Issue by Doublepicebs** [spckio/spck-issues#83]
If I press on the (+) icon while the keyboard is active, this will activate a bug where I won't be able to scroll as long as the keyboard is active. Needs app restart to deactivate this bug, but will return back if do the same steps mentioned above.

**Comment by Proxtx** [comment]
Yes also saw that bug... You can scroll but only in the top-half of the screen

**Comment by spck-io** [comment]
Thanks for the bug report! This is very useful. Will check it out as soon as possible.

**Comment by spck-io** [comment]
This issue has been fixed in 0.9.10
