### ISSUE TITLE
File save operations are destructive if terminated early

### ISSUE THREAD

**Issue by Doublepicebs** [spckio/spck-issues#86]
I was working on a HTML file and I spent **2 HOURS** working on it... Suddenly the app became too lagy so I decided to restart the app. After I restarted it I was surprised that the file started again at line 1... Yes, all what is did was gone...
I am so sad about what happened, 
I hope you fix that bug soon. Thanks...

**Comment by Proxtx** [comment]
A entire project disappeared but I had a backup

**Comment by spck-io** [comment]
I’m so sorry to hear that this happened... I’ll do my best to see if I can fix this. Can you guys please provide any additional details on what happened before this? Did anything strange happen? Again, I’m very sorry this happened...

Is this a file opened using another app, or it’s created from the editor? There are different methods of saving depending on if it’s an external file or internal file, that can help me diagnose the issue.

**Comment by Proxtx** [comment]
I just started the app. It was the last project I edited and it had a lot of images.

**Comment by Proxtx** [comment]
[7:49:02 AM] [add]: /data/data/io.spck/files/Vodobanka Map Walker/main.js
[7:49:02 AM] [clear]: css
[7:49:02 AM] [clear]: html
[7:49:02 AM] [clear]: javascript
[7:49:02 AM] [clear]: css
[7:49:02 AM] [clear]: html
[7:49:02 AM] [clear]: javascript
[7:49:02 AM] Starting language server
[7:48:56 AM] File threshold exceeded for auto file import.
[7:48:56 AM] Could not find parent for: /data/data/io.spck/files/Vodobanka Map Walker
[7:48:56 AM] [git:currentBranch] Could not resolve reference "HEAD".

happened again but ... Both projects were created in the editor. I opened the app (with a poor internet connection). The name of the project was Fluid

**Comment by Proxtx** [comment]
And it was the last project I edited

**Comment by Proxtx** [comment]
But the folder / project still exists... If I try to open http://localhost:7700/Fluid/index.html. Chrome will load it. The project is not listed in the editor but still exists

**Comment by spck-io** [comment]
Thanks for the extra details, I am very sorry this happened again... It seems like a bug again with indexedDB dropping some entry in the database. I have a backup of projects in the filesystem but it’s first choice is to go to indexedDB for a list of projects.

Not entirely sure why indexedDB is losing records, but I think the editor can just read a list of projects from the filesystem.

This seems unrelated to @Doublepicebs issue, I think it’s possible to implement a file backup system in case the operating system is not actually saving the files properly (no errors thrown by OS).

**Comment by spck-io** [comment]
Additionally I will change the git interface so that local repositories can be created without linking to a remote. That way you can back up your files through git index files which will provide another layer of protection.

**Comment by Doublepicebs** [comment]
Unfortunately I couldn't find the log.
The strange thing is that the editor started to lag and became slow. That's why I restarted it in first place.

**Comment by spck-io** [comment]
I have made several changes in the recent update, listed in detail below:

1. Failed saves (if not silently thrown in Android code) will result in a “Unsaved” status indicator next to the filename and also a Toast message. Clicking the “Unsaved” will attempt to save the file again if possible.
2. Simplified saving call chain to prevent race conditions and unintended side effects.
3. Backups of the last edited file will be made every 10 seconds to indexedDB defaulting to localStorage if indexedDB is unavailable. A check with the filesystem version of the file will be made when editor switches files, then if there are discrepancies, the newer file will be saved with a ~ suffix (to avoid overwrite or any file permission errors at the OS layer)
4. Improved git support allows for local branches without remotes to allow backups through git (make commits frequently to avoid data loss)
5. Project backend rewritten to avoid any dependency on indexedDB, an extra file is used just to store project metadata and the project list reflects directly with what’s on the filesystem.

**Comment by spck-io** [comment]
Actually, thinking this problem over again, it’s possible that the lag is causing the save operation to take longer than it should. When you force quit the app it’s possible the previous auto save has not finished and left an opened write stream to the file that was not closed properly in Android. I will implement a fix for this scenario in the next Android update which will write to a temporary file and rename the the temporary file to the actual file to prevent corruption from an unfinished write operation.

**Comment by spck-io** [comment]
The editor is now using “atomic” file saves. This should no longer be an issue starting from 0.9.16. Please reopen if something similar to the above happens in the latest version.
