### ISSUE TITLE
Git Push And Over-all Scrolling Animation Lag

### ISSUE THREAD

**Issue by alenpaulvarghese** [spckio/spck-issues#87]
Git Push is not working for me , thats what i feel. Pushing brings up a Toast icon in the top which seems not to be responding.

reference: https://ibb.co/HVrPNmC

Scrolling Animation getting a bit laggy.

spec : snapdragon 636 Soc , 4Gb ram , Android 10

**Comment by spck-io** [comment]
It’s possible the push serialization is very slow for a large repo. The speed of the git library the editor is using is not on par with native git and might be very slow for larger repos. Is scrolling animation of the editor or with the files/projects side menu?

**Comment by alenpaul2001** [comment]
> It’s possible the push serialization is very slow for a large repo. The speed of the git library the editor is using is not on par with native git and might be very slow for larger repos. Is scrolling animation of the editor or with the files/projects side menu?



> It’s possible the push serialization is very slow for a large repo. The speed of the git library the editor is using is not on par with native git and might be very slow for larger repos. Is scrolling animation of the editor or with the files/projects side menu?

I was talking about the lag in editor

**Comment by alenpaulvarghese** [comment]
> It’s possible the push serialization is very slow for a large repo. The speed of the git library the editor is using is not on par with native git and might be very slow for larger repos. Is scrolling animation of the editor or with the files/projects side menu?

I was talking about the animation lag in the editor
