### ISSUE TITLE
Can't delete projects, again

### ISSUE THREAD

**Issue by Doublepicebs** [spckio/spck-issues#93]
This bug was that I couldn't delete JS (no js framework) projects, but I found that now I can't delete HTML (plain HTML) ones either.

**Comment by spck-io** [comment]
Are you still having this issue in the latest version 0.9.12? Do you get any sort of errors when trying to delete? Is this happening to new projects or just a few old ones?

**Comment by Doublepicebs** [comment]
Yes, not solved yet. Nope, no errors, neither in the log. Relatively new ones (made on about 0.9.7 or higher)

**Comment by spck-io** [comment]
This is quite an old issue, are you still experiencing this on the latest version? If not, would like to close this.

**Comment by bitt0008** [comment]
> This is quite an old issue, are you still experiencing this on the latest version? If not, would like to close this.

hey, its me again.

im still having this issue with some of the project that are not marked "IDB".

**Comment by Doublepicebs** [comment]
Still, projects don't get deleted.

**Comment by Doublepicebs** [comment]
@spck-io 
Here is something I found in the logs when I tried to delete a project.
![Screenshot_20200411-192454](https://user-images.githubusercontent.com/51971241/79050449-5da84180-7c2a-11ea-832f-574dc4ada5da.png)

**Comment by Doublepicebs** [comment]
Notice the "cannot find parent for" which seems to be the primary problem
