### ISSUE TITLE
 [git:clone] Java exception was raised during method invocation

### ISSUE THREAD

**Issue by grm34** [spckio/spck-issues#94]
Hi and thank you for your work.
Cloning any github repo failed each time, same error with token or username/password way.

**Comment by spck-io** [comment]
Something is going wrong with filesystem access in the git library. Are you on the latest app version, also are you encountering any other issues with read/write files?

**Comment by grm34** [comment]
I'm on v3.1.1 build v0.9.12. Storage access granted. Cloning any repo falls on Java Exception but after app restart repo show up with no access to folder: `Could not find parent for: /data/data/io.spck/files/project_name`
By the way zip method works without any read/write issue.
No ident for bash? Thank you
