### ISSUE TITLE
"Serialized Value is too large" while cloning from github

### ISSUE THREAD

**Issue by KataiKi** [spckio/spck-issues#95]
Trying to clone my project from GitHub (https://github.com/KataiKi/Fate-Grand-Order_Lua.git)

`UNKNOWN ERROR
The serialized value is too large (size=356437613 bytes, max=267386880 bytes).`

The project is only 52mb (mostly image files), which is a far cry away from the 256mb limit here.

**Comment by spck-io** [comment]
I will take a look at this. Are you using the latest android app from the play store 3.1.1? The max file size serialization is only a problem with using indexedDB which shouldn’t be possible in the latest Android version. It’s also possible the git index file is over 250mb as it contains all the history of all files ever created in the repo.
