### ISSUE TITLE
All projects disappeared

### ISSUE THREAD

**Issue by Doublepicebs** [spckio/spck-issues#96]
Even the log history... All what's still saved is the theme and font size

**Comment by Doublepicebs** [comment]
It even prevents me from creating new projects

**Comment by byrz-ell** [comment]
can't create project

**Comment by Stefenn** [comment]
All projects dissapeared and can't create project too. Even i uninstall it doesnt work!

**Comment by Doublepicebs** [comment]
Can't even clone a GitHub repo, telling me there is no internet and another strange message (checked my internet, it works at 5mb/s)
![Screenshot_20200228-124249](https://user-images.githubusercontent.com/51971241/75542193-f8a4dd80-5a27-11ea-9bea-534821815eee.png)

**Comment by ternengesam** [comment]
lost all my project(data) notin is left

**Comment by spck-io** [comment]
Do not uninstall that will actually delete your files. I have reverted to the previous version, hope that recovers your projects.

**Comment by spck-io** [comment]
Sorry for the bad update 😰. I think the revert should bring back all your projects, unless you have already uninstalled. Please restart the editor a couple of times with a working internet connection to receive the update. I’m currently working on the next android version and I changed the way read projects directory works, however it seems the new API is not compatible with previous API call. Deeply sorry to all users who have lost their project, but DO NOT UNINSTALL your projects should be still recoverable.

**Comment by spck-io** [comment]
To clarify what happened: There were new parameters added to readdir called foldersOnly, filesOnly that are passed the variables to Java. Java code cannot handle these additional parameters in the previous version (I was testing on an unreleased version of the Android app), so readdir throws an error that resulted in this disaster. Deeply sorry for what happened.

I’ll make sure this sort of thing never happens again by removing auto updating in the next Android version. I promise the next Android release would be great, and much more stable. The next Android version will have a brand new console interface, and “hasFragileUserData” to allow data to be kept between uninstalls on the new Android 10, removing the auto update will also speed up editor loading times.

**Comment by Doublepicebs** [comment]
Thanks and good job! They are back!

**Comment by Tekpriest** [comment]
when is th

**Comment by ternengesam** [comment]
when is the update coming in i cant after reading that mail

**Comment by spck-io** [comment]
You need to refresh the app, by force quitting and restarting a couple of times. The update has already been published.

**Comment by brettjrea** [comment]
I actually was effected by this when it happened and a few days later. I luckily commit and push regularly. So just readd what I want to work with.

**Comment by Proxtx** [comment]
Spck editor have an index of all projects. If a project were removed from the index you won't be able to open it again in the editor but you can write http://localhost:7700/ plus the name of the lost project plus /index.html into your browser and you will be able to see your project again now you can use this tool: https://play.google.com/store/apps/details?id=com.httrack.android to download all your files from the localhost.

**Comment by brettjrea** [comment]
That's actually pretty cool to know, I am having copy, pasting, and highlighting selection issues so I'm not using it at all at the moment but definitely am hoping too in the future.
