### ISSUE TITLE
Issue with text selecting/highlighting

### ISSUE THREAD

**Issue by nibmz7** [spckio/spck-issues#98]
On Android. This issue just came up after the last update. It will select a whole word without the two accompanying indicators so am unable to highlight a specific block of text.

Anyways, your app is a lifesaver. I'm away from home 90% of the time and am not able to bring my laptop around so this app has helped increased my productivity by leaps and bounds. Thank you!

**Comment by nibmz7** [comment]
![Screenshot_2020-03-01-22-32-33-785_io spck](https://user-images.githubusercontent.com/14259666/75627605-93f6a800-5c0c-11ea-9dc4-13d41ebf0195.jpg)

**Comment by Doublepicebs** [comment]
Indeed this happens to me, but the "paste - copy - select all" popper doesn't even get shown with me.

**Comment by gipsi** [comment]
I'm getting no cut, copy, paste, sometimes 'paste' and 'select all' but when (all) text is highlighted, no popup to copy with.

**Comment by spck-io** [comment]
I have released an update fixing this 0.9.17. Also 4.0.0 has been released with a lot of major improvements. Please upgrade when you feel ready (backup projects is recommended)
